### ISSUE TITLE
Analytics: batching support tracker

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#12268]
This is a tracker for the analytics batching support features

- [ ] Add `batchSegment` support
- [ ] Add basic `batchInterval` support
- [ ] Add decay `batchInterval`support
- [ ] Finalize on the aggregation and other operator design
- [ ] Add aggregation support
- [ ] Add filter support to only send 'last'/'first'/... batched segment

**Comment by lannka** [comment]
Decided to go with batch plugin solution: #12432
