### ISSUE TITLE
[Master feature] Leaner AMP

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#14392]
Goal: Reduce size of AMP’s main JS binary by 50%.
Corollary: Do not regress parse, compile, and execution time of the JS.

**Comment by choumx** [comment]
Work for Q2 2018:
- [ ] Automated binary size tracking & dashboard
- [ ] Deliver module/no-module versions of AMP main JS binary
- [ ] Bundle analysis and strategy planning
- [ ] Reduce binary size by 10%

**Comment by choumx** [comment]
Bundle analyses from April 3, 2018:

- `v0.js` + [source-map-explorer](https://github.com/danvk/source-map-explorer) -- https://choumx.github.io/amphtml/sme_0403.html
- `amp.js` + [disc](https://github.com/hughsk/disc) -- https://choumx.github.io/amphtml/disc_0403.html

**Comment by choumx** [comment]
Note: Individual tasks tracked in [Build Size](https://github.com/ampproject/amphtml/projects/45) project.

**Comment by choumx** [comment]
Accidental close.

**Comment by rsimha** [comment]
Sheesh, `Required in order to fix` closed this :/

**Comment by kristoferbaxter** [comment]
Closed in favor of #16745.
