### ISSUE TITLE
[Master feature] amp-consent support in amp-story

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#14538]
Bring the feature described in #13716 into amp-story.

**Comment by jasti** [comment]
- [ ] Optionally block publisher served ads based on consent status https://github.com/ampproject/amphtml/issues/14548

**Comment by gmajoulet** [comment]
- [ ] ``<amp-story-consent>`` component #15062
- [ ] Validator
- [ ] Change to use CSS variables to configure the main color
- [ ] Switch from simple template to ``htmlFor``

**Comment by jasti** [comment]
- [ ] Update  amp-consent [availability](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#integrations-and-availablity) and docs

**Comment by rudygalfi** [comment]
@gmajoulet Can you provide any update on status here and do [this step](https://github.com/ampproject/amphtml/issues/14538#issuecomment-386486395) if ready?

**Comment by gmajoulet** [comment]
The documentation is [live here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#prompt-ui-for-stories), and I will update this issue as soon as the ampbyexample page is published.

**Comment by jeffjose** [comment]
Is there any work pending here?

**Comment by gmajoulet** [comment]
I believe we are feature complete. Closing this ticket.
