### ISSUE TITLE
[Master Feature] Enhancements to amp-consent

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#15651]
This is a master issue to track the second phase of amp-consent which focuses on more advanced use cases of amp-consent. All active features in discussion from the initial amp-consent [implementation] (#13716 ) have been moved to this issue.

**Comment by jasti** [comment]
**amp-consent core feature enhancements**

- [ ] [Support external consent flow using amp-consent within amp-iframe](https://github.com/ampproject/amphtml/issues/14913)
- [ ] [Allow amp-consent state to customize content](https://github.com/ampproject/amphtml/issues/15561)
- [ ] [Support <amp-analytics> vendors to get consent status](https://github.com/ampproject/amphtml/issues/14916)
- [ ] [Make amp-consent status available as a substitution variable](https://github.com/ampproject/amphtml/issues/15267)
- [ ] [Call pub configured endpoints when user acts on consent](https://github.com/ampproject/amphtml/issues/15238)
- [ ] [Add pre-defined consent policy to make it easier to implement amp-consent](https://github.com/ampproject/amphtml/issues/15290)
- [ ] [Per Vendor, per purpose consents](https://github.com/ampproject/amphtml/issues/15653)
- [ ] [Support <amp-consent> block configuration using checkConsentHRef](https://github.com/ampproject/amphtml/issues/14920)

**amp-consent integrations** 
- [ ] [Provide an option to hide the amp-story-consent decline button](https://github.com/ampproject/amphtml/issues/15570)
- [ ] [amp-story-consent should prevent auto advance in the background](https://github.com/ampproject/amphtml/issues/15430)

**amp-consent postPromptUI**
- [ ] [Support inline postPromptUI](https://github.com/ampproject/amphtml/issues/14893)

**Comment by jpettitt** [comment]
Related issue

- [ ] [Add geo support to user notifications](https://github.com/ampproject/amphtml/pull/15648)

**Comment by QES** [comment]
Is there a way to make amp-consent work with the IABs https://advertisingconsent.eu/ consent framework and integrate into the advertising tools that they provide and pass to ad units.

**Comment by zhouyx** [comment]
@QES That's one of the master feature that has been prioritized.  The issue can be tracked at #15653

**Comment by jasti** [comment]
@QES Which CMP do you use?

**Comment by QES** [comment]
@jasti work with people who provide our advertising so we have moved around over the last few months, we just moved with the whole GDPR to someone who understood the issue and implemented a solution which we could implement as a first step with amp-consent and I think we are currently using appnexus (but we have used others in the past).

**Comment by jasti** [comment]
@QES we are happy to collaborate with your CMP to provide an AMP compatible IAB solution. Please have them express interest here:  https://github.com/ampproject/amphtml/issues/15653

**Comment by ampprojectbot** [comment]
This issue seems to be in  Pending Triage for awhile. @zhouyx Please triage this to an appropriate milestone.
