### ISSUE TITLE
🚄Release tracking issue for canary release 1529106593171 (Production)

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#15992]
# Release tracking issue

- [x] Release [1528302494869](https://github.com/ampproject/amphtml/releases/tag/1528302494869) cut as canary
- [x] Release 1528302494869 pushed to Dev Channel
- [x] Release 1528302494869 pushed to 1%
- [x] Release [1528391646530](https://github.com/ampproject/amphtml/releases/tag/1528841168349]) cut with cherry picks
- [x] Release 1528841168349 pushed to Dev Channel
- [x] Release 1528841168349 pushed to 1%
- [x] Release [1528841168349](https://github.com/ampproject/amphtml/releases/tag/1528416097273) cut with cherry picks
- [x] Release 1528841168349 pushed to Dev Channel
- [x] Release 1528841168349 pushed to 1%
- [x] Release 1528841168349 pushed to production
- [x] Release [1529106593171](https://github.com/ampproject/amphtml/releases/tag/1529106593171) cut with cherry picks.
- [x] Release 1529106593171 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).

**Comment by adelinamart** [comment]
We have a new release, 1528841168349, so closing this one.

**Comment by adelinamart** [comment]
- [ ] NEW Cherry pick release [1529106593171](https://github.com/ampproject/amphtml/releases/tag/1529106593171) pushed to Dev Channel
  - [ ] Cherry pick release 1529106593171 pushed to 1%

If the cherry pick is made to the release in production, you may also need to
add a checkbox like:
  - [ ] Cherry pick release 1529106593171 pushed to production
