### ISSUE TITLE
🚄Release tracking issue for release 1529449959701 (Production)

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#16025]
# Release tracking issue

- [x] Canary release [1528909142235](https://github.com/ampproject/amphtml/releases/tag/1528909142235) is cut
- [x] Canary release 1528909142235 pushed to Dev Channel
 - [x] Cherry pick release [1529035559569](https://github.com/ampproject/amphtml/releases/tag/1529035559569) pushed to Dev Channel
 - [x] Cherry pick release 1529035559569-old pushed to 1%
 - [x] Cherry pick release 1529035559569-old pushed to production
-  [x] Cherry pick (PR #16077) release 1529449959701 to production 

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).

**Comment by jridgewell** [comment]
This is already in production. Closing.
