### ISSUE TITLE
🚄Release tracking issue for canary release 1529691528033 (Canary)

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#16178]
# Release tracking issue

- [x] Release [1529458017017](https://github.com/ampproject/amphtml/releases/tag/1529458017017) is cut as a new canary release
- [x] Release 1529458017017 pushed to Dev Channel
- [x] Release 1529458017017 pushed to 1%
- [x] Release [1529691528033 ](https://github.com/ampproject/amphtml/releases/tag/1529691528033) created with cherry picks.
- [ ] Release 1529691528033 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by jridgewell** [comment]
This is being patched with #16375 and #16385. See https://github.com/ampproject/amphtml/issues/16388 for updates on the cherry-picks and rollout.
