### ISSUE TITLE
🚄Release tracking issue for release 1530043289240 (Production)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#16388]
(Will update with release number shortly)

# Release tracking issue

- [x] Release [1530043289240](https://github.com/ampproject/amphtml/releases/tag/1530043289240) created with cherry picks.
- [x] Release 1530043289240 pushed to Dev Channel
- [x] Release 1530043289240 pushed to 1%
- [x] Release 1530043289240 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by jridgewell** [comment]
Travis build for this release is at: https://travis-ci.org/ampproject/amphtml/builds/397046064

**Comment by jridgewell** [comment]
I'm including https://github.com/ampproject/amphtml/pull/16338, because it's failing tests.

**Comment by jridgewell** [comment]
Patched canary pushed to Dev Channel.

**Comment by jridgewell** [comment]
Released to prod and 1%.
