### ISSUE TITLE
🚄Release tracking issue for canary release 1530221685242 (Canary)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#16447]
# Release tracking issue

- [x] Release [1530221685242](https://github.com/ampproject/amphtml/releases/tag/1530221685242) is cut as a new canary release
- [x] Release 1530221685242 pushed to Dev Channel
- [x] Release 1530221685242 pushed to 1%
- [ ] Release 1530221685242 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by jridgewell** [comment]
Moving to https://github.com/ampproject/amphtml/issues/16488 after patching with cherry-pick https://github.com/ampproject/amphtml/issues/16486.
