### ISSUE TITLE
🚄Release tracking issue for release 1530320824316 (Production)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#16488]
# Release tracking issue

- [x] Release [1530320824316](https://github.com/ampproject/amphtml/releases/tag/1530320824316) is cut as a new canary release
- [x] Release 1530320824316 pushed to Dev Channel
- [x] Release 1530320824316 pushed to 1%
- [x] Release 1530320824316 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by jridgewell** [comment]
This is a cherry-pick of https://github.com/ampproject/amphtml/issues/16486 onto canary https://github.com/ampproject/amphtml/issues/16447.

**Comment by cvializ** [comment]
The promote triggered a P0 https://github.com/ampproject/amphtml/issues/16671
