### ISSUE TITLE
🚄Release tracking issue for canary release 1531800879103 (Canary)

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#16669]
# Release tracking issue

- [x] Release [1531800879103](https://github.com/ampproject/amphtml/releases/tag/1531262625717) is cut as a new canary release
- [x] Release 1531800879103 pushed to Dev Channel
- [x] Release 1531800879103 pushed to 1%
- [x] Release 1531800879103 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by cathyxz** [comment]
I'm noticing that the release number on this issue does not match the current canary which is https://github.com/ampproject/amphtml/releases/tag/1531357871900 . I imagine that the release number changed after the cherry pick. @lannka can you verify?

**Comment by aghassemi** [comment]
In prod.
