### ISSUE TITLE
single pass closure compiler issue tracker

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#16847]
below are sub tasks required to get single pass closure compiler working

- [x] lazy load intermediate bundle
- [x] green tests on travis builds
- [ ] conformance checks/tests for code motion
- [ ] fix amp-date-picker bug
- [ ] fix sourcemaps
- [ ] remove special `-sp` suffix in error reporting when it becomes the main binary for prod traffic

**Comment by ampprojectbot** [comment]
This issue seems to be in  Pending Triage for awhile. @cramforce Please triage this to an appropriate milestone.

**Comment by rsimha** [comment]
@erwinmombay Can this be closed out?

**Comment by rsimha** [comment]
Rolled in the tasks from #18811 into this.

**Comment by rsimha** [comment]
Moving this over to @ampproject/wg-performance for triage and prioritization.

**Comment by erwinmombay** [comment]
closing as this is obsolete.
