### ISSUE TITLE
🚄 Release tracking issue for 1533058547995 (Canary)

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#17097]
### **Please Note:** This week's release is delayed. `Current ETA is Thursday August 2, 11 AM PST (6 PM UTC)`

# Release tracking issue

- [x] Release [1532461037969](https://github.com/ampproject/amphtml/releases/tag/1532461037969) is cut as a new canary release
- [x] Release 1532461037969 pushed to dev channel (2:49 PM, Jul 25, 2018 UTC-4)
- [x] Release [1532641868525](https://github.com/ampproject/amphtml/releases/tag/1532641868525) created with cherry picks.
- [x] Release 1532641868525 pushed to dev channel (10:22 PM, Jul 26, 2018 UTC-4)
- [x] Release 1532641868525 pushed to 1% (10:22 PM, Jul 26, 2018 UTC-4)
- [x] Release [1533058547995](https://github.com/ampproject/amphtml/releases/tag/1533058547995) created with cherry picks.
- [x] Release 1533058547995 pushed to dev channel
- [x] Release 1533058547995 pushed to 1%
- [x] Release [1533168552513](https://github.com/ampproject/amphtml/releases/tag/1533168552513) created with cherry picks (August 2, 2018)
- [x] Release 1533168552513 pushed to dev channel
- [x] Release 1533168552513 pushed to 1%
- [x] Release 1533168552513 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by aghassemi** [comment]
1533168552513  is now in production
