### ISSUE TITLE
🚄 Release tracking issue for 1533253141109 (Canary)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17279]
# Release tracking issue

- [x] Release [1533253141109](https://github.com/ampproject/amphtml/releases/tag/1533253141109) is cut as a new canary release
- [x] Release 1533253141109 pushed to dev channel (9:00 AM, Aug 3, 2018 UTC-7)
- [x] Release 1533253141109 pushed to 1% (4:30 PM, Aug 3, 2018 UTC-7)
- [x] Release 1533253141109 pushed to production

**Comment by rsimha** [comment]
This is stale, and should've been closed.
