### ISSUE TITLE
🚄 Release tracking issue for 011533924452420 (Canary)

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#17351]
# Release tracking issue

- [x] Release [011533692711873](https://github.com/ampproject/amphtml/releases/tag/011533692711873) is cut as a new canary release
- [ ] Release 011533692711873 pushed to dev channel (12:00 AM, Aug 3, 2018 UTC-7)
- [ ] Release 011533692711873 pushed to 1% (12:00 AM, Aug 3, 2018 UTC-7)
- [ ] Release 011533692711873 pushed to production

Edit: Updated versions after cherry pick (#17375)

- [x] Release [011533924452420](https://github.com/ampproject/amphtml/releases/tag/011533692711873) is cut as a new canary release
- [x] Release 011533924452420 pushed to dev channel
- [x] Release 011533924452420 pushed to 1%
- [x] Release 011533924452420 pushed to production

**Comment by cathyxz** [comment]
@newmuis is this release number still correct? I believe this is now 1533924452420 after the cherry pick. Release linked at: https://github.com/ampproject/amphtml/releases.

**Comment by rsimha** [comment]
Version 1533924452420 is now pushed to prod.
