### ISSUE TITLE
🚄Release tracking issue for canary release 1534872626733 (Production)

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#17495]
# Release tracking issue

- [x] Release [1534278312424](https://github.com/ampproject/amphtml/releases/tag/1534278312424) is cut as a new canary release
- [x] Release 1534278312424 pushed to dev channel (5:36 PM, Aug 14, 2018 UTC-4)
- [x] Release [1534360330773](https://github.com/ampproject/amphtml/releases/tag/1534360330773) created with cherry picks.
- [x] Commit [1534360330773](https://github.com/ampproject/amphtml/releases/tag/1534360330773) cherry-picked to last week's production release 1533924452420.
- [x] Release 1534360330773 pushed to Dev Channel (4:58 PM, Aug 15, 2018 UTC-4)
- [x] Release 1534360330773 pushed to 1% (4:58 PM, Aug 15, 2018 UTC-4)
- [x] Release [1534445750553](https://github.com/ampproject/amphtml/releases/tag/1534360330773) created with cherry picks.
- [x] Release 1534445750553 pushed to Dev Channel (Aug 16, 2018 UTC-4)
- [x] Release 1534445750553 pushed to 1% (Aug 16, 2018 UTC-4)
- [x] Release [1534810430045](https://github.com/ampproject/amphtml/releases/tag/1534810430045) created with cherry picks.
- [x] Release 1534810430045 pushed to Dev Channel 
- [x] Release 1534810430045 pushed to 1% 
- [x] Release [1534872626733](https://github.com/ampproject/amphtml/releases/tag/1534872626733) created with cherry picks. (experiment config change only)
- [x] Release 1534872626733 pushed to 1%
- [x] Release 1534872626733 pushed to prod
- [x] Release [1535038987988](https://github.com/ampproject/amphtml/releases/tag/1535038987988) created with cherry picks. (See #17682)
- [x] Release 1535038987988 pushed to prod

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by aghassemi** [comment]
@rsimha I think this is missing `1534445750553` which looks like is the latest Canary candidate. Just making sure I am not missing something.

**Comment by rsimha** [comment]
@aghassemi you're right, there was a second cherry pick on Thursday that I may not have added to this tracking issue.

**Comment by aghassemi** [comment]
@rsimha Thanks for confirming, I will update the description with all details soon.

**Comment by aghassemi** [comment]
@danielrozenberg `1534810430045` is the latest Canary RC to promote tomorrow.
