### ISSUE TITLE
🚄 Release tracking issue for production release 1535039767807 / 1535566825959 (Canary)

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#17636]
# Release tracking issue

- [x] Release [1534879991178](https://github.com/ampproject/amphtml/releases/tag/1534879991178) is cut as a new canary release
- [x] Release 1534879991178 pushed to dev channel (Aug 21, 2018 23:02 UTC)
- [x] Release 1534879991178 pushed to 1% (Aug 22, 2018 18:20 UTC)
- [x] Release [1535039767807](https://github.com/ampproject/amphtml/releases/tag/1535039767807) created with cherry picks. (See #17682)
- [x] Release 1535039767807 pushed to dev channel (Aug 23, 2018 21:56 UTC)
- [x] Release 1535039767807 pushed to 1% (Aug 23, 2018 21:56 UTC)
- [x] Release 1535039767807 pushed to production (10:58 AM, Aug 28, 2018 UTC-7)
- [x] Rolled back 1535039767807 for P0 bug (6:22 PM, Aug 28, 2018 UTC-7)
- [x] Release [1535566825959](https://github.com/ampproject/amphtml/releases/tag/1535566825959) created with cherry picks.
- [x] Release 1535566825959 pushed to dev channel (1:42 PM, Aug 29, 2018 UTC-7)
- [x] Release 1535566825959 pushed to 1% (1:42 PM, Aug 29, 2018 UTC-7)
- [x] Release 1535566825959 pushed to production (2:51 PM, Aug 29, 2018 UTC-7)
- [x] Release 1536699515199 created with cherry picks and pushed to production (3:48 PM, Sept 11, 2018 UTC-7) 
- [x] Release 1536865149181 created with cherry picks and pushed to production (2:37 PM, Sept 13, 2018 UTC-7)

**Comment by prateekbh** [comment]
@danielrozenberg opt-in completed
