### ISSUE TITLE
Release tracking issue for canary release 1535579255907 (Canary/Production) 

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#17802]
# Release tracking issue

- [x] Release [1535579255907](https://github.com/ampproject/amphtml/releases/tag/1535579255907) is cut as a new canary release
- [x] Release 1535579255907 pushed to dev channel (7:59 AM, Aug 30, 2018 UTC-7)
- [x] Release 1535579255907 pushed to 1% (10:00 AM, Aug 30, 2018 UTC-7)
- [x] Release 1535579255907 pushed to production

**Comment by erwinmombay** [comment]
issues to be locked at:
https://github.com/ampproject/amphtml/issues/17837
https://github.com/ampproject/amphtml/issues/17838
https://github.com/ampproject/amphtml/issues/17839
https://github.com/ampproject/amphtml/issues/17840
