### ISSUE TITLE
Release Tracking Issue for 1809142227020 (production)

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#17970]
Tracking the cut on Tuesday Sept 11, 2018: 
- [x] Release [1809111831160](https://github.com/ampproject/amphtml/releases/tag/1809111831160) is cut as a new canary release (Sept 11, 2018)
- [x] Release [1809122303360](https://github.com/ampproject/amphtml/releases/tag/1809122303360) is cut after cherry-picking https://github.com/ampproject/amphtml/pull/18013 (Sept 11, 2018)
- [x] Release 1809141845540 is cut after cherry-picking https://github.com/ampproject/amphtml/issues/18040 https://github.com/ampproject/amphtml/issues/18025 (Sept 14, 2018). 
  - Cherry-picked #18024 for https://github.com/ampproject/amphtml/issues/18025 
  - Cherry-picked #18029 #18039 #18017 for https://github.com/ampproject/amphtml/issues/18040 
- [x] Release [1809141845540](https://github.com/ampproject/amphtml/releases/tag/1809141845540) is promoted to opt-in and 1% (Sept 14, 2018, 3:02 PM PST)
- [x] Release [1809142227020](https://github.com/ampproject/amphtml/releases/tag/1809142227020) is cut after cherry-picking https://github.com/ampproject/amphtml/issues/18037 (Sept 14, 2018). 
  - Cherry-picked https://github.com/ampproject/amphtml/pull/18035 for #18037. 
- [x] Release [1809142227020](https://github.com/ampproject/amphtml/releases/tag/1809142227020) is promoted to opt-in and 1%.

**Comment by adelinamart** [comment]
This version is now in production
