### ISSUE TITLE
🚄Release tracking issue for canary release <1809202142050> (Canary)

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#18159]
# Release tracking issue

- [x] Release `[1809181624140](https://github.com/ampproject/amphtml/releases/tag/<RELEASE_NUMBER>)` is cut as a new canary release
- [x] Release 1809181624140pushed to dev channel (<CL submit time>)
- [x] Release 1809181624140 pushed to 1% (<CL submit time>)
- [ ] Release 1809181624140 pushed to production (<CL submit time>)

If you perform cherry picks, add/update the checkboxes above as needed e.g.

- [x] Release `[1809202142050](18255)` created with cherry picks.
- [x] Release 1809202142050 pushed to Dev Channel

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by jarek-gilewski** [comment]
Is this already on production? AMP-list still keeps initial height - see example https://produktsuchmaschine.de/search.html?sq=red (go to page 2 and scroll down)

**Comment by calebcordry** [comment]
@jarek-gilewski This cut will never be in production. You can follow the current release at #18374
