### ISSUE TITLE
🚄Release tracking issue for canary release 1809251804390 (Canary)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#18374]
# Release tracking issue

NOTE: This is week of AMP Contributor Summit. Due to this, we will not be pushing last weeks canary to production. We will be cutting and releasing a new canary.

- [x] Release [1809251804390](https://github.com/ampproject/amphtml/releases/tag/1809251804390) is cut as a new canary release
- [x] Release 1809251804390 pushed to dev channel (Tuesday)
- [x] Release 1809251804390 pushed to 1% (Wednesday)
~~- [ ] Release 1809251804390 pushed to production (<CL submit time>)~~

Release 1809251804390 will not be promoted. New canary cut with cherry picks #18422 & #18405 

- [x] Release [1809271909310](https://github.com/ampproject/amphtml/releases/tag/1809271909310
) is cut as a new canary release
- [x] Release 1809271909310 pushed to dev channel (Friday)
- [x] Release 1809271909310 pushed to 1% (Friday)
- [x] Release 1810021759000 pushed to production (Tuesday) (Added by nainar)
Note: (Added by nainar) 1809271909310 had a cherry pick - due to which the version number changed.
