### ISSUE TITLE
🚄Release tracking issue for canary release 1810052256480 (Production)

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#18518]
# Release tracking issue

- [x] Release [1810022028350-old](https://github.com/ampproject/amphtml/releases/tag/1810022028350) is cut as a new canary release
- [x] Release 1810022028350-old pushed to dev channel (Tuesday - 2 Oct 2018 at 4:54 pm PT)
- [x] Release 1810022028350-old pushed to 1% (Wednesday - 3 Oct 2018 at 10:56 am)
- [x] Release 1810052256480 pushed to 1%
- [x] Release [1810052256480](https://github.com/ampproject/amphtml/releases/tag/1810052256480) pushed to production (<Tuesday - 9 Oct 2018 at 4:41pm PT>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
