### ISSUE TITLE
🚄Release tracking issue for canary release 1810152207300 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#18649]
# Release tracking issue

- [x] Release [1810091721120-old](https://github.com/ampproject/amphtml/releases/tag/1810091721120) is cut as a new canary release
- [x] Release <1810091721120-old> pushed to dev channel (10/9/2018 4pm pt)
- [x] Release [1810110036230](https://github.com/ampproject/amphtml/releases/tag/1810110036230) created with cherry picks.
- [x] Release < 1810110036230 > pushed to Dev Channel
- [x] Release < 1810110036230 > pushed to 1% (10/11/2018 9:35am pt)
- [ ] Release <1810091721120> pushed to production (<CL submit time>)
- [x] Release <1810152207300> with cherry picks to Dev Channel
  - Turn on linker-form experiment (#18752)
- [x] Release <1810152207300> to 1%
- [x] Release <1810152207300> to production 4:30 PM, Oct 16, 2018 UTC-7

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
