### ISSUE TITLE
🚄 Release tracking issue for canary release 1810241929000 → 1810270052190 → 1810301740350 → 1811051833450 → 1811091510240

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#18971]
# Release tracking issue

- [x] Release [1810241929000](https://github.com/ampproject/amphtml/releases/tag/1810241929000) is cut as a new canary release
- [x] Release 1810241929000 pushed to dev channel (4:03 PM, Oct 25, 2018 UTC-4)
- [x] Release 1810241929000 pushed to 1% (4:43 PM, Oct 25, 2018 UTC-4)
- [x] Release [1810301740350](https://github.com/ampproject/amphtml/releases/tag/1810301740350) pushed to production (11:35 AM, Oct 30, 2018 UTC-7)
- [x] Cherry pick request - generated new version [1810270052190](https://github.com/ampproject/amphtml/releases/tag/1810270052190) is cut as a new canary release
  - Proactively refresh overflow to avoid rendering bugs on iOS (#19007)
  - Update experiment for scroll-height-bounce to be "on" in canary and "off" in prod (#19008)
  - Implement Linkers for Segment (#18878) (3 days ago) 
- [x] Release 1810270052190 pushed to 1%  and optin (7:51 PM, Oct 26, 2018 UTC-7)
- [x] Cherry pick "Launch scroll-height-bounce on PROD (#19013)" to 1810270052190 -> Generated new version 1810301740350
- [x] Cherry pick "Fix p0 caused by hidden-mutation-observer experiment" (#19141) into prod (10:11 PM, Nov 6, 2018 UTC-5) -> generasted new version 1811051833450
- [x] Release pushed to prod (8:32 PM, Nov 5, 2018 UTC-5)
- [x] Cherry pick Fix HTML_ATTR #19185 -> generated new version  1811091510240 
- [x] Release [`1811091510240`](https://github.com/ampproject/amphtml/releases/tag/1811091510240) created with cherry picks (1:44 PM, Nov 9, 2018 UTC-5)
- [ ] Cherry pick release pushed to optin (<time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by lannka** [comment]
Is this all done? Should be closed?
