### ISSUE TITLE
🚄Release tracking issue for canary release 1811061842310 → 1811072108000 → 1811081843340 → 1811091519050 (Canary)

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#19166]
# Release tracking issue

- [x] Release [`1811061842310`](https://github.com/ampproject/amphtml/releases/tag/001811061842310) is cut as a new canary release
- [x] Release 1811061842310 pushed to dev channel (<CL submit time>)
- [x] Cherry pick "Don't encode `ExpandStringAsync`" (#19161)
- [x] Release [`1811072108000`](https://github.com/ampproject/amphtml/releases/tag/1811072108000) created with cherry picks to dev channel
- [x] Cherry pick "Reset the UI once any action completes: delegated or non-delegated" #19178 (#19180)
- [x] Release [`1811081843340`](https://github.com/ampproject/amphtml/releases/tag/1811081843340) created with cherry picks (3:02 PM, Nov 8, 2018 UTC-5)
- [x] Cherry pick release pushed to optin (3:53 PM, Nov 8, 2018 UTC-5)
- [x] Cherry pick Fix HTML_ATTR #19185 
- [x] Release [`1811091519050`](https://github.com/ampproject/amphtml/releases/tag/1811091519050) created with cherry picks (2:40 PM, Nov 9, 2018 UTC-5)
- [x] release 1811091519050 pushed to optin (<time>)
- [x] Release 1811091519050 pushed to 1% (<CL submit time>)
- [x] Release 1811091519050 pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by aghassemi** [comment]
1811091519050 was just promoted to production.
