### ISSUE TITLE
🚄Release tracking issue for release 1811132019350 (Canary)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#19302]
- [x] Release [1811132019350](https://github.com/ampproject/amphtml/releases/tag/1811132019350) is cut as a new canary release
- [x] Release [1811132019350](https://github.com/ampproject/amphtml/releases/tag/1811132019350)  pushed to dev channel 
- [x] Release [1811132019350](https://github.com/ampproject/amphtml/releases/tag/1811132019350)  pushed to 1%
- [ ] Release [1811132019350](https://github.com/ampproject/amphtml/releases/tag/1811132019350) pushed to production

**Comment by newmuis** [comment]
This release went to production as [1811202351440](https://github.com/ampproject/amphtml/releases/tag/1811202351440) due to the cherrypick from #19385.
