### ISSUE TITLE
amp-ima-video: Follow up Tracking Issue for New Features

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#19393]
relates to #18954

* [x] show controls on hover (New Feature PR)
* [x] document the new `adLabel` in [reference docs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ima-video/amp-ima-video.md), as well as state the default
* [x] Update AMP By Example

@curseagain feel free to take on as many of these as you would like, and feel free to reach out for help on any of them. Or if you can no longer take them on, let me know and I can pick them up 😄

**Comment by honeybadgerdontcare** [comment]
@curseagain 	The validator allows any attributes that begin with `data-`.

**Comment by torch2424** [comment]
Closing this as everything has been merged in! 🎉 😄
