### ISSUE TITLE
🚄Release tracking issue for release 1811202257200 (Canary)

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#19476]
- [x] Release [1811202257200](https://github.com/ampproject/amphtml/releases/tag/1811202257200) is cut as a new canary release
- [x] Release [1811202257200](https://github.com/ampproject/amphtml/releases/tag/1811202257200)  pushed to dev channel 
- [x] Release [1811202257200](https://github.com/ampproject/amphtml/releases/tag/1811202257200)  pushed to 1%
- [x] Release [1811202257200](https://github.com/ampproject/amphtml/releases/tag/1811202257200) pushed to production

**Comment by lannka** [comment]
Pushed to prod.
