### ISSUE TITLE
🚄Release tracking issue for canary release 1811272154520 (Canary)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#19484]
# Release tracking issue

- [x] Release [1811272154520](https://github.com/ampproject/amphtml/releases/tag/1811272154520) is cut as a new canary release
- [x] Release [1811272154520](https://github.com/ampproject/amphtml/releases/tag/1811272154520) pushed to dev channel (6:36 PM, Nov 27, 2018 UTC-8)
- [x] Release [1811272154520](https://github.com/ampproject/amphtml/releases/tag/1811272154520) pushed to 1% (11:03 AM, Nov 28, 2018 UTC-8)
- [x] Release [1811272154520](https://github.com/ampproject/amphtml/releases/tag/1811272154520) pushed to production (5:45 PM, Dec 4, 2018 UTC-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
