### ISSUE TITLE
🚄Release tracking issue for canary release 1812051624460 (Canary)

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#19659]
# Release tracking issue

- [x] Release [1812051624460](https://github.com/ampproject/amphtml/releases/tag/1812051624460) is cut as a new canary release (with cherry-pick from #19656)
- [x] Release 1812051624460 pushed to dev channel (4:20 PM, Dec 5, 2018 UTC-5)
- [x] Release [1812061946500](https://github.com/ampproject/amphtml/releases/tag/1812061946500) created with cherry-pick from #19693.
- [x] Release 1812061946500 pushed to 1% (6:17 PM, Dec 6, 2018 UTC-5)
- [x] Release [1812102014220](https://github.com/ampproject/amphtml/releases/tag/1812102014220) created with cherry picks.
- [x] Release 1812102014220 pushed to Dev Channel (12:10 PM, Dec 11, 2018 UTC-5)
- [x] Release 1812102014220 pushed to Production (4:42 PM, Dec 11, 2018 UTC-5)
- [x] Release [1812121929200](https://github.com/ampproject/amphtml/releases/tag/1812121929200) created with cherry picks
- [x] Release 1812121929200 pushed to Production (4:51 PM, Dec 12, 2018 UTC-5)
- [x] Release [1812131718380](https://github.com/ampproject/amphtml/releases/tag/1812131718380) created with cherry picks
- [x] Release 1812131718380 pushed to Production (1:49 PM, Dec 13, 2018 UTC-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
