### ISSUE TITLE
🚄 Release tracking issue for canary release 1812121952400 (Canary)

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#19847]
# Release tracking issue

- [x] Release [1812121952400](https://github.com/ampproject/amphtml/releases/tag/1812121952400) is cut as a new canary release
- [ ] Release <RELEASE_NUMBER> pushed to dev channel (<CL submit time>)
- [ ] Release <RELEASE_NUMBER> pushed to 1% (<CL submit time>)
- [ ] Release <RELEASE_NUMBER> pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by rsimha** [comment]
Assigning to @danielrozenberg, next week's release on-duty.

Since we don't have a scheduled release next week, this issue can be closed without pushing 1812121952400 to prod.

We do have a canary cut though, for which a new release issue must be created.
