### ISSUE TITLE
🚄Release tracking issue for canary release 1812181822170 (Canary)

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#19960]
# Release tracking issue

- [ ] Release [1812181822170](https://github.com/ampproject/amphtml/releases/tag/1812181822170) is cut as a new canary release
- [ ] Release 1812181822170 pushed to dev channel (<CL submit time>)
- [ ] Release 1812181822170 pushed to 1% (<CL submit time>)
- [ ] Release 1812181822170 pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by lannka** [comment]
Question: are we going to push this canary to prod after release freeze? Or do we just abandon this and cut a new one?

This canary has an issue: #19963
