### ISSUE TITLE
Release tracking issue for canary release 001812261943070 (Canary)

### ISSUE THREAD

**Issue by prateekbh** [ampproject/amphtml#20082]
# Release tracking issue

- [x] Release [001812261943070](https://github.com/ampproject/amphtml/releases/tag/1812181822170) is cut as a new canary release
- [x] Release 001812261943070 pushed to dev channel 
- [x] Release 001812261943070 pushed to 1% 
- ~~Release 001812261943070 pushed to production~~ _(no production release this week!)_

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by cathyxz** [comment]
@calebcordry can this issue be safely closed?

**Comment by calebcordry** [comment]
Yep. Thanks for cleaning up 🙂
