### ISSUE TITLE
🚄Release tracking issue for canary release 1901021931380 (Canary)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#20146]
# Release tracking issue

- [x] Release `[1901021931380](https://github.com/ampproject/amphtml/releases/tag/1901021931380)` is cut as a new canary release
- [x] Release 1901021931380 pushed to dev channel (3:56 PM, Jan 4, 2019 UTC-8)
- [x] Release 1901021931380 pushed to 1% (3:56 PM, Jan 4, 2019 UTC-8)
- [x] Release 1901021931380 pushed to production (5:06 PM, Jan 8, 2019 UTC-8)
