### ISSUE TITLE
🚄Release tracking issue for canary release 1901081935550 (Production)

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#20196]
# Release tracking issue

- [x] Release [`1901081935550`](https://github.com/ampproject/amphtml/releases/tag/1901081935550) is cut as a new canary release
- [x] Release [`1901081935550`](https://github.com/ampproject/amphtml/releases/tag/1901081935550) pushed to dev channel (5:08 PM, Jan 8, 2019 UTC-8)
- [x] Release  [`1901081935550`](https://github.com/ampproject/amphtml/releases/tag/1901081935550) pushed to 1% (12:53 PM, Jan 10, 2019 UTC-8)
- [x] Release  [`1901081935550`](https://github.com/ampproject/amphtml/releases/tag/1901081935550) pushed to production (<CL submit time>)
