### ISSUE TITLE
🚄Release tracking issue for canary release 1901181700510

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#20361]
# Release tracking issue

- [x] Release [1901151846530](https://github.com/ampproject/amphtml/releases/tag/1901151846530) is cut as a new canary release
- [x] Release 1901151846530 pushed to dev channel
- [x] Release 1901151846530 pushed to 1%
- [x] Release [1901181700510](...) created with cherry picks.
- [x] Release 1901181700510 pushed to Dev Channel
- [x] Release 1901181700510 pushed to 1% 
- [x] Release 1901181700510 pushed to production (4:58 PM, Jan 22, 2019 UTC-5)
- [x] Release 1901181700510 rolled back due to #20474 (11:11 PM, Jan 22, 2019 UTC-5)
- [x] Cherry-pick #20407 into 1901181700510 as 1901231933480
- [x] Release (1901231933480) pushed to production (5:42 PM, Jan 23, 2019 UTC-5)
- [x] Release 1901231933480 rolled back due to #20474 (10:15 PM, Jan 23, 2019 UTC-5)
- [x] Cherry-pick #20501 into 1901231933480 as [1901241837330](https://github.com/ampproject/amphtml/releases/tag/1901241837330)
- [x] Release 1901241837330 pushed to production (4:07 PM, Jan 24, 2019 UTC-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new).  If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
