### ISSUE TITLE
🚄Release tracking issue for canary release 1901222107370 (Production)

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20470]
# Release tracking issue

- [x] Release [1901222107370](https://github.com/ampproject/amphtml/releases/tag/1901222107370) is cut as a new canary release
- [x] Release 1901222107370 pushed to dev channel (8:33 PM, Jan 22, 2019 UTC-5)
- [x] Release [1901232142340](https://github.com/ampproject/amphtml/releases/tag/1901232142340) created with cherry picks.
- [x] Release 1901232142340 pushed to Dev Channel (7:11 PM, Jan 23, 2019 UTC-5)
- [x] Release 1901232142340 pushed to 1% (7:11 PM, Jan 23, 2019 UTC-5)
- [x] Release [1901242049580](https://github.com/ampproject/amphtml/releases/tag/1901242049580) created with cherry picks (#20506 and #20501).
- [x] Release 1901242049580 pushed to Dev Channel (6:37 PM, Jan 24, 2019 UTC-5)
- [x] Release 1901242049580 pushed to 1% (6:37 PM, Jan 24, 2019 UTC-5)
- [x] Release 1901242049580 pushed to production (4:14 PM, Jan 29, 2019 UTC-5)
- [x] Release 1901242049580 was rolled back due to #20594 (10:48 PM, Jan 29, 2019 UTC-5)
- [x] Release [1901302225410](https://github.com/ampproject/amphtml/releases/tag/1901302225410) created with cherry picks. (8:26 PM, Jan 30, 2019 UTC-5)
- [x] Release 1901302225410 pushed to Dev Channel (12:42 PM, Jan 31, 2019 UTC-5)
- [x] Release 1901302225410 pushed to 1%. (5:16 PM, Jan 31, 2019 UTC-5)
- [x] Release 1901302225410 pushed to production.  (1:11 PM, Feb 1, 2019 UTC-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by aghassemi** [comment]
1901242049580 is rolled back due to https://github.com/ampproject/amphtml/issues/20594
