### ISSUE TITLE
🚄Release tracking issue for canary release 1901312147090 (Canary)

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#20587]
# Release tracking issue

- [x] Release [1901312147090](https://github.com/ampproject/amphtml/releases/tag/1901312147090) is cut as a new canary release.
- [x] Release 1901312147090 pushed to dev channel (3:08 PM, Feb 1, 2019 UTC-5).
- [x] Release 1901312147090 promoted to 1% (5:02 PM, Feb 1, 2019 UTC-5).
- [ ] Release 1901312147090 pushed to production ().

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by kristoferbaxter** [comment]
1. Cherry Picks Complete.
2. Build Successful (https://travis-ci.org/ampproject/amphtml/builds/489674953)
