### ISSUE TITLE
🚄Release tracking issue for canary release 1902132037100 (Production)

### ISSUE THREAD

**Issue by Marcial1234** [ampproject/amphtml#20875]
# Release tracking issue

- [x] Release [1902132037100](https://github.com/ampproject/amphtml/releases/tag/1902132037100) is cut as a new canary release
- [x] Release 1902132037100 pushed to dev channel (3:08 PM, Feb 14, 2019 UTC-5)
- [x] Release 1902132037100 pushed to 1% (3:58 PM, Feb 14, 2019 UTC-5)
- [x] Release [1902151859190](https://github.com/ampproject/amphtml/releases/tag/1902151859190) created with cherry picks
- [x] Release 1902151859190 pushed to 1% (5:57 PM, Feb 15, 2019 UTC-5)
- [x] Release 1902151859190 pushed to Dev Channel (6:16 PM, Feb 15, 2019 UTC-5)
- [x] Release 1902151859190 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by jpettitt** [comment]
cc @jpettitt
