### ISSUE TITLE
🚄Release tracking issue for canary release 1902271810270 (Production)

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#20973]
# Release tracking issue

- [x] Release [1902191749350](https://github.com/ampproject/amphtml/releases/tag/1902191749350) is cut as a new canary release
- [x] Release 1902191749350 pushed to dev channel
- [x] Release 1902191749350 pushed to 1%
- [x] Release 1902191749350 pushed to production
- [x] Release [1902271810270](https://github.com/ampproject/amphtml/releases/tag/1902271810270) created with cherrypicks #21026(Cherrypick tracking issue #21147)
- [x] Release 1902271810270 pushed to dev channel and 1%
- [x] Release 1902271810270 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by zhouyx** [comment]
1902191749350 in prod

**Comment by choumx** [comment]
Rolled back due to #21144 and #20979 (same issue).

**Comment by zhouyx** [comment]
1902271810270 with the fix is in prod.
