### ISSUE TITLE
🚄Release tracking issue for canary release 1902261915030 (Canary)

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#21169]
# Release tracking issue

- [x] Release [1902261915030](https://github.com/ampproject/amphtml/releases/tag/1902261915030) is cut as a new canary release
- [x] Release 1902261915030 pushed to dev channel
- [x] Release 1902261915030 pushed to 1%
~~- [ ] Release 1902261915030 pushed to production~~
- [x] Patched 1902261915030 to 1903070012530
  - 🚮🖍🚀 Remove amp-story backgrounds (#21289)
  - Fix call on undefined property forEach (#21232)
- [x] Release 1903070012530 pushed to dev channel
- [x] Release 1903070012530 pushed to 1%
- [x] Release 1903070012530 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
