### ISSUE TITLE
🚄Release tracking issue for canary release 1903141753530 (production)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#21329]
# Release tracking issue

- [x] Release [1903080058260](https://github.com/ampproject/amphtml/releases/tag/1903080058260) is cut as a new canary release
- [X] Release 1903080058260 pushed to dev channel
- [X] Release 1903080058260 pushed to 1%
- [X] Release [1903122236150](https://github.com/ampproject/amphtml/releases/tag/1903122236150) from [#21386 cherry pick](https://github.com/ampproject/amphtml/issues/21386)
- [X] Release [1903141753530](https://github.com/ampproject/amphtml/releases/tag/1903141753530)
- [X] Release 1903141753530 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by jridgewell** [comment]
Now live in production.
