### ISSUE TITLE
🚄Release tracking issue for canary release 1903122229510 (Canary)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#21422]
# Release tracking issue

- [x] Release [1903122229510](https://github.com/ampproject/amphtml/releases/tag/1903122229510) is cut as a new canary release
- [x] Release 1903122229510 pushed to dev channel (5:52 PM, Mar 14, 2019 UTC-4)
- [x] Release 1903122229510 pushed to 1% (`<CL submit time>`)
- [x] Release 1903122229510 pushed to production (`<CL submit time>`)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
