### ISSUE TITLE
🚄 Release tracking issue for canary release 1903191703470

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#21482]
# Release tracking issue

- [x] Release [1903191703470](https://github.com/ampproject/amphtml/releases/tag/1903191703470) is cut as a new canary release
- [x] Release 1903191703470 pushed to dev channel (6:45 PM, Mar 19, 2019 UTC-7)
- [x] Release 1903191703470 pushed to 1% (1:56 PM, Mar 20, 2019 UTC-7)
- [x] Release 1903191703470 pushed to production (`<CL submit time>`)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
