### ISSUE TITLE
🚄Release tracking issue for release 1903281741200 (Canary)

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#21609]
# Release tracking issue

- [x] Release [1903262017080](https://github.com/ampproject/amphtml/releases/tag/1903262017080) is cut as a new canary release
- [x] Release 1903262017080 pushed to dev channel (2:09 PM, Mar 27, 2019 UTC-4)
- [x] Release [1903281741200](https://github.com/ampproject/amphtml/releases/tag/1903281741200) created with cherry picks #21622 (2:45 PM, Mar 28, 2019 UTC-4)
- [X] Release 1903281741200 pushed to dev channel (4:15 PM, Mar 28, 2019 UTC-4)
- [X] Release 1903281741200 pushed to 1% (4:44 PM, Mar 28, 2019 UTC-4)
- [x] Release 1903281741200 pushed to production (10:30 AM, April 2, 2019 UTC-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by aghassemi** [comment]
This is now in production.
