### ISSUE TITLE
🚄 Release tracking issue for release 1904021746450

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21688]
# Release tracking issue

- [x] Release [1904021746450](https://github.com/ampproject/amphtml/releases/tag/1904021746450) is cut as a new canary release
- [x] Release 1904021746450 pushed to dev channel (7:00 PM, April 2, 2019 UTC-7)
- [x] Release 1904021746450 pushed to 1% (2:30 PM, April 3, 2019 UTC-7)
- [x] Release 1904021746450 pushed to production (6:02 PM, Apr 9, 2019 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
