### ISSUE TITLE
🚄 Release tracking issue for release 1904091426070

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#21788]
# Release tracking issue

- [x] Release [1904091426070](https://github.com/ampproject/amphtml/releases/tag/1904091426070) is cut as a new canary release
- [x] Release 1904091426070 pushed to dev channel (6:56 PM, Apr 9, 2019 UTC-4)
- [x] Release 1904091426070 pushed to 1% (4:56 PM, Apr 10, 2019 UTC-4)
- [x] Release 1904091426070 pushed to production (6:50 PM, Apr 15, 2019 UTC-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
