### ISSUE TITLE
🚄 Release tracking issue for release 1904200955460

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21881]
- [x] Release [1904170517570](https://github.com/ampproject/amphtml/releases/tag/1904170517570) is cut as a new canary release
- [x] Release 1904170517570 pushed to dev channel (12:19 AM, Apr 17, 2019 UTC-7)
- [x] Release 1904170517570 pushed to 1% (6:29 PM, Apr 17, 2019 UTC-7)
- [x] Release 1904170517570 push to 1% was **reverted** due to #21915 (10:00 PM, Apr 19, 2019 UTC-7)
- [x] Release [1904200955460](https://github.com/ampproject/amphtml/releases/tag/1904200955460) is cut as a new canary release
- [x] Release 1904200955460 pushed to dev channel (3:55 PM, Apr 20, 2019 UTC-7)
- [x] Release 1904200955460 pushed to 1% (3:55 PM, Apr 20, 2019 UTC-7)
- [x] Release 1904200955460 pushed to production

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by aghassemi** [comment]
1904170517570 push to 1% was reverted due to #21915. 

_1% is now same as prod until a fix is merged_

**Comment by aghassemi** [comment]
New Canary was cut with the fix included, new Canary RTV is 1904200955460

**Comment by lannka** [comment]
Promoted to prod at 9:55 AM, Apr 24, 2019 UTC-7
