### ISSUE TITLE
Release tracking issue for release 1904240947200

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#21958]
- [x]  Release [1904240947200](https://github.com/ampproject/amphtml/releases/tag/1904240947200) is cut as a new canary release
- [x]  Release 1904240947200 pushed to dev channel (9:51 AM, Apr 25, 2019 UTC-7)
- [x]  Release 1904240947200 pushed to 1% (10:23 AM, Apr 25, 2019 UTC-7)
- [x] Cherry pick [1904262212040](https://github.com/ampproject/amphtml/releases/tag/1904262212040) to opt-in and 1% (7:07 PM, Apr 26, 2019 UTC-7)
- [x]  Release 1904262212040 pushed to production
- [x] Release [1905021827420](https://github.com/ampproject/amphtml/tag/1905021827420) created with cherry picks.
- [x] Release 1905021827420 pushed to Production

**Comment by rsimha** [comment]
Reopening due to cherry-pick request #22113
