### ISSUE TITLE
🚄 Release tracking issue for release 1904301721170

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22117]
# Release tracking issue

- [x] Release [1904301721170](https://github.com/ampproject/amphtml/releases/tag/1904301721170) is cut as a new canary release
- [x] Release 1904301721170 pushed to dev channel (12:26 PM, May 1, 2019 UTC-4)
- [x] Release 1904301721170 pushed to 1% (6:35 PM, May 1, 2019 UTC-4)
- [x] Release 1904301721170 pushed to production (1:55 PM, May 7, 2019 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
