### ISSUE TITLE
🚄Release tracking issue for release 1905071607430

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#22180]
# Release tracking issue

- [x] Release [1905071607430](https://github.com/ampproject/amphtml/releases/tag/1905071607430) is cut as a new canary release
- [x] Release 1905071607430 pushed to dev channel (5:19 PM, May 7, 2019 UTC-4)
- [x] Release 1905071607430 pushed to 1% (4:03 PM, May 8, 2019 UTC-4)
- [x] Release [1905091827220](https://github.com/ampproject/amphtml/releases/tag/1905091827220) is cut as a new canary release via cherry picking #22218 (cherry-pick request: #22219)
- [x] Release 1905091827220 pushed to dev channel (4:03 PM, May 9, 2019 UTC-4)
- [x] Release 1905091827220 pushed to 1% (4:30 PM, May 9, 2019 UTC-4)
- [x] Release 1905091827220 pushed to production (2:13 PM, May 14, 2019 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by mdmower** [comment]
I let @calebcordry know about a bug in #22137 (see comments there). Please make sure it is either fixed or reverted before 1905071607430 is pushed to production.

**Comment by calebcordry** [comment]
Filed issue #22217. Cherry pick request to add revert coming shortly.
