### ISSUE TITLE
🚄 Release tracking issue for release 1905140117570

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#22292]
# Release tracking issue

- [x] Release [1905140117570](https://github.com/ampproject/amphtml/releases/tag/1905140117570) is cut as a new canary release
- [x] Release 1905140117570 pushed to dev channel (7:05 PM, May 14, 2019 UTC-4)
- [x] Release 1905140117570 pushed to 1% (3:22PM, May 15, 2019 UTC-4)
- [x] Release 1905140117570 pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
