### ISSUE TITLE
🚄 Release tracking issue for release 1905211840370

### ISSUE THREAD

**Issue by prateekbh** [ampproject/amphtml#22426]
# Release tracking issue

- [x] Release [1905211840370](https://github.com/ampproject/amphtml/releases/tag/1905211840370) is cut as a new canary release
- [x] Release 1905211840370 pushed to dev channel ( 1:33 PM, May 22, 2019 UTC-4)
- [x] Cherry-picked 1905222334000 to canary (06:30 PM, May 22, 2019 UTC-4)
- [x] Cherry-picked 1905222334000 to dev channel ( 1:33 PM, May 22, 2019 UTC-4)
- [x] Release 1905222334000 pushed to 1% (11:09 AM, May 23, 2019 UTC-4)
- [x] Release 1905222334000 pushed to production (5:22 PM, May 28, 2019 UTC-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by calebcordry** [comment]
- [ ] Release `[<CHERRY_PICK_RELEASE_NUMBER>](...)` created with cherry picks.
