### ISSUE TITLE
🚄Release tracking issue for canary release 1905292322390 (Production)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#22547]
- [x] Release [1905282314280](https://github.com/ampproject/amphtml/releases/tag/1905282314280) is cut as a new canary release
---
- [x] Release [1905292322390](https://github.com/ampproject/amphtml/releases/tag/1905292322390) is re-cut as a new canary release due to p0
- [x] Release 1905292322390 pushed to dev channel (10:39 AM, May 30, 2019 UTC-7)
- [x] Release 1905292322390 pushed to 1% (10:22 AM, May 30, 2019 UTC-7)
- [x] Release 1905292322390 pushed to production (3:28 PM, Jun 4, 2019 UTC-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
