### ISSUE TITLE
🚄Release tracking issue for canary release 1906051812580  (Canary)

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#22686]
# Release tracking issue

- [x] Release [1906042041510](https://github.com/ampproject/amphtml/releases/tag/1906042041510) is cut as a new canary release (Travis build fails)
- [x] Release [1906051812580](https://github.com/ampproject/amphtml/releases/tag/1906051812580) is cut as a new canary release (Travis build succeeded)
- [x] Release 1906051812580 pushed to dev channel (1:17 PM, Jun 6, 2019 UTC-4)
- [x] Release 1906051812580 pushed to 1% (1:17 PM, Jun 6, 2019 UTC-4)
- [x] Release 1906051812580 pushed to production (12:58 PM, Jun 11, 2019 UTC-4)
- [x] Release [1906131851520](https://github.com/ampproject/amphtml/releases/tag/1906131851520) created with cherry picks.
- [x] Release [1906141418310](https://github.com/ampproject/amphtml/releases/tag/1906141418310) created with cherry picks. (1:18 PM, Jun 14, 2019 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
