### ISSUE TITLE
🚄Release tracking issue for canary release 1906111828200 (Production)

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#22792]
# Release tracking issue

- [x] Release [1906111828200](https://github.com/ampproject/amphtml/releases/tag/1906111828200) is cut as a new canary release
- [x] Release 1906111828200 pushed to dev channel (3:00 PM, Jun 12, 2019 UTC-4)
- [x] Release 1906111828200 pushed to 1% (3:52 PM, Jun 12, 2019 UTC-4)
- [x] Release 1906111828200 pushed to production (3:55 PM, Jun 19, 2019 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by Enriqe** [comment]
The push of 1906111828200 was delayed due to internal issues with the release. It is now ready to test in the dev channel.
