### ISSUE TITLE
🚄 Release tracking issue for release 1906191709480

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#22937]
# Release tracking issue

- [x] Release [1906191709480](https://github.com/ampproject/amphtml/releases/tag/1906191709480) is cut as a new canary release
- [x] Release `1906191709480` pushed to dev channel (4:33 PM, Jun 19, UTC-4)
- [x] Release `1906191709480` pushed to 1% (4:33 PM, Jun 19, UTC-4)
- [x] Release `1906191709480` pushed to production (12:21 PM, Jun 25, 2019 UTC-7)

**Comment by sparhami** [comment]
I initially created a cherry pick into the release candidate, but realized the issue only affects canary. Will wait for the normal canary promotiony to fix canary, since that is tomorrow anyway. The cherry-pick is not needed with the production flags.

**Comment by Enriqe** [comment]
@sparhami do we have release tracking issue for this week's release? I don't see it when filtering "Type: Release" labels.

**Comment by sparhami** [comment]
@Enriqe I'll create it once the release is actually cut and I have the version number. I'm trying the new process, but having some trouble with it, so I might just go back to the old way this afternoon.

**Comment by Enriqe** [comment]
Sounds good, just wanted to check what the current status is with the new release. Thanks!
