### ISSUE TITLE
🚄 Release tracking issue for release 1906242222460

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#23047]
# Release tracking issue

- [x] Release [1906242222460](https://github.com/ampproject/amphtml/releases/tag/1906242222460) is cut as a new canary release
- [x] Release 1906242222460 pushed to dev channel (10:27 AM, Jun 27, 2019 UTC-7)
- [x] Release 1906242222460 pushed to 1% (1:33 PM, Jun 27, 2019 UTC-7)
- [x] Release [1906272257090](https://github.com/ampproject/amphtml/releases/tag/1906272257090) created with cherry picks: #23072, #23083
- [x] Release 1906272257090 pushed to Dev Channel (11:25 AM, Jun 28, 2019 UTC-7)
- [x] Release 1906272257090 pushed to 1% (12:56 PM, Jun 28, 2019 UTC-7)
- [x] Release [1906282133370](https://github.com/ampproject/amphtml/releases/tag/1906272257090) created with cherry picks: #23072, #23083, #23104
- [x] Release 1906282133370 pushed to Dev Channel (3:56 PM, Jun 28, 2019 UTC-7)
- [x] Release [1907022322580](https://github.com/ampproject/amphtml/releases/tag/1907022322580) created with cherry picks: #23161 
- [x] Release 1907022322580 pushed to Dev Channel (11:09 AM, Jul 3, 2019 UTC-7)
- [x] Release 1907022322580 pushed to 1%
- [x] Release 1907022322580 pushed to Prod

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by sparhami** [comment]
Quick update, due to potential issues with the current canary, the 1% has been restored to `1906282130140`, the current production.

**Comment by cramforce** [comment]
Are we shipping in 4th of July week?

**Comment by zhouyx** [comment]
We are not cutting new canary or promoting prod this week.

**Comment by erwinmombay** [comment]
1907022322580 is now in prod
