### ISSUE TITLE
🚄Release tracking issue for production release 1907091704050

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#23271]
# Release tracking issue

- [x] Release [1907091704050](https://github.com/ampproject/amphtml/releases/tag/1907091704050) is cut as a new canary release
- [x] Release 1907091704050 pushed to dev channel (<CL submit time>)
- [x] Release 1907091704050 pushed to 1% (<CL submit time>)
- [x] Release [1907152257550](https://github.com/ampproject/amphtml/releases/tag/1907152257550) created with cherry picks.
- [x] Release 1907152257550 pushed to Dev Channel
- [x] Release 1907152257550 pushed to 1% (<CL submit time>)
- [x] Release 1907152257550 pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by alanorozco** [comment]
(Reopening since [1907161745080](https://github.com/ampproject/amphtml/issues/23372) is not prod yet.)

**Comment by alanorozco** [comment]
(In prod now.)
