### ISSUE TITLE
🚄 Release tracking issue for production release 1907161745080

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#23372]
# Release tracking issue

- [x] Release [1907161745080](https://github.com/ampproject/amphtml/releases/tag/1907161745080) is cut as a new canary release
- [x] Release 1907161745080 pushed to dev channel (4:31 PM, Jul 17, 2019 UTC-4)
- [x] Release 1907161745080 pushed to 1% (7:11 PM, Jul 17, 2019 UTC-4)
- [x] Release 1907161745080 pushed to production (3:02 PM, Jul 23, 2019 UTC-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
