### ISSUE TITLE
🚄 Release tracking issue for release <RELEASE_NUMBER>

### ISSUE THREAD

**Issue by Karolyna84** [ampproject/amphtml#23561]
# Release tracking issue

- [x] Release `[<RELEASE_NUMBER>](https://github.com/ampproject/amphtml/releases/tag/<RELEASE_NUMBER>)` is cut as a new canary release
- [x] Release <RELEASE_NUMBER> pushed to dev channel (<CL submit time>)
- [x] Release <RELEASE_NUMBER> pushed to 1% (<CL submit time>)
- [x] Release <RELEASE_NUMBER> pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
