### ISSUE TITLE
🚄 Release tracking issue for release 1907301630320

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#23597]
# Release tracking issue

- [x] Release [1907301630320](https://github.com/ampproject/amphtml/releases/tag/1907301630320) is cut as a new canary release
- [x] Release 1907301630320 pushed to dev channel (9:02 PM, Jul 30, 2019 UTC-4)
- [x] Release 1907301630320 pushed to 1% (2:55 PM, Jul 31, 2019 UTC-4)
- [x] Release 1907301630320 pushed to production (2019-08-08 18:19 UTC)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by erwinmombay** [comment]
This is currently blocked from getting into production. We are seeing issues in the RC channel.

**Comment by erwinmombay** [comment]
this has been promoted to production
