### ISSUE TITLE
🚄 Release tracking issue for release 1908162035200

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#23822]
# Release tracking issue

- [x] Release [1908061758110](https://github.com/ampproject/amphtml/releases/tag/1908061758110) is cut as a new canary release
- [x] Release 1908061758110 pushed to dev channel (2019-08-07 22:45 UTC)
- [x] Release 1908061758110 pushed to 1% (2019-08-08 21:28 UTC)
- [x] Cherry-pick (#23869) applied, new release: 1908121824440
- [x] Cherry-pick (#24020) applied, new release: [1908162035200](https://github.com/ampproject/amphtml/releases/tag/1908162035200)
- [x] Release 1908162035200 pushed to production (1:07 PM, Aug 19, 2019 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
