### ISSUE TITLE
🚄Release tracking issue for release 1908162134430

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#23939]
# Release tracking issue

- [x] Release [1908131750340](https://github.com/ampproject/amphtml/releases/tag/1908131750340) is cut as a new canary release
- [x] Cherry-picks (#23948, #23965, #23967) applied, new version: 1908150025400
- [x] Release 1908150025400 pushed to dev channel (11:12 PM, Aug 14, 2019 UTC-4)
- [x] Release 1908150025400 pushed to 1% (2:48 PM, Aug 15, 2019 UTC-4)
- [x] Cherry-picks (#24020, #24025) applied, new version: 1908162134430 (11:53 AM, Aug 19, 2019 UTC-4)
- [x] Release 1908162134430 pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
