### ISSUE TITLE
🚄Release tracking issue for canary release <INITIAL_CANARY_RELEASE_NUMBER> (Canary)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#24086]
# Release tracking issue

- [x] Release `[1908201719490](https://github.com/ampproject/amphtml/releases/tag/1908201719490)` is cut as a new canary release
- [ ] Release <RELEASE_NUMBER> pushed to dev channel (<CL submit time>)
- [ ] Release <RELEASE_NUMBER> pushed to 1% (<CL submit time>)
- [ ] Release <RELEASE_NUMBER> pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
