### ISSUE TITLE
🚄Release tracking issue for canary release 1909051756330 (1%)

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#24254]
# Release tracking issue

- [x] Release [1908271552560](https://github.com/ampproject/amphtml/releases/tag/1908271552560) is cut as a new canary release
- [x] Release [1908271552560](https://github.com/ampproject/amphtml/releases/tag/1908271552560) pushed to dev channel (4:05 PM, Aug 28, 2019 UTC-4)
- [x] Release [1908302047320](https://github.com/ampproject/amphtml/releases/tag/1908302047320) is cut as a new canary release with cherry-pick #24300 (7:02 PM, Aug 30, 2019 UTC-4)
- [x] Release [1908302047320](https://github.com/ampproject/amphtml/releases/tag/1908302047320) pushed to dev channel (7:59 PM, Aug 30, 2019 UTC-4)
- [x] Release [1908302047320](https://github.com/ampproject/amphtml/releases/tag/1908302047320) pushed to 1% (4:21 PM, Sep 3, 2019 UTC-4)
- [x] Release [1909051756330](https://github.com/ampproject/amphtml/releases/tag/1909051756330) is cut as a new 1% release with cherry-pick #24366 (7:47 PM, Sep 5, 2019 UTC-4)
- [x] Release [1909051756330](https://github.com/ampproject/amphtml/releases/tag/1909051756330) pushed to production (6:02 PM, Sep 9, 2019 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
