### ISSUE TITLE
🚄Release tracking issue for canary release 1909051736590 (Canary)

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#24352]
# Release tracking issue

- [x] Release [1909030343550](https://github.com/ampproject/amphtml/releases/tag/1909030343550) is cut as a new canary release
- [x] Release [1909030343550](https://github.com/ampproject/amphtml/releases/tag/1909030343550) pushed to dev channel (4:21 PM, Sep 3, 2019 UTC-4)
- [x] Release [1909051736590](https://github.com/ampproject/amphtml/releases/tag/1909051736590) created with cherry pick https://github.com/ampproject/amphtml/issues/24366
- [x] Release [1909051736590](https://github.com/ampproject/amphtml/releases/tag/1909051736590) pushed to dev channel (8:05 PM, Sep 5, 2019 UTC-4)
- [x] Release [1909051736590](https://github.com/ampproject/amphtml/releases/tag/1909051736590) pushed to 1% (8:06 PM, Sep 9, 2019 UTC-4)
- [ ] Release [1909051736590](https://github.com/ampproject/amphtml/releases/tag/1909051736590) pushed to production ()

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
