### ISSUE TITLE
🚄 Release tracking issue for release 1909141409590

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#24438]
# Release tracking issue

- [x] Release [1909100047420](https://github.com/ampproject/amphtml/releases/tag/1909100047420) is cut as a new canary release
- [x] Release 1909100047420 pushed to dev channel (5:21 PM, Sep 10, 2019 UTC-4)
- [x] Release 1909100047420 pushed to 1% (12:05 PM, Sep 11, 2019 UTC-4)
- [x] Release [1909131832350](https://github.com/ampproject/amphtml/releases/tag/1909131832350) is cut as a new canary release with cherry-picks #24483, #24504, #24470
- [x] Release 1909131832350 pushed to dev channel (5:24 PM, Sep 13, 2019 UTC-4)
- [x] Release 1909131832350 pushed to 1% (5:07 PM, Sep 13, 2019 UTC-4)
- [x] Release [1909141409590](https://github.com/ampproject/amphtml/releases/tag/1909141409590) is cut as a new canary release with cherry-pick #24530
- [x] Release 1909141409590 pushed to dev channel (12:38 PM, Sep 14, 2019 UTC-4)
- [x] Release 1909141409590 pushed to 1% (12:38 PM, Sep 14, 2019 UTC-4)
- [x] Release 1909141409590 pushed to production (2:52 PM, Sep 18, 2019 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by rsimha** [comment]
`1909141409590` went to production on Sep 18.
