### ISSUE TITLE
🚄 Release tracking issue for release 1909181902540

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#24694]
# Release tracking issue

- [x] Release [1909181902540](https://github.com/ampproject/amphtml/releases/tag/1909181902540) is cut as a new canary release
- [x] Release 1909181902540 pushed to dev channel (6:29 PM, Sep 18, 2019 UTC-4)
- [x] Release 1909181902540 pushed to 1% (7:27 PM, Sep 19, 2019 UTC-4)
- [x] Release 1909181902540 pushed to production (11:04 AM, Sep 24, 2019 UTC-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by rsimha** [comment]
Assigning to @calebcordry to update once 1909181902540 is pushed to production.
