### ISSUE TITLE
🚄Release tracking issue for canary release 1909241711100 (Canary)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#24713]
# Release tracking issue

- [x] Release [`1909241711100`](https://github.com/ampproject/amphtml/releases/tag/1909241711100) is cut as a new canary release
- [x] Release `1909241711100` pushed to dev channel (4:35 PM, Sep 24, 2019 UTC-7)
- [x] Release `1909241711100` pushed to 1% (2:11 PM, Sep 25, 2019 UTC-7)
- [x] Release `1909241711100` pushed to production (<CL submit time>)
- [x] Release `1910071803120` pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
