### ISSUE TITLE
Intent-to-Deprecate: Recursive form submissions

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#24894]
### Problem

```html
<!-- Infinite recursion form submission. -->
<form id="myForm" on="submit-success:myForm.submit">
```

See #24702 for details.

### Proposal

Add a third `ActionTrust` tier and have trust degrade by one level across form submit.

- High-intent user gestures are still "high trust".
- Existing actions that require "high trust" now require "default trust".

For example, a form submission that's triggered by a ("high trust") button press will emit a "default trust" event.

This "default trust" event can still trigger all existing actions, including form submission. So most use cases will not be affected.

However, a form submission that's triggered by a "default trust" event will emit a "low trust" event. This "low trust" event cannot trigger another form submission.

The new trust tiers would be as follows:
```js
export const ActionTrust = {
  /**
   * Events that are triggered without a user gesture, or triggered by a user
   * gesture with weak intent (e.g. scroll) are "low trust".
   *
   * Actions that have low impact on the page's visual state should require
   * "low trust" (e.g. pausing a video).
   */
  LOW: 1,	  
  /**
   * Events that are triggered nearly immediately (up to a few seconds) after
   * a user gesture with strong intent (e.g. tap or swipe) are "default trust".
   *
   * Actions that can modify the page's visual state (e.g. content jumping)
   * should require "default trust". This is the default required trust level
   * for actions.
   */
  DEFAULT: 2,
  /**
   * Events that are triggered immediately after a user gesture with
   * strong intent (e.g. tap or swipe) are "high trust".
   *
   * There are no actions yet that require high trust.
   */
  HIGH: 3,
};
```

### Implementation

Also requires fixing action->event trust propagation in the following components:
- [x] amp-accordion (email) (#25110)
- [ ] amp-date-picker
- [ ] amp-gwd-animation
- [x] amp-lightbox (email) (#25112)
- [ ] amp-pan-zoom
- [x] amp-selector (email) (#24431)
- [x] amp-sidebar (email) (#25095)

### Alternatives considered

- Add time-based resubmission detection to forms. This is brittle and could be worked around by chaining multiple `<form>` elements.
- Make `form:submit-*` events "low trust". This would break many existing use cases today.
- Make `form.submit` action require "high trust" and `form:submit-*` always be "default trust". This avoids the "degrading trust" concept but is more strict since it prevents any form submission loops.
