### ISSUE TITLE
🚄 Release tracking issue for release 1910071804120 (Production)

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#24998]
# Release tracking issue

- [x] Release [`1910071804120`](https://github.com/ampproject/amphtml/releases/tag/1910071804120) is cut as a new canary release (6:48 PM, Oct 7, 2019 UTC-4)
- [x] Release `1910071804120` pushed to dev channel (1:55 PM, Oct 8, 2019 UTC-4)
- [x] Release `1910071804120` pushed to 1% (<CL submit time>)
- [x] Release `1910071804120` pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
