### ISSUE TITLE
🚄Release tracking issue for canary release 1910161528000 (Canary)

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#25086]
# Release tracking issue

- [x] Release [1910161528000](https://github.com/ampproject/amphtml/releases/tag/1910161528000) is cut as a new canary release
- [x] Release 1910161528000 pushed to dev channel (7:01 PM, Oct 16, 2019 UTC-7)
- [x] Release 1910161528000 pushed to 1% (11:01 AM, Oct 18, 2019 UTC-7)
- [x] Release 1910161528000 pushed to production (9:43 AM, Oct 23, 2019 UTC-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
