### ISSUE TITLE
🚄Release tracking issue for canary release 1910222037440 (Prod)

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#25222]
# Release tracking issue

- [x] Release [1910222037440](https://github.com/ampproject/amphtml/releases/tag/1910222037440) is cut as a new canary release
- [x] Release <1910222037440> pushed to dev channel (10:57 PM, Oct 22, 2019 UTC-7)
- [x] Release <1910222037440> pushed to 1% (9:16 AM, Oct 23, 2019 UTC-7)
- [x] Release [1910251950120](https://github.com/ampproject/amphtml/releases/tag/1910251950120) created with cherry picks.
- [x] Release 1910251950120 pushed to Dev Channel (4:00 PM, Oct 25, 2019 UTC-7)
- [x] Release 1910251950120 pushed to 1% (4:52 PM, Oct 25, 2019 UTC-7)
- [x] Release 1910251950120 pushed to prod

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by jridgewell** [comment]
1910251950120 is now in production

**Comment by jridgewell** [comment]
A new release `001910302211460` is being pushed soon

**Comment by jridgewell** [comment]
Verified the fix in opt-in, pushing to 1% and prod
