### ISSUE TITLE
🚄 Release tracking issue for release 1911070201440

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#25493]
# Release tracking issue

- [x] Release [1911070201440](https://github.com/ampproject/amphtml/releases/tag/1911070201440) is cut as a new canary release
- [x] Release 1911070201440 pushed to dev channel (10:21 AM, Nov 7, 2019 UTC-8)
- [x] Release 1911070201440 pushed to 1% (1:09 PM, Nov 7, 2019 UTC-8)
- [x] Release 1911070201440 pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
