### ISSUE TITLE
🚄 Release tracking issue for release 1911121900560

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#25569]
# Release tracking issue

- [x] Release [1911121900560](https://github.com/ampproject/amphtml/releases/tag/1911121900560) is cut as a new canary release
- [x] Release 1911121900560 pushed to dev channel (9:51 PM, Nov 12, 2019 UTC-8)
- [X] Release 1911121900560 pushed to 1% (10:53 AM, Nov 14, 2019 UTC-8)
- [x] Release 1911121900560 pushed to production (3:09 PM, Nov 19, 2019 UTC-8)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
