### ISSUE TITLE
Dynamic adoption of shadow mode

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#25630]
Related to #22357 (part of #25500)

In order to offload code from extensions that use the `MultiDocManager` internally, one approach would be to allow adoption of shadow mode when such extensions are encountered which would expose the same API from PWAs to the extensions.

### Implications
- The extensions would now be able to use `AMP.attachShadowDoc` from the global object as opposed to having to create their own instance of `MultiDocManager`).

### Tasks
- [x] Separate the overlaid shadow mode layer code from `amp-shadow`
- [x] Detect extensions that require shadow mode and dynamically adopt it before loading the extensions
- [ ] Unit testing & e2e testing if needed
