### ISSUE TITLE
🚄 Release tracking issue for release 1912061958420

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25861]
# Release tracking issue

- [x] Release [1912032225230](https://github.com/ampproject/amphtml/releases/tag/1912032225230) is cut as a new canary release
- [x] Release 1912032225230 pushed to dev channel (5:36 PM, Dec 3, 2019 UTC-8)
- [x] Release [1912050134470](https://github.com/ampproject/amphtml/releases/tag/1912050134470) created with cherry picks #25878.
- [x] Release 1912050134470 pushed to Dev Channel
- [x] Release 1912050134470 pushed to 1% (11:10 AM, Dec 5, 2019 UTC-8)
- [x] Release [1912061958420](https://github.com/ampproject/amphtml/releases/tag/1912061958420) created with cherry picks #25919.
- [x] Release 1912061958420 pushed to dev channel (2:49 PM, Dec 6, 2019 UTC-8)
- [x] Release 1912061958420 pushed to 1% (3:07 PM, Dec 6, 2019 UTC-8)
- [x] Release [1912120230490](https://github.com/ampproject/amphtml/releases/tag/1912120230490) created with cherry picks #25945.
- [x] Release 1912120230490 pushed to dev channel (December 12, 2019, 6:36:54 PM GMT-5)
- [x] Release 1912120230490 pushed to 1% (December 12, 2019, 7:36:04 PM GMT-5)
- [x] Release 1912120230490 pushed to production (December 13, 2019, 3:14:33 PM GMT-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by newmuis** [comment]
I'm having trouble getting this to pass on Travis due to an error in the tests:

```
Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/ and ensure it can be found on your PATH.
```
https://travis-ci.org/ampproject/amphtml/jobs/623960002

Rerunning seems to have no impact.  @ampproject/wg-infra what's the recommended course of action here?

**Comment by danielrozenberg** [comment]
> 
> https://travis-ci.org/ampproject/amphtml/jobs/623960002
> 

@newmuis the Travis job you linked to is green, I assume you restarted it and it works now?

**Comment by estherkim** [comment]
It was a corrupt cache issue 🙁

**Comment by rsimha** [comment]
Closing this now that 1912120230490 has been pushed to stable.
