### ISSUE TITLE
🚄 Release tracking issue for release 1912101856490

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#25987]
# Release tracking issue

- [x] Release [1912101856490](https://github.com/ampproject/amphtml/releases/tag/1912101856490) is cut as a new canary release (12:40 AM, Dec 11, 2019 UTC-5)
- [x] Release 1912101856490 pushed to dev channel (1:10 PM, Dec 11, 2019 UTC-5)
- [x] Release 1912101856490 pushed to 1% (7:19 PM, Dec 11, 2019 UTC-5)
- [x] Release 1912120230490 pushed to dev channel (December 12, 2019, 6:36:54 PM GMT-5)
- [x] Release 1912120230490 pushed to 1% (December 12, 2019, 7:36:04 PM GMT-5)
- [x] Release 1912101856490 re-pushed to dev channel (December 13, 2019, 3:41:37 PM GMT-5)
- [x] Release 1912101856490 re-pushed to 1% (December 13, 2019, 5:40:22 PM GMT-5)
- [x] Release 1912101856490 pushed to production (December 17, 2019, 2:10:13 PM GMT-5)
- [x] Release [1912201827130](https://github.com/ampproject/amphtml/releases/tag/1912201827130) created with cherry picks.
- [x] Release 1912201827130 pushed to production (December 20, 2019, 3:23:35 PM GMT-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by rsimha** [comment]
FYI: 1912101856490 was temporarily rolled back from opt-in and 1% to make way for 1912120230490 (last week's RC + cherry-pick #25945). It can now be restored.

**Comment by rsimha** [comment]
Closing this, now that 1912101856490 has been promoted to stable.

**Comment by rsimha** [comment]
Reopening due to #26118.

**Comment by rsimha** [comment]
https://github.com/ampproject/amphtml/releases/tag/1912201827130 has been promoted to stable.

**Comment by kristoferbaxter** [comment]
https://github.com/ampproject/amphtml/releases/tag/1912201827130 has been promoted to LTS.
