### ISSUE TITLE
🚄 Release tracking issue for release 1912180046560

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#26087]
# Release tracking issue

- [x] Release [1912180046560](https://github.com/ampproject/amphtml/releases/tag/1912180046560) is cut as a new canary release
- [x] Release 1912180046560 pushed to dev channel (December 18, 2019, 2:53:56 PM GMT-5)
- [x] Release 1912180046560 pushed to 1% (December 19, 2019, 5:54:13 PM GMT-5)
- [x] Release 1912180046560 pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).

**Comment by rsimha** [comment]
FYI @estherkim who is next week's release on-duty.

Closing because this release isn't going to stable.

**Comment by rsimha** [comment]
It turns out that there was no new canary cut during the holiday release freeze. Release 1912180046560 is still out to 1%, and should be promoted to stable this week.

Reopening this and assigning to @kristoferbaxter, who is on-duty.

**Comment by kristoferbaxter** [comment]
Thanks @rsimha! Makes sense.

**Comment by kristoferbaxter** [comment]
Closing, as this is now pushed to production.
