### ISSUE TITLE
🚄Release tracking issue for release 2001071857360

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#26268]
# Release tracking issue

- [x] Release [2001071857360](https://github.com/ampproject/amphtml/releases/tag/2001071857360) is cut as a new canary release
- [x] Release 2001071857360 pushed to dev channel (<CL submit time>)
- [x] Release 2001071857360 pushed to 1% (<CL submit time>)
- [x] Release 2001071857360 pushed to production (January 15, 2020, 1:12:13 PM GMT-8)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://bit.ly/amp-cherry-pick).
