### ISSUE TITLE
Project Tracker: Improve test-vendors

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#26302]
- [x] Mock variable service #26300
- [x] Handle parameters in mocked variable service #26300
- [x] Handle parameters in global url-replace-service mock #26828
- [x] Handle nested macros #26271
