### ISSUE TITLE
🚄Release tracking issue for canary release 2001141706210 (Canary)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#26356]
# Release tracking issue

- [x] Release [`2001141706210`](https://github.com/ampproject/amphtml/releases/tag/2001141706210) is cut as a new canary release
- [x] Release 2001141706210 pushed to dev channel (January 15, 2020, 1:48:55 PM GMT-8)
- [x] Release 2001141706210 pushed to 1% (<CL submit time>)
- [ ] Release 2001141706210 pushed to production (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Dev Channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

**Comment by photocoder** [comment]
https://dimasfrolov.com
Today I see on my page a lot of errors :

error.js:202 a.getResources(...).mutateElement is not a function
hf @ error.js:202
amp-auto-lightbox.js:321 Uncaught (in promise) TypeError: a.getResources(...).mutateElement is not a function
    at amp-auto-lightbox.js:321

**Comment by kristoferbaxter** [comment]
@alanorozco and @jridgewell are looking into this.

**Comment by kristoferbaxter** [comment]
@gmajoulet - Let's rollback, and get this issue fixed with a cherry pick.

**Comment by jridgewell** [comment]
Rollback is submitted, waiting for propagation. Should be about 30min.

**Comment by jridgewell** [comment]
Rollback was successfully pushed (a while ago, just forgot to comment).
