### ISSUE TITLE
CMP consent prompt UX and a11y redesign

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#26432]
Project tracker for #26197 (related to #17257)
[Design doc is here](https://docs.google.com/document/d/1VQ9qqOhGznS_5ySrusBBz_GFEfsLjHYUJSketwq9-9I/edit)

- [x] Create feature flag & remove focusing on iframe (document.activeElement) #26437
- [x] SR a11y changes (through role alertDialog) #26456
- [x] Restrict fullScreen before user interaction #26461
- [x] dev error and postMessage messages (& documentation) #26467
- [x] Document fullscreen restriction #26487
- [x] Document a11y changes for pubs #26722
- [x] Add e2e tests #26584
- [x] Turn on Canary Flag #26766
- [x] Turn on Production Flag #26909

**Comment by micajuine-ho** [comment]
cc @lannka
