### ISSUE TITLE
🚄 Release tracking issue for release 2001251659540

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#26510]
# Release tracking issue

- [x] Release [2001232119410](https://github.com/ampproject/amphtml/releases/tag/2001232119410) is cut as a new canary release
- [x] Release [2001232119410](https://github.com/ampproject/amphtml/releases/tag/2001232119410) promoted to Experimental and Beta (opt-in) channels (11:29 AM, Jan 24, 2020 UTC-5)
- [x] Release [2001232119410](https://github.com/ampproject/amphtml/releases/tag/2001232119410) promoted to Experimental and Beta (1% traffic) channels (2:48 PM, Jan 24, 2020 UTC-5)
- [x] Release 2001251659540 created with cherry pick #26483
- [x] Release 2001251659540 promoted to Experimental and Beta (opt-in) channels (4:20 PM, Jan 25, 2020 UTC-5)
- [x] Release 2001251659540 promoted to Experimental and Beta (1% traffic) channels (4:52 PM, Jan 25, 2020 UTC-5)

- [x] Release 2001251659540 promoted to Production channel (
January 29, 2020, 6:10:43 PM GMT-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
