### ISSUE TITLE
🚄 Release tracking issue for release 2001281851410

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#26560]
# Release tracking issue

- [x] Release [2001281851410](https://github.com/ampproject/amphtml/releases/tag/2001281851410) is cut as a new canary release
- [x] Release 2001281851410 promoted to Experimental and Beta (opt-in) channels (January 30, 2020, 2:25:47 PM GMT-5)
- [x] Release 2001281851410 promoted to Experimental and Beta (1% traffic) channels (January 30, 2020, 2:25:47 PM GMT-5)
- [x] Release 2001281851410 promoted to Stable channel (<CL submit time>)
- [x] Release 2002072310350 created with cherry-picks (<CL submit time>)
- [x] Release 2002072310350 promoted to Stable channel (<CL submit time>)
- [x] Rolled back Stable channel to 2001281851410 ()
- [x] Release 2001281851410 promoted to LTS (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

**Comment by Enriqe** [comment]
@rcebulko will be taking on the release duties from here on
