### ISSUE TITLE
🚄 Release tracking issue for release 2002041606330, 2002112037430 (Experimental/Beta)

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#26619]
# Release tracking issue

- [x] Release [2002041606330](https://github.com/ampproject/amphtml/releases/tag/2002041606330)` is cut as a new canary release
- [x] Release 2002041606330 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [x] Release 2002041606330 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [x] Release 2002072311510 created with cherry-picks
- [x] Release 2002072311510 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [x] Release 2002072311510 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [x] Rolled back Experimental and Beta (opt-in) channels to 2002041606330 ()
- [x] Rolled back Experimental and Beta (1% traffic) channels to 2002041606330
- [ ] ~~Release 2002072311510 promoted to Stable channel (<CL submit time>)~~
- [x] Rolled back 2002072311510 back to 2002041606330 due to https://github.com/ampproject/amphtml/issues/26665
- [x] Patched 2002072311510 with https://github.com/ampproject/amphtml/commit/af50ae0f25b9766334d3e77a7ea0d60ca4d807b0 and https://github.com/ampproject/amphtml/commit/315d430fcf2eb1c5e5a1db13bb808aaf0a57712c to turn into 2002112037430 02/12/2020
- [x] Promote 2002112037430 to production 11:40 AM, Feb 13, 2020 UTC-8

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
