### ISSUE TITLE
Evaluate uses of meta.getAttribute('content')

### ISSUE THREAD

**Issue by mdmower** [ampproject/amphtml#26652]
Several extensions and services query AMP documents for special `<meta name="..." content="...">` tags to perform tasks different than default. In #26534, `amp-script` failed to work in PWAs because `<meta>` tags are lost when an AMP document is loaded in the `ShadowRoot`. Less severe issues may be present elsewhere and have gone unnoticed.

There are [new `.getMetaByName()` methods](https://github.com/ampproject/amphtml/issues/26609) that work for all AmpDoc types (single, shadow, fie) and which may be worthwhile to adopt in other extensions and services. A couple of greps (`grep -lr "getAttribute('content')"` and `grep -lr 'meta\[name'`) work as a starting point to investigate:

- [x] extensions/amp-a4a/0.1/refresh-manager.js
  ✔ [a4a: RefreshManager: Support amp-ad-enable-refresh lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26840)
- [x] extensions/amp-access/0.1/amp-access-server-jwt.js
  ✔ [amp-access: Support i-amphtml-access-state lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26679)
- [x] extensions/amp-access/0.1/amp-access-server.js
  ✔ [amp-access: Support i-amphtml-access-state lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26679)
- [x] extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  ✔ [amp-ad: Support amp-3p-iframe-src lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26682)
- [x] extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  ✔ [amp-ad-network-doubleclick: Respect meta['referrer'] in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26678)
- [x] ~~extensions/amp-ad-network-fake-impl/0.1/amp-ad-metadata-transformer.js~~
  This is used by `transformCreative_()` in `amp-ad-network-fake-impl.js`. It... "Converts a general AMP doc to a AMP4ADS doc.". It is intended to work with a real `document` and not an `ampdoc`, so it is appropriate to leave as-is.
- [x] extensions/amp-ad/0.1/amp-ad.js
  ✔ [amp-ad: Support amp-3p-iframe-src lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26682)
- [x] extensions/amp-analytics/0.1/linker-manager.js
  ✔ [amp-analytics: Support amp-google-client-id-api lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26683)
- [x] extensions/amp-apester-media/0.1/utils.js
  ✔ [amp-apester: Support keyword lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/27345)
- [x] extensions/amp-app-banner/0.1/amp-app-banner.js
  ✔ [amp-app-banner: Support apple-itunes-app lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/27346)
- [x] ~~extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js~~
  Not `meta[name]`
- [x] ~~extensions/amp-jwplayer/0.1/amp-jwplayer.js~~
  Not `meta[name]`
- [x] extensions/amp-script/0.1/amp-script.js
  ✔ [amp-script: Use updated method to get meta hashes](https://github.com/ampproject/amphtml/pull/26535)
- [x] ~~extensions/amp-story-auto-ads/0.1/utils.js~~
  `AdDoc` is an "ad document within FIE", so support for multiple `meta[name]` lookup methods is not necessary.
- [x] ~~extensions/amp-story/1.0/amp-story.js~~
  amp-story is actually setting `theme-color`, which must be done at the root document level, so this should be left as-is.
- [x] ~~extensions/amp-story/1.0/test/test-amp-story.js~~
  amp-story is actually setting `theme-color`, which must be done at the root document level, so this should be left as-is.
- [x] src/3p-frame.js
  ✔ [amp-ad: Support amp-3p-iframe-src lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26682)
- [x] ~~src/cookies.js~~
  `meta[name='amp-cookie-scope']` is expected in the shell `<head>` for `AmpDocShadow`
- [x] ~~src/experiments.js~~
  Opting to leave as-is. `meta[name="amp-experiments-opt-in"]` is currently expected in the shell `<head>`, so experiments apply to all loaded `AmpDoc`s. This seems like the correct design.
- [x] ~~src/inabox/utils.js~~
  amp-inabox is designed only with single docs in mind: "Declare that this runtime will support a single root doc."
- [x] ~~src/mediasession-helper.js~~
  Not `meta[name]`
- [x] ~~src/multidoc-manager.js~~
  Import of `<meta>` tags for `AmpDocShadow`
- [x] src/service/action-impl.js
  ✔ [amp-action: Support whitelist lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26684)
- [x] ~~src/service/ampdoc-impl.js~~
  Definition of get/setMetaByName
- [x] src/service/cid-impl.js
  ✔ [amp-analytics: Support amp-google-client-id-api lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26683)
- [x] src/service/document-info-impl.js
  ✔ [DocInfo: replace metaTags with viewport in API](https://github.com/ampproject/amphtml/pull/26687)
- [x] ~~src/service/navigation.js~~
  PWAs are expected to handle navigation on their own. No plans to enable support for `amp-to-amp-navigation` in `AmpDocShadow`.
- [x] ~~src/service/origin-experiments-impl.js~~
  Opting to leave as-is. `meta[name="amp-experiments-opt-in"]` is currently expected in the shell `<head>`, so experiments apply to all loaded `AmpDoc`s. This seems like the correct design.
- [x] src/service/url-replacements-impl.js
  ✔ [variable substitutions: Support whitelist lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26731)
- [x] src/service/variable-source.js
  ✔ [variable substitutions: Support whitelist lookup in AmpDocShadow](https://github.com/ampproject/amphtml/pull/26731)
- [x] ~~src/service/viewport/viewport-impl.js~~
  Shell document should be used to get viewport data.
- [x] ~~test/unit/test-viewport.js~~
  Shell document should be used to get viewport data.
- [x] ~~third_party/subscriptions-project/config.js~~
  Not `meta[name]`

**Comment by mdmower** [comment]
If anyone knows whether certain extensions/services will never be used in an AmpDocShadow, I'd appreciate it if you could chime-in. I've seen hints in A4A and amp-story that suggest they only ever expect to to run in `AmpDocSingle`. If that's the case we can omit them from this analysis.

**Comment by kevinkimball** [comment]
>src/service/navigation.js
PWAs usually handle navigation on their own; unsure that it would be wise to enable support for amp-to-amp-navigation in AmpDocShadow

Correct. In the PWA context there will be no viewer, so A2A is not supported and this is not needed

**Comment by mdmower** [comment]
@wg-ads Is it safe to assume that anything related to a4a will never be viewed as an `AmpDocShadow` (i.e never viewed in a `ShadowRoot`)? Any items that you could cross off the list as "no fix needed" would be appreciated. Thanks!

**Comment by mdmower** [comment]
🎉
