### ISSUE TITLE
I2I: Multi-selector support for visibility trigger

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#26823]
Follow up to #11380.

**NOTE**: This only applies to visibility triggers as well as static content (i.e. no mustache template selectors, no dynamic content). At this time, visibility triggers only work for amp-elements.

## Summary

- Multi-selector support: Add support for a single visibility trigger to support multiple selectors 
- QuerySelectorAll support: Add support for a visibility trigger’s selector(s) to track all elements have the selector(s) (instead of the first element)

## Design document

[External Doc](https://docs.google.com/document/d/1tvGV0_SJqIsbDqWYiaq0IuVZbOwT1ZkxUxm_NCLYl6E/edit?usp=sharing)

## Design Proposal

- **Multi-selector**: Add array support for the `selector` field within a visibility trigger
- **QuerySelectorAll**: All selectors within the multi-selector array will be treated as querySelectorAll
- Restrict listeners (and requests) for elements that do not have a `data-var-*` attribute

See the design doc above for details.

## Motivation

In amp-analytics, it is hard for publishers to track the visibility of elements that share selectors. Our current implementation only allows a one-to-one mapping between a single element and visibility trigger. This presents a challenge for publishers who would like to track the visibility of all similar elements, such as all amp-ads ~~or all paragraphs in an article~~.

## Launch tracker

- [x] Feature Flag #26862
- [x] Multi-selector #26862
- [x] querySelectorAll #26886
- [x] Restrict unique requests #26902
- [x] Turn on experiment in Canary #30861
- [x] Turn on experiment in Prod #31066
- [x] Document Changes #26911
- [ ] Clean up

/cc @lannka @zhouyx

**Comment by zhouyx** [comment]
Thank you @micajuine-ho this is going to save a lot of configurations! 
Could you please highlight the format of the chosen proposal.

**Comment by micajuine-ho** [comment]
> Could you please highlight the format of the chosen proposal.

Updated!

**Comment by enderton** [comment]
Hello!  We've been following this issue, and are very excited for these changes to improve our impression analytics logic (and have tried it locally in development).  Is there a known timeline for when the experiment flag will be removed (for the `querySelectorAll` portion)?  Thanks.

**Comment by micajuine-ho** [comment]
Hi @enderton, have you used this feature with the experiment flag on?

**Comment by enderton** [comment]
Yes - in local and staged environments, yes (via toggling in dev tools `AMP.toggleExperiment('visibility-trigger-improvements')`.

Is not yet in production code served by AMP CDN, so have not used https://amp.dev/documentation/guides-and-tutorials/learn/experimental/#served-from-cdn.ampproject.org.

It's our understanding that we could not enable this experiment for all users, so have held off making part of production code.
