### ISSUE TITLE
🚄 Release tracking issue for release 2002142325340, 2002191442400

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#26848]
# Release tracking issue

- [x] Release [2002142325340](https://github.com/ampproject/amphtml/releases/tag/2002142325340) is cut as a new canary release
- [x] Release 2002142325340 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [ ] ~~Release 2002142325340 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)~~
- [ ] ~~Release 2002142325340 promoted to Stable channel (<CL submit time>)~~
- [x] Release 2002191442400 to opt-in 12:09 PM, Feb 19, 2020 UTC-8
- [x] Release 2002191442400 to beta/experiment 1% 1:42 PM, Feb 19, 2020 UTC-8
- [x] Release 2002191442400 to stable 3:58 PM, Feb 19, 2020 UTC-8

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
