### ISSUE TITLE
🚄 Release tracking issue for release 2002192257490

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#26885]
# Release tracking issue

- [x] Release [2002192257490](https://github.com/ampproject/amphtml/releases/tag/2002192257490>) is cut as a new canary release
- [x] Release 2002192257490 promoted to Experimental and Beta (opt-in) channels (12:34 PM, Feb 20, 2020 UTC-8)
- [x] Release 2002192257490 promoted to Experimental and Beta (1% traffic) channels (1:07 PM, Feb 20, 2020 UTC-8)
- [x] Release <RELEASE_NUMBER> promoted to Stable channel (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
