### ISSUE TITLE
🚄 Release tracking issue for release 2002251816300

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#27014]
# Release tracking issue

- [x] Release [2002251816300](https://github.com/ampproject/amphtml/releases/tag/2002251816300) is cut as a new canary release
- [x] Release 2002251816300 promoted to Experimental and Beta (opt-in) channels (February 26, 2020, 8:01:13 PM GMT-5)
- [x] Release 2002251816300 promoted to Experimental and Beta (1% traffic) channels (
February 27, 2020, 4:37:26 PM GMT-5)
- [x] Release 2002251816300 promoted to Stable channel (8:46 AM, Mar 6, 2020 UTC-8)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

**Comment by wassgha** [comment]
Promoted to LTS
