### ISSUE TITLE
🚄 Release tracking issue for release 2003031842100

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#27182]
# Release tracking issue

- [x] Release [2003031842100](https://github.com/ampproject/amphtml/releases/tag/2003031842100) is cut as a new canary release
- [x] Release 2003031842100 promoted to Experimental and Beta (opt-in) channels (10:11 AM, Mar 10, 2020 UTC-7)
- [x] Release 2003031842100 promoted to Experimental and Beta (1% traffic) channels (11:10 AM, Mar 10, 2020 UTC-7)
- [x] Release 2003031842100 promoted to Stable channel (4:25 PM, Mar 12, 2020 UTC-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

**Comment by wassgha** [comment]
Promoted to stable 4:25 PM, Mar 12, 2020 UTC-7
