### ISSUE TITLE
🚄 Release tracking issue for release 2003101714470

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#27217]
# Release tracking issue

- [x] Release [2003101714470](https://github.com/ampproject/amphtml/releases/tag/2003101714470) is cut as a new canary release
- [x] Release 2003101714470 promoted to Experimental and Beta (opt-in) channels (9:46 PM, Mar 12, 2020 UTC-7)
- [x] Release 2003101714470 promoted to Experimental and Beta (1% traffic) channels (10:00 AM, Mar 13, 2020 UTC-7)
- [x] Release 2003101714470 promoted to Stable channel (5:53 PM, Mar 17, 2020 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
