### ISSUE TITLE
🚄 Release tracking issue for release 2003171848440

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#27275]
# Release tracking issue

- [x] Release [2003171848440](https://github.com/ampproject/amphtml/releases/tag/2003171848440) is cut as a new canary release
- [x] Release 2003171848440 promoted to Experimental and Beta (opt-in) channels (6:54 PM, Mar 17, 2020 UTC-4)
- [x] Release 2003171848440 promoted to Experimental and Beta (1% traffic) channels (6:18 PM, Mar 18, 2020 UTC-4)
- [x] Release [2003241513590](https://github.com/ampproject/amphtml/releases/tag/2003241513590) created via cherry-pick (#27353) (1:29 PM, Mar 24, 2020 UTC-4)
- [x] Release 2003241513590 promoted to Experimental and Beta (opt-in) channels (3:55 PM, Mar 24, 2020 UTC-4)
- [x] Release 2003241513590 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [x] Release 2003241513590 promoted to Stable channel (<CL submit time>)
- [x] Release 2003241513590 rolled back to 2003171848440 (see https://github.com/ampproject/amphtml/issues/27425) (10:27 AM, March 26, 2020 UTC-4)
- [x] Release 2003261442330 created via cherry-pick (#27425) (1:49 PM, 
March 26, 2020 UTC-4)
- [x] Release 2003261442330 promoted to Stable channel (4:02 PM, March 26, 2020 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

**Comment by rcebulko** [comment]
Rolled back; re-opening
