### ISSUE TITLE
🚄 Release tracking issue for release 2003241730220

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#27390]
# Release tracking issue

- [x] Release [2003241730220](https://github.com/ampproject/amphtml/releases/tag/2003241730220) is cut as a new canary release
- [x] Release 2003241730220 promoted to Experimental and Beta (opt-in) channels (4:34 PM, March 25, 2020 UCT-4)
- [x] Release [2003262059300](https://github.com/ampproject/amphtml/releases/2003262059300) created via cherry-pick (see #27425) (10:16 AM, March 27, 2020 UTC-4)
- [x] Release 2003262059300 promoted to Experimental and Beta (opt-in) channels (12:56 PM, March 27, 2020 UTC-4)
- [x] Release 2003262059300 promoted to Experimental and Beta (1% traffic) channels (March 27, 2020, 3:48:05 PM GMT-4)
- [x] Release 2003262059300 promoted to Stable channel (
March 31, 2020, 3:37:54 PM GMT-4)
- [x] Release [2004012158290](https://github.com/ampproject/amphtml/releases/tag/2004012158290) created with cherry picks
- [x] Release 2004012158290 promoted to Experimental and Beta (April 1, 2020, 7:55:37 PM GMT-4)
- [x] Release 2004012158290 promoted to Stable channel (April 1, 2020, 7:56:34 PM GMT-4) 

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

**Comment by rsimha** [comment]
`2003262059300` is in Stable now.

**Comment by rsimha** [comment]
Reopening because `2003262059300` was rolled back.

**Comment by rsimha** [comment]
CP release [2004012158290](https://github.com/ampproject/amphtml/releases/tag/2004012158290) has been promoted to 1% and Stable.
