### ISSUE TITLE
🚄 Release tracking issue for release 2003311743260

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#27511]
# Release tracking issue

- [x] Release [2003311743260](https://github.com/ampproject/amphtml/releases/tag/2003311743260) is cut as a new canary release
- [x] Release 2003311743260 promoted to Experimental and Beta (opt-in) channels (March 31, 2020, 6:02:39 PM GMT-4)
- [x] Release [2004012111560](https://github.com/ampproject/amphtml/releases/tag/2004012111560) created with cherry picks
- [x] Release 2004012111560 promoted to Experimental and Beta (opt-in) channels (
April 2, 2020, 1:49:55 PM GMT-4)
- [ ] Release 2004012111560 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [ ] Release 2004012111560 promoted to Stable channel (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
