### ISSUE TITLE
🚄 Release tracking issue for release 2004030010070

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#27555]
# Release tracking issue

- [ ] Release `[2004030010070](https://github.com/ampproject/amphtml/releases/tag/2004030010070)` is cut as a new canary release
- [ ] Release 2004030010070 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [ ] Release 2004030010070 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [x] Release 2004030010070 promoted to Stable channel (6:52 PM PST April 2, 2020)
- [x] Release 2004030010070 promoted to LTS (April 13, 2020, 2:52:56 PM PST)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

**Comment by nainar** [comment]
We are cutting a new release to stable first to fix a prod issue. 

Will cut canary later since not as urgent.

**Comment by nainar** [comment]
@erwinmombay has cut the stable release. 

@rsimha to follow up on Beta/experimental
