### ISSUE TITLE
amp-bind: remove the need for treewalking

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#27590]
**summary**
Currently, `amp-bind` uses a [TreeWalker](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker) in order to find bindings on elements. This is an expensive operation. We can significantly speed this up via preprocessing in the AMP Optimizer.

Instead of using the TreeWalker, we could use the optimizer to place the attribute `i-amphtml-binding` on each element with a binding and use `querySelectorAll` in the runtime to find them.

**todo**
- [x] Measure expected perf win: time spent treewalking for light/heavy pages vs. querySelectorAll times for the same pages.
-  [x] Implement AMP Optimizer / AMP Cache changes: https://github.com/ampproject/amphtml/pull/32851
-  [x] Implement amp-bind changes.: https://github.com/ampproject/amp-toolbox/pull/1147
- [x] Validator changes: https://github.com/ampproject/amphtml/pull/32901

cc @ampproject/wg-runtime

**Comment by samouri** [comment]
Expected perf win: on 6x cpu slowdown, 50ms --> 0.2ms. Measured via @jridgewell

**Comment by kristoferbaxter** [comment]
This is a great idea.
