### ISSUE TITLE
🚄 Release tracking issue for release 2004161906340

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#27625]
# Release tracking issue

- [x] Release [2004071640410](https://github.com/ampproject/amphtml/releases/tag/2004071640410) is cut as a new canary release
- [x] Release 2004071640410 promoted to Experimental and Beta (opt-in) channels (April 7, 2020, 3:55:59 PM PDT)
- [x] Release 2004071640410 promoted to Experimental and Beta (1% traffic) channels (April 8, 2020, 12:06:23 PM PDT)
- [x] ~~Release 2004071640410 promoted to Stable channel (April 14, 2020, 1:37:23 PM PST)~~ **reverted** back to 2004030010070 (April 14, 2020, 4:06:00 PM PST)
- [x] Release 2004142326360 created with cherry pick #27769 (April 14, 2020, 5:03:18 PM PST)
- [x] ~~Release 2004142326360 promoted to Stable channel (April 14, 2020, 5:40:05 PM PST)~~ **reverted** back to 2004030010070 (April 15, 2020, 7:40:59 AM PST)
- [x] Release 2004152338170 created with cherry pick #27790 (April 15, 2020, 5:18:37 PM PST)
- [x] Release 2004161906340 created with cherry pick #27734 (April 16, 2020, 1:29:02 PM PST)
- [x] ~~Release 2004161906340 promoted to Stable channel (April 16, 2020, 2:38:57 PM PST)~~ **reverted** back to 2004030010070 (April 17, 2020, 12:03:45 PM PST)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

**Comment by danielrozenberg** [comment]
This release is being reverted while the above-linked cherry-pick is being performed

**Comment by danielrozenberg** [comment]
2004142326360 is the cherry-pick on top of 2004071640410, and is now on Stable
