### ISSUE TITLE
Track features before launch of <amp-story-animation>

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#27758]
- [x] Support tag (#27597)
- [x] Scope selectors to its `<amp-story-page>` (#27887, [context](https://github.com/ampproject/amphtml/pull/27597#discussion_r405847475)).
- [ ] Provide all [getDims() values](https://github.com/ampproject/amphtml/blob/b6313e372fdd1298928e2417dcc616b03288e051/extensions/amp-story/1.0/animation.js#L159) as <amp-animation> CSS config (#28146):
  - [ ] Possible optimization: Use `getLayoutBox` values when available.
- [x] Support sequencing (`animate-in-after`) (#27985)
- [ ] Validation file for `<amp-story-animation>` 
- [ ] Decide on subanimations API: element by id, subanimations, or `<style keyframes>`?
- [ ] Don't depend on async `getDims()` for presets:
  1. The initial keyframe should _not_ require dimension calculations. Write a test for this.
  2. Remove async chain.
