### ISSUE TITLE
🚄 Release tracking issue for release 2004172112280

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#27765]
# Release tracking issue

- [x] Release [2004111615170](https://github.com/ampproject/amphtml/releases/tag/2004111615170) is cut as a new nightly release
- [x] Release [2004141826300](https://github.com/ampproject/amphtml/releases/tag/2004141826300) created with cherry picks
- [x] Release 2004141826300 promoted to Experimental and Beta (opt-in) channels (April 14, 2020, 2:19:38 PM PST)
- [x] Release [2004142327160](https://github.com/ampproject/amphtml/releases/tag/2004142327160) created with cherry pick #27769 (April 14, 2020, 5:07:15 PM PST)
- [x] Release 2004142327160 promoted to Experimental and Beta (opt-in) channels (April 14, 2020, 5:50:23 PM PST)
- [x] Release [2004152339120](https://github.com/ampproject/amphtml/releases/tag/2004152339120) created with cherry pick #27790 (April 15, 2020, 5:26:21 PM PST)
- [x] Release 2004152339120 promoted to Experimental and Beta (opt-in) channels (April 15, 2020, 6:27:43 PM PST)
- [x] Release 2004152339120 promoted to Experimental and Beta (1% traffic) channels (April 16, 2020, 1:30:15 PM PST)
- [x] Release [2004172112280](https://github.com/ampproject/amphtml/releases/tag/2004172112280) created with cherry pick #27838 (April 17, 2020, 4:39:16 PM PST)
- [x] Release 2004172112280 promoted to Experimental and Beta (opt-in) channels (April 17, 2020, 5:19:40 PM PST)
- [x] Release 2004172112280 promoted to Experimental and Beta (1% traffic) channels (April 17, 2020, 5:09:16 PM PST)
- [x] Release 2004172112280 promoted to Stable (April 21, 2020, 10:20:52 PM PST)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
