### ISSUE TITLE
🚄 Release tracking issue for release 2004240001480

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#27908]
# Release tracking issue

- [x] Release [2004210608300](https://github.com/ampproject/amphtml/releases/tag/2004210608300) cut as a new nightly release
- [x] Release 2004210608300 promoted to Experimental and Beta (opt-in) channels (April 21, 2020, 11:28:04 PM PST)
- [x] Release [2004221922480](https://github.com/ampproject/amphtml/releases/2004221922480) cut with cherry pick https://github.com/ampproject/amphtml/issues/27947
- [x] Release 2004221922480 promoted to Experimental and Beta (opt-in) channels (April 22, 2020, 1:57:07 PM PST)
- [x] Release [2004240001480](https://github.com/ampproject/amphtml/releases/2004240001480) cut with cherry pick https://github.com/ampproject/amphtml/issues/28011
- [x] Release 2004240001480 promoted to Experimental and Beta (opt-in) channels (April 23, 2020, 6:28:19 PM PST)
- [x] Release 2004240001480 promoted to Experimental and Beta (1% traffic) channels (April 24, 2020, 8:54:19 AM PST)
- [x] Release 2004240001480 promoted to Stable channel (12:03 PM, Apr 28, 2020 UTC-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
