### ISSUE TITLE
🚄 Release tracking issue for release 2004252135000

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#28081]
# Release tracking issue

This issue tracks release [`2004252135000`](https://github.com/ampproject/amphtml/releases/tag/2004252135000)

- [x] Release `2004252135000` promoted to Experimental and Beta (opt-in) channels (1:57 PM, Apr 28, 2020 UTC-4)
- [x] Release `2004252135000` promoted to Experimental and Beta (1% traffic) channels (1:15 PM, Apr 29, 2020 UTC-4)
- [x] Release `2004252135000` promoted to Stable channel (May 5, 2020, 2:50:22 PM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).
