### ISSUE TITLE
🚄 Release tracking issue for release 2005050322000

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#28223]
# Release tracking issue

This issue tracks release [`2005050322000`](https://github.com/ampproject/amphtml/releases/tag/2005050322000)

- [x] Release `2005050322000` promoted to Experimental and Beta (opt-in) channels (May 5, 2020, 3:16:10 PM GMT-7)
- [x] Release `2005050322000` promoted to Experimental and Beta (1% traffic) channels (May 6, 2020, 10:03:38 AM GMT-7)
- [x] Release [2005050322001](https://github.com/ampproject/amphtml/releases/tag/2005050322001) created with cherry-pick #28307
- [x] Release 2005050322001 promoted to Experimental and Beta channels (
May 11, 2020, 4:53:57 PM GMT-7)
- [x] Release `2005050322001` promoted to Stable channel (May 12, 2020, 9:34:00 PM GMT-7)
- [x] Release [2005050322002](https://github.com/ampproject/amphtml/releases/tag/2005050322002) created with cherry-pick #28359
- [x] Release `2005050322002` promoted to Stable channel (May 12, 2020, 7:59:05 PM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by gmajoulet** [comment]
Next release: #28389
