### ISSUE TITLE
[amp-social-share:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#28283]
Open tasks:

- [x] Initial implementation in #26543
- [x] Storybook samples in AMP in #27745
- [x] AMP service reconfiguration in #28137
- [x] Unconfuse `params` and `bindings`. Likely remove one of them and flatten the other one into component props. #28137
- [x] Cleanup typing in the `amp-social-share-config.js`. #28137
- [x] Declare and use prop types. See [FitTextProps type](https://github.com/ampproject/amphtml/blob/master/extensions/amp-fit-text/1.0/fit-text.type.js). Cleanup typing part 2 https://github.com/ampproject/amphtml/pull/29658, https://github.com/ampproject/amphtml/pull/29880
- [x] Move "target" logic to the component. #29176 
- [x] Document design choices for component [Handling Children in Bento](https://docs.google.com/document/d/1LG-SzXpdUvTM1g2SIzE0UAheoLYW9r_motomzhX6Rlc/edit?usp=sharing), [Colors and Styling in Bento](https://docs.google.com/document/d/1qlGJT_XGuLC6FcS58kO4wY-7Fyko3NSEiH2cSXqIgLI/edit?usp=sharing)
- [x] ~Proposed documentation for using AMP services in Bento~
- [x] Update storybook - including knobs for colors https://github.com/ampproject/amphtml/pull/30191
- [x] Display children of component https://github.com/ampproject/amphtml/pull/29250
- [x] Default background color #29175 
- [x] Investigate SVG fill color (mdn `currentColor`) https://github.com/ampproject/amphtml/pull/29285
- [x] Update experiment version #29174
- [x] Add mutation observer https://github.com/ampproject/amphtml/pull/29436
- [x] Create automated tests (will test Bento through AMP) https://github.com/ampproject/amphtml/pull/29619
- [x] Create `passthroughNonEmpty` mode for handling children https://github.com/ampproject/amphtml/pull/29367
- [x] Update out-of-date logos https://github.com/ampproject/amphtml/pull/29867
- [x] Update config to allow color and children in all types https://github.com/ampproject/amphtml/pull/29632
- [x] Component should not throw errors https://github.com/ampproject/amphtml/pull/30200
- [x] Focus issue done in 0.1, add to 1.0 - #29561
- [x] Add validator for 1.0 - https://github.com/ampproject/amphtml/pull/33478

Other Fixes:
- [x] Move endpoint check from amp side to preact side https://github.com/ampproject/amphtml/pull/29325/
- [x] Do not throw error when params not provided for `type` = `email` https://github.com/ampproject/amphtml/pull/29633
- [x] ~Expand e2e tests to include one for each configurable type~

Documents:

[Handling Children in Bento](https://docs.google.com/document/d/1LG-SzXpdUvTM1g2SIzE0UAheoLYW9r_motomzhX6Rlc/edit?usp=sharing)
[Colors and Styling in Bento](https://docs.google.com/document/d/1qlGJT_XGuLC6FcS58kO4wY-7Fyko3NSEiH2cSXqIgLI/edit?usp=sharing)
[Design Notes](https://docs.google.com/document/d/1Ypo27kEJ7Qs0z336VPSbfEgUK9lS-dioFNCvl40nwGw/edit?usp=sharing)
[Design Doc](https://docs.google.com/document/d/1mtZu3NbD4tgmXtOTtYD_lEvMFUgebEyE4ZJc1ret-Wg/edit?usp=sharing)

Other Items:
- Eventually will create a module for utilities (i.e. isIOS)

cc: @nainar

**Comment by krdwan** [comment]
Tracking Open Items Here:

High Priority -
1. In Preact component, `params` and `bindings` are currently separate `props`.  After re-design of AMP component, we will take a comprehensive look into how `params` and `bindings` may be redesigned to create a simpler interface.

Nice to Have -
1. `PropType` type checking on Preact component `props`.

**Comment by dvoytenko** [comment]
@krdwan 

> Tracking Open Items Here:

This is great. But also a simple `TODO` item in the "Open tasks" in the description would suffice. See how I placed it into the description of the bug. It's nice to have it in a list in one place.

**Comment by krdwan** [comment]
> @krdwan
> 
> > Tracking Open Items Here:
> 
> This is great. But also a simple `TODO` item in the "Open tasks" in the description would suffice. See how I placed it into the description of the bug. It's nice to have it in a list in one place.

Thanks @dvoytenko !  I'm still a few merges away from having write access to the repo (and edit access on this issue).  I'll be sure to consolidate once I have it!
