### ISSUE TITLE
[amp-selector:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#28282]
## High-level requirements
| Consideration  | Ready when | Status |
| ------------- | ------------- | ------- |
| Component compatibility | [Conformance with 0.1 (see below)](https://amp.dev/documentation/components/amp-selector/) | ✅ |
| Testing | Unit tests and e2e tests from 0.1 | ✅ |
| Internationalization | n/a | n/a |
| Analytics | `select` event is supported | ✅ |
| Accessibility | Audit performed, [0.1 for reference](https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+label%3A%22UI%3A+Component%3A+amp-selector%22+label%3A%22Related+to%3A+Accessibility%22) |✅  |
| Page experience | Audit performed |✅ |
| Documentation | Written |✅ |
| Storybook | Samples written | ✅ |

## Component compatibility
Attributes to support: 
- [x] `disabled`
- [x] `form`
- [x] `multiple`
- [x] `name`
- [x] `keyboard-select-mode`/`keyboardSelectMode`
- option attributes:
  - [x] `option`
  - [x] `disabled`, `selected`

Events to support: 
- [x] `selected`/`onChange`

## Open tasks:

- [x] Initial implementation in #27365
- [x] Turn on pre-existing e2e tests in #28576
- [x] Support keyboard-select-mode
- [x] Integration with forms
- [x] Allow uncontrolled input usage; [related](https://github.com/ampproject/amphtml/pull/27365#discussion_r419750748)
- [x] [Support hybrid "disabled and selected" style state ](https://github.com/ampproject/amphtml/pull/27365#discussion_r419751701)-- currently "disabled" takes precedence over "selected"
- [x] [Use nullish coalescing](https://github.com/ampproject/amphtml/pull/27365#discussion_r419748198) once supported in #28339
- [x] [2-way DOM update and mutation observers](https://github.com/ampproject/amp-react-prototype/issues/40#issuecomment-566260499)
- [x] Decide on value typing (Array vs scalar) for non-multiple selectors
