### ISSUE TITLE
[amp-fit-text:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#28281]
## High-level requirements
| Consideration  | Ready when | Status |
| ------------- | ------------- | ------- |
| Component compatibility | [Conformance with 0.1 (see below)](https://amp.dev/documentation/components/amp-fit-text/) | ✅ |
| Testing | Unit tests and e2e tests from 0.1 | ✅ |
| Internationalization | n/a | n/a |
| Analytics | n/a | n/a |
| Accessibility | Audit performed, [0.1 for reference](https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+label%3A%22UI%3A+Component%3A+amp-fit-text%22+label%3A%22Related+to%3A+Accessibility%22) |✅ |
| Page experience | Audit performed |✅  |
| Documentation | Written |✅  |
| Storybook | Samples written | ✅ |

## Component compatibility
Attributes to support: 
- [x] `min-font-size` 
- [x] `max-font-size`

### Migration Notes:

- 1.0 resizes to clientHeight and clientWidth, whereas 0.1 resize to offsetHeight and offsetWidth. The difference here is the exclusion of margins and borders from the fit-text coverage area.

## Open tasks:

- [x] Initial implementation in #28169
- [x] [Do not depend on `children` to resize](https://github.com/ampproject/amphtml/pull/28169#discussion_r424797378) in #28496 
- [x] Watch for [attribute mutations in Bento mode.](https://github.com/ampproject/amphtml/pull/28169#discussion_r421660013)
    - Remove the specifically attached MutationObserver for attributes in `amp-fit-text` when a generic one is in place in `PreactBaseElement`.
    - The generic one should call `mutatedAttributesCallback` to handle Bento mode.
    - In AMP mode this will cause it to be doubly called -- need to fine tune this.
- [x] Resolve [infinite render issue](https://github.com/ampproject/amphtml/pull/28169#discussion_r424454269) when observing mutations on both `subtree` and `attributes`.
- [x] Support passing in a [parser callback](https://github.com/ampproject/amphtml/pull/28169#discussion_r421658550) for PreactBaseElement `props` 
- [x] ~Investigate e2e test failures for `amp4ads-preset` environments~
- [x] ~Remove constant `line-height` and support [configuring `lineHeight`](https://github.com/ampproject/amphtml/pull/28169#discussion_r419757497)~
- [x] [Polyfill ResizeObserver](https://github.com/ampproject/amphtml/pull/28169#discussion_r421127484)
- [x] Make attrs media based

**Comment by dvoytenko** [comment]
Added task:

> Remove constant line-height.
