### ISSUE TITLE
🚄 Release tracking issue for release 2005151837000

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28389]
# Release tracking issue

This issue tracks release [2005080549000](https://github.com/ampproject/amphtml/releases/tag/2005080549000)

- [x] Release 2005080549000 promoted to Experimental and Beta (opt-in) channels (May 13, 2020, 2:51:37 PM GMT-4)
- [x] Release [2005080549001](https://github.com/ampproject/amphtml/releases/tag/2005080549001) created with cherry picks #28359
- [x] Release 2005080549001 promoted to Experimental and Beta (opt-in) (May 14, 2020, 10:42:56 AM GMT-4)
- [x] Release 2005080549001 promoted to Experimental and Beta (1% traffic) channels (May 14, 2020, 10:42:56 AM GMT-4)
- [x] Release [2005080549002](https://github.com/ampproject/amphtml/releases/tag/2005080549002) created with cherry picks #28409
- [x] Release 2005080549002 promoted to Experimental and Beta (opt-in) (May 14, 2020, 5:53:30 PM GMT-4)
- [x] Release 2005080549002 promoted to Experimental and Beta (1% traffic) channels (May 14, 2020, 4:05:38 PM GMT-4)
- [x] Release [2005080549003](https://github.com/ampproject/amphtml/releases/tag/2005080549003) created with cherry picks #28433
- [x] Release [2005151844001](https://github.com/ampproject/amphtml/releases/tag/2005151844001) created with cherry picks #28441, #28307
- [x] Release 2005151844001 promoted to Experimental and Beta (opt-in) (May 15, 2020, 7:01:44 PM GMT-4)
- [x] Release 2005151844001 promoted to Experimental and Beta (1% traffic) channels (May 15, 2020, 6:17:54 PM GMT-4)
- [x] Release 2005151844001 promoted to Stable channel (May 19, 2020, 2:04:21 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
