### ISSUE TITLE
🚄 Release tracking issue for release 2005150002000

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#28500]
# Release tracking issue

This issue tracks release [2005150002000](https://github.com/ampproject/amphtml/releases/tag/2005150002000)

- [x] Release 2005150002000 promoted to Experimental and Beta (opt-in) channels (May 19, 2020, 2:22:39 PM GMT-4)
- [x] Release 2005150002000 promoted to Experimental and Beta (1% traffic) channels (May 20, 2020, 2:38:43 PM GMT-4)

- [X] Release [2005150002001](https://github.com/ampproject/amphtml/releases/tag/2005150002001) created with cherry picks #28404, #28423, #28441 
- [X] Release 2005150002001 promoted to Experimental and Beta channels (May 28, 2020, 1:53:38 PM GMT-7)
- [x] Release 2005150002001 promoted to Stable channel (May 29, 2020, 12:59:49 PM GMT-7
)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by cramforce** [comment]
I rolled back the release due to #28441 missing this release.

**Comment by cramforce** [comment]
When rolling forward, please verify that no other cherry-picks were missing from the release.

**Comment by powerivq** [comment]
Verified that all cherry picks of the week have been in. Two issues found by QA are verified to be existing issues.
