### ISSUE TITLE
🚄 Release tracking issue for release 2005220120000

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#28590]
# Release tracking issue

This issue tracks release `[2005220120000](https://github.com/ampproject/amphtml/releases/tag/2005220120000)`

- [x] Release 2005220120000 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [x] Release 2005220120000 promoted to Experimental and Beta (1% traffic) channels (by @newmuis on June 2, 2020, 6:39:06 PM GMT-4)
- [x] Release 2005220120000 promoted to Stable channel (June 4, 2020, 6:47:17 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
