### ISSUE TITLE
🚄 Release tracking issue for release 2005272217000

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#28685]
# Release tracking issue

This issue tracks release [2005272217000](https://github.com/ampproject/amphtml/releases/tag/2005272217000)

- [x] Release 2005272217000 promoted to Experimental and Beta (opt-in) channels (June 3, 2020, 4:15:51 PM GMT-4)
- [x] Release 2005272217000 promoted to Experimental and Beta (1% traffic) channels (June 4, 2020, 1:02:32 PM GMT-4)
- [x] Release 2005272217000 promoted to Stable channel (June 9, 2020, 2:29:47 PM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
