### ISSUE TITLE
🚄 Release tracking issue for release 2006050512000

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#28789]
# Release tracking issue

This issue tracks release [2006050512000](https://github.com/ampproject/amphtml/releases/tag/2006050512000)

- [x] Release 2006050512000 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [x] Release 2006050512000 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [x] Release 2006050512000 promoted to Stable channel (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
