### ISSUE TITLE
🚄 Release tracking issue for release 2006112352000

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#28910]
# Release tracking issue

This issue tracks release [2006112352000](https://github.com/ampproject/amphtml/releases/tag/2006112352000)

- [x] Release 2006112352000 promoted to Experimental and Beta (opt-in) channels (June 16, 2020, 3:06:31 PM GMT-7)
- [x] Release 2006112352000 promoted to Experimental and Beta (1% traffic) channels (June 18, 2020, 11:09:58 AM GMT-7)
- [x] Release [2006112352001](https://github.com/ampproject/amphtml/releases/tag/2006112352001) created with cherry picks #28981
- [x] Release 2006112352001 promoted to Experimental and Beta channels (2020-06-23 11:53 -04:00)
- [x] Release 2006112352001 promoted to Stable channel (June 23, 2020, 5:17:07 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by cramforce** [comment]
@rsimha I think PRs in this release haven't been marked as part of the stable channel.

I suppose this is because https://github.com/ampproject/amphtml/releases/tag/2006112352000 wasn't marked as stable?

**Comment by rsimha** [comment]
I see that the original release [2006230309000](https://github.com/ampproject/amphtml/releases/tag/2006112352000) didn't make it past nightly. However, release [2006112352001](https://github.com/ampproject/amphtml/releases/2006112352001) with a cherry-pick did make it to stable yesterday.

I'd have expected the PRs to get tagged when the second release got promoted, but am not sure if this is indeed the current behavior. @estherkim or @danielrozenberg can shed light on this.

**Comment by jridgewell** [comment]
[2006112352001](https://github.com/ampproject/amphtml/releases/2006112352001) is marked as "latest release". @rsimha, did you have to manually mark it? Or did the release process do it automatically?

**Comment by rsimha** [comment]
> [2006112352001](https://github.com/ampproject/amphtml/releases/2006112352001) is marked as "latest release". @rsimha, did you have to manually mark it? Or did the release process do it automatically?

Release automation does it during promotion to stable channel.
