### ISSUE TITLE
🚄 Release tracking issue for release 2006180239000

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#29007]
# Release tracking issue

This issue tracks release [2006180239000](https://github.com/ampproject/amphtml/releases/tag/2006180239000)

- [x] Release 2006180239000 promoted to Experimental and Beta (opt-in) channels (June 24, 2020, 12:32:31 PM GMT-4)
- [x] Release 2006180239000 promoted to Experimental and Beta (1% traffic) channels (June 24, 2020, 4:47:46 PM GMT-4)
- [x] Release [2006180239002](https://github.com/ampproject/amphtml/releases/tag/2006180239002) created with cherry picks #29044, #29051
- [x] Release 2006180239002 promoted to Experimental and Beta (opt-in) channels (June 25, 2020, 11:47:16 PM GMT-4)
- [x] Release 2006180239002 promoted to Experimental and Beta channels (June 25, 2020, 11:47:16 PM GMT-4)
- [x] Release 2006180239002 promoted to Stable channel (July 7, 2020, 12:35:56 PM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by cramforce** [comment]
@rsimha How do I find out which commits are in this release?

**Comment by rsimha** [comment]
> @rsimha How do I find out which commits are in this release?

As of this moment, 2006180239000 is a nightly channel release that hasn’t yet gone to opt-in or “1%” beta. The commit log can be determined by comparing the tag with the tag of the previous nightly channel release. 

https://github.com/ampproject/amphtml/compare/2006170435000...2006180239000

When a tag is promoted to opt-in, we re-publish its release with a full list of commits. This was a recent change to make the release page less repetitive / confusing. 

Would it help if we included the tag-comparison link in nightly releases?

/cc @estherkim @danielrozenberg to keep me honest.

**Comment by cramforce** [comment]
Yeah, it'd be good if we auto-generated these links in the right places.

**Comment by cramforce** [comment]
Actually, I don't think the link above is right. We should get commits between the correct nightly and the previous stable.

**Comment by wassgha** [comment]
Promoted to stable.
