### ISSUE TITLE
🚄 Release tracking issue for release 2007040248000

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#29171]
# Release tracking issue

This issue tracks release [2007040248000](https://github.com/ampproject/amphtml/releases/tag/2007040248000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2006180239002...2007040248000).

- [x] Release 2007040248000 promoted to Experimental and Beta (opt-in) channels (July 7, 2020, 1:20:39 PM GMT-7)
- [x] Release 2007040248000 promoted to Experimental and Beta (1% traffic) channels (July 8, 2020, 12:08:58 PM GMT-7)
- [x] Release [2007040248001](https://github.com/ampproject/amphtml/releases/tag/2007040248001) created with cherry picks #2007040248001
- [x] Release 2007040248001 promoted to Experimental and Beta channels (July 10, 2020, 2:29:12 PM GMT-7)
- [x] Release 2007040248001 promoted to Stable channel (2020-07-14 13:57 -07:00)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by lannka** [comment]
Seems this was in prod already. Closing
