### ISSUE TITLE
[amp-timeago:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#29246]
## High-level requirements
| Consideration  | Ready when | Status |
| ------------- | ------------- | ------- |
| Component compatibility | [Conformance with 0.1 (see below)](https://amp.dev/documentation/components/amp-timeago/) | ✅ |
| Testing | Unit tests | ✅ |
| Internationalization | `locale` supported | ✅ |
| Analytics | n/a | n/a |
| Accessibility | Audit performed, [0.1 for reference](https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+label%3A%22UI%3A+Component%3A+amp-timeago%22+label%3A%22Related+to%3A+Accessibility%22) |✅  |
| Page experience | Audit performed, [0.1 for reference](https://github.com/ampproject/amphtml/issues/27229) |✅ |
| Documentation | Written |✅  |
| Storybook | Samples written | ✅ |

## Component compatibility
Attributes to support: 
- [x] `datetime` 
- [x] `locale`
- [x] `cutoff`

`amp-bind` considerations:
- [x] `[datetime]`

## Open tasks

- [x] Discuss content-as-fallback strategy and use of `passthrough` -- make sure this is mutable
- [x] Preact unit tests
- [x] Consider auto-refreshing behavior
- [x] Decide shadow vs light dom
- [x] Look into flaky tests, currently skipped in https://github.com/ampproject/amphtml/pull/30181
