### ISSUE TITLE
🚄 Release tracking issue for release 2007172306000

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#29429]
# Release tracking issue

This issue tracks release [2007172306000](https://github.com/ampproject/amphtml/releases/tag/2007172306000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2007102309001...2007172306000).

- [x] Release 2007172306000 promoted to Experimental and Beta (opt-in) channels (2020-07-21 17:01 -07:00)
- [x] Release 2007172306000 promoted to Experimental and Beta (1% traffic) channels (2020-07-22 16:44 -07:00)
- [x] Release [2007172306001](https://github.com/ampproject/amphtml/releases/tag/2007172306001) created with cherry picks #29475
- [x] Release 2007172306001 promoted to Experimental and Beta channels (2020-07-23 18:49 -07:00)
- [x] Release [2007172306003](https://github.com/ampproject/amphtml/releases/tag/2007172306003) created with cherry picks #29528 and #29493 
- [x] Release 2007172306003 promoted to Experimental and Beta channels (2020-07-27 18:38 -07:00)
- [x] Release 2007172306003 promoted to Stable channel (2020-07-29 11:34 -04:00)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by rcebulko** [comment]
This release has reached Stable and will not go on to become LTS, so I'm closing this tracking issue now.
