### ISSUE TITLE
🚄 Release tracking issue for release 2007102309001

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#29428]
# Release tracking issue

This issue tracks release [2007102309001](https://github.com/ampproject/amphtml/releases/tag/2007102309001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2007040248002...2007102309001).

- [x] Release 2007102309001 promoted to Experimental and Beta (opt-in) channels (July 15, 2020, 8:22:45 AM GMT-4)
- [x] Release 2007102309001 promoted to Experimental and Beta (1% traffic) channels (July 15, 2020, 4:13:34 PM GMT-4)
- [x] Release 2007102309001 promoted to Stable channel (2020-07-21 16:52 -07:00)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by lannka** [comment]
Promoted to stable
