### ISSUE TITLE
🚄 Release tracking issue for release 2007242032001

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#29539]
# Release tracking issue

This issue tracks release [2007242032001](https://github.com/ampproject/amphtml/releases/tag/2007242032001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2007172306003...2007242032001).

- [x] Release 2007242032001 built from Nightly with cherry-picks: #29475  (July 28, 2020, 5:28 PM GMT-4)
- [x] Release 2007242032001 promoted to Experimental and Beta (opt-in) channels (July 28, 2020, 7:04 PM GMT -4)
- [x] Release 2007242032001 promoted to Experimental and Beta (1% traffic) channels (July 29, 2020, 5:29:13 PM GMT-4)
- [x] Release 2007242032001 promoted to Stable channel (August 4, 2020, 5:14:35 PM GMT-4)
- [x] Release [2007242032002](https://github.com/ampproject/amphtml/releases/tag/2007242032002) created with cherry pick #29697
- [x] Release 2007242032002 promoted to Stable channel (August 6, 2020, 2:27:33 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment]
Closing, now that https://github.com/ampproject/amphtml/releases/2007242032001 has made it to Stable channel.

**Comment by rsimha** [comment]
Reopening because of the CP.

**Comment by rsimha** [comment]
New stable with CP has been released: https://github.com/ampproject/amphtml/releases/tag/2007242032002

**Comment by calebcordry** [comment]
Reopened for another CP.

**Comment by calebcordry** [comment]
We decided not to do additional cherry picks to this version.
