### ISSUE TITLE
🚄 Release tracking issue for release 2007302351000

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#29725]
# Release tracking issue

This issue tracks release [2007302351000](https://github.com/ampproject/amphtml/releases/tag/2007302351000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2007242032001...2007302351000).

- [x] Release 2007302351000 promoted to Experimental and Beta (opt-in) channels (August 4, 2020, 5:49:58 PM GMT-4)
- [x] Release 2007302351000 promoted to Experimental and Beta (1% traffic) channels (August 5, 2020, 5:38:29 PM GMT-4)
- [x] Release [2007302351001](https://github.com/ampproject/amphtml/releases/tag/2007302351001) created with cherry pick #29697
- [x] Release 2007302351001 promoted to Experimental and Beta channels (August 6, 2020, 2:27:16 PM GMT-4, August 6, 2020, 2:38:17 PM GMT-4)
- [x] Release 2007302351001 promoted to Stable channel (August 12, 2020, 11:33:49 AM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
