### ISSUE TITLE
🚄 Release tracking issue for release 2008150009001

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#29879]
# Release tracking issue

This issue tracks release [2008150009001](https://github.com/ampproject/amphtml/releases/tag/2008150009001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2008072132003...2008150009001).

- [x] Release 2008150009001 promoted to Experimental and Beta (opt-in) channels (August 18, 2020, 2:54:00 PM GMT-4)
- [x] Release 2008150009001 promoted to Experimental and Beta (1% traffic) channels (August 21, 2020, 1:47:10 PM GMT-4)
- [x] Release 2008150009001 promoted to Stable channel (August 27, 2020. 10:46:22 AM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment]
_[Cleaning up old Release issues]_
