### ISSUE TITLE
🚄 Release tracking issue for release 2008220050000

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#30012]
# Release tracking issue

This issue tracks release [2008220050000](https://github.com/ampproject/amphtml/releases/tag/2008220050000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2008150009001...2008220050000).

- [x] Release 2008220050000 promoted to Experimental and Beta (opt-in) channels (August 27, 2020. 1:45 PT)
- [x] Release 2008220050000 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [x] Release [30057](https://github.com/ampproject/amphtml/releases/tag/2008220050001) created with cherry picks #30057
- [x] Release 2008220050001 promoted to percentage Experimental and Beta channels (August 31, 2020, 5:10:36 PM GMT-7)
- [x] Release 2008220050001 promoted to Stable (September 2, 2020, 10:35:27 AM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
