### ISSUE TITLE
[amp-story-player] [master tracker] UI Custom Controls API

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#30031]
We should allow publishers to specify icons and their corresponding events to be dispatched. We should also allow some basic customization like vertical (header/footer) and horizontal (start/end) placement. See https://github.com/ampproject/amphtml/issues/30031#issuecomment-685842504 for more details on the API.

Work plan:

- [x] Consume JSON configuration from player (PR: #30500)
- [x] Send a message from player to story with desired configuration (PR: #30501) (API spec: #30588)
- [x] From the story side, build the system layer with desired configuration. (PR: #30502)
    - [x] Fix pagination buttons for pre-rendered documents bug. (PR: #30503)
    - [x] Validate configuration (limit amount of icons - mobile and desktop have different limits).
            
    - [x] Add click listeners that sends message back to player for those buttons that are appropiate. (PR #30745)
- [x] Listen to messages from player side and perform corresponding action (skip next story in desktop, dispatch custom event, etc..) (PR: #30745) (API Spec: #30588)

Button-specific:
- [x] Skip button: disable when there are no next stories. (PR #30745)
- [x] Close button: always position at start/end of other icons .(PR: #30502)

![image](https://user-images.githubusercontent.com/5449100/94170842-8df13e80-fe5e-11ea-85b2-639561cf5164.png)

**Comment by Enriqe** [comment]
Here is how the finalized API would look like:

```
    {
      "header": { // (Optional)
        "position": "end", // Values: "start" or "end".
        "buttons": [ // Required.
          {
            "name": "mute", // If name is part of default set, the default behavior and icon will be used.
            "icon": "icon.jpg",  // Supports URLS and `data:image` URIs like base64 images and svgs.
          },
          {
            "name": "close",
          },
          {
            "name": "customButton", // If not part of default set, the following fields will be required.
            "icon": "data:image/svg+xml;charset=utf-8,<svg ... ", 
            "event": "customEvent", // Event that will be dispatched when clicked.
          }
        ]
      },
      "footer": { // (Optional)
        position: "start", // Same fields and rules as header apply to footer.
        ...
      }
    }
```

For the initial version, we will only allow up to 3 buttons, either on the left (start) or right (end) for the footer and header (so 6 max in total). Any other buttons would be discarded.

**Comment by newmuis** [comment]
Looks good!  We need semantics to avoid name collisions on the buttons (e.g. `amp-mute` instead of `mute`).  Otherwise we can't add new default buttons or we might break someone that was using that.... Right?

Or will the `icon` and `event` even override default buttons?

**Comment by Enriqe** [comment]
The idea is that `icon` and `event` are optional if part of the default set, but overridable if desired. So if publisherX is using a `buttonX` with their own `icon` and `event`, and we later introduce `buttonX` as part of the default set, we will still respect the pubisherX's `icon` and `event`, because it overrides the default behavior. Does this sound good to you? @newmuis @gmajoulet

**Comment by newmuis** [comment]
Thanks for clarifying!

**Comment by Enriqe** [comment]
All main tasks have been finished. Remaining items are:

- Deleting previous `exit-control` API.
- Writing documentation.

Will file separate issues for those.
