### ISSUE TITLE
🚄 Release tracking issue for release 2008290323001

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#30086]
# Release tracking issue

This issue tracks release [2008290323001](https://github.com/ampproject/amphtml/releases/tag/2008290323001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2008220050001...2008290323001).

- [x] Release 2008290323001 promoted to Experimental and Beta (opt-in) channels (September 2, 2020, 11:21:23 AM GMT-7)
- [x] Release 2008290323001 promoted to Experimental and Beta (1% traffic) channels (September 3, 2020, 11:07:59 AM GMT-7)
- [x] Release 2008290323001 promoted to Stable channel (September 8, 2020, 5:56:10 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
