### ISSUE TITLE
🚄 Release tracking issue for release 2009040024000

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#30147]
# Release tracking issue

This issue tracks release [2009040024000](https://github.com/ampproject/amphtml/releases/tag/2009040024000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2008220050001...2009040024000).

- [x] Release 2009040024000 promoted to Experimental and Beta (opt-in) channels (September 8, 2020, 11:15:18 AM GMT-4)
- [x] Release 2009040024000 promoted to Experimental and Beta (1% traffic) channels (September 9, 2020, 4:39:10 PM GMT-4)
- [x] Release [2009040024001](https://github.com/ampproject/amphtml/releases/tag/2009040024001) created with cherry pick #30175
- [x] Release 2009040024001 promoted to Experimental and Beta (opt-in) channels (September 9, 2020, 8:28:58 PM GMT-4)
- [x] Release 2009040024001 promoted to Experimental and Beta (1% traffic) channels (September 9, 2020, 8:22:04 PM GMT-4)
- [x] Release 2009040024001 promoted to Stable channel (September 15, 2020, 12:54:49 PM GMT-7
)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
