### ISSUE TITLE
[amp-date-display:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#30189]
Open tasks:

- [x] Resolve the fake container
- [x] Fix wrapper
- [x] Simplify template integration
- [x] Share more "epoch" code and mapping with `amp-timeago` and `amp-date-countdown`.
- [x] Decide on the wrapper: should it be a `<div>`, a `<span>`, direct `render()` result, and/or customizable?
