### ISSUE TITLE
Video in Bento tracker

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#30330]
- [x] `VideoWrapper`: Base #29486
- [ ] `VideoWrapper`: Clear MediaSession from `useLayoutEffect`.
- [x] `VideoWrapper`: Use JSS for autoplay icon. #30298
- [ ] `VideoWrapper`: Better concept for `userInteracted`. It's either:
      - a prop (what's it named?)
      - internal state (what's it named?)
      - (is it just toggling `autoplay`?)
- [ ] `VideoWrapper`: rotate-to-fullscreen (per item or per page?)
---
- [ ] `VideoDock`: @alanorozco to flesh this out
---
- [ ] `amp-video`: Base #30280
- [ ] `amp-video`: placeholder?
- [ ] `amp-video`: Android bug first frame hack? (is this still an issue?)
- [ ] `amp-video`: propagate cached sources
- [ ] `amp-video`: HLS decode error fallback
---
- [ ] `amp-video-iframe`: Base
- [ ] `amp-video-iframe`: `postIntersection` (single-use `IntersectionObserver`)
---
- [ ] `amp-youtube`: Base
- [ ] `amp-youtube`: `sendCommand`
- [ ] `amp-youtube`: placeholder?
