### ISSUE TITLE
🚄 Release tracking issue for release 2009190410000

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#30436]
# Release tracking issue

This issue tracks release [2009190410000](https://github.com/ampproject/amphtml/releases/tag/2009190410000). See what's new compared to stable `[here](https://github.com/ampproject/amphtml/compare/2009112034002... 2009190410000)`.

- [x] Release 2009190410000 promoted to Experimental and Beta (opt-in) channels (September 23, 2020, 10:49:47 AM GMT-7
)
- [x] Release 2009190410000 promoted to Experimental and Beta (1% traffic) channels (September 23, 2020, 1:38:48 PM GMT-7
)
- [x] Release 2009190410000 promoted to Stable channel (September 29, 2020, 10:27:48 AM GMT-7
)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
