### ISSUE TITLE
🚄 Release tracking issue for release 2009252320001

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#30435]
# Release tracking issue

This issue tracks release [2009252320001](https://github.com/ampproject/amphtml/releases/tag/2009252320001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2009190410000...2009252320001).

- [x] Release 2009252320000 promoted to Experimental and Beta (opt-in) channels (
September 29, 2020, 1:26:16 PM GMT-4)
- [x] Release [2009252320001](https://github.com/ampproject/amphtml/releases/tag/2009252320001) created with cherry picks #30453
- [x] Release 2009252320001 promoted to Experimental and Beta (1% traffic) channels (September 30, 2020, 2:49:30 PM GMT-4)
- [x] Release 2009252320001 promoted to Stable channel (October 6, 2020, 6:12:45 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
