### ISSUE TITLE
[amp-accordion:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#30445]
Open tasks:

- [x] Initial component/element binding - https://github.com/ampproject/amphtml/pull/30446/
- [x] animated collapse/expand - #30543
- [x] default CSS: port from 0.1 - https://github.com/ampproject/amphtml/pull/30622
- [x] porting pass with a11y (`tabindex`, etc) - https://github.com/ampproject/amphtml/pull/30644
- [x] move aria-expanded from `section` to `header` - https://github.com/ampproject/amphtml/pull/30721
- [x] imperative APIs (including AMP) - https://github.com/ampproject/amphtml/pull/30754
- [x] Confirm Binder support works. Including, confirm that `data-expand` is no longer needed. - https://github.com/ampproject/amphtml/pull/30894
- [x] Firing events - https://github.com/ampproject/amphtml/pull/30976
- [x] Order of firing events look into this (i.e. expand-single-section) only 1 event fire (addressed in item above)
- [x] restructure Accordion [Doc](https://docs.google.com/document/d/1L5jG0Z81BX-ESs003qvFFVYSEWFZYIgKYrxfKrvXB8U/edit#) - https://github.com/ampproject/amphtml/pull/31083
- [x] handle protect existing `id` on content node - https://github.com/ampproject/amphtml/pull/31136
- [x] Ensure no a11y conflicts from restructure https://github.com/ampproject/amphtml/pull/31083#discussion_r521692395 - https://github.com/ampproject/amphtml/pull/31136
- [x] display locking - https://github.com/ampproject/amphtml/pull/31227
- [x] Update CSS if team decides to change default CSS (so far sounds like not)
- [x] Add `aria-labelledby` attributes to content. - #31136
- [x] ~Explore porting visual tests from `0.1` as opposed to testing css in unit tests~
- [x] Per issue https://github.com/ampproject/amphtml/issues/32549, respect role attributes if they already exist on header or content sections. https://github.com/ampproject/amphtml/pull/32915
- [x] Add validator for 1.0 https://github.com/ampproject/amphtml/pull/33493
   - [x] Update 0.1 to be compatible with validator changes https://github.com/ampproject/amphtml/pull/33828
   - [x] Update documentation https://github.com/ampproject/amphtml/pull/33494

To dos:

PRs:
Component Outline - https://github.com/ampproject/amphtml/pull/30446
Animations - https://github.com/ampproject/amphtml/pull/30543
