### ISSUE TITLE
[amp-youtube:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by realPrimoh** [ampproject/amphtml#30443]
Design doc: https://docs.google.com/document/d/1PaQZyQw1HEi5G-B6DW0uO-UG53rkBqmQ5WLyEfQTKrI/edit?usp=sharing

TODO:
- [x] Implement imperative API
- [x] Address `currentTime` state var
- [x] ~Address `dock` prop~

Complete:
- [x] Complete general prototype of extension
- [x] Complete design doc
- [x] Write unit tests
