### ISSUE TITLE
🚄 Release tracking issue for release 2010010034000

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#30542]
# Release tracking issue

This issue tracks release [2010010034000](https://github.com/ampproject/amphtml/releases/tag/2010010034000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2008290323006...2010010034000).

- [x] Release 2010010034000 promoted to Experimental and Beta (opt-in) channels (October 7, 2020, 5:03:42 PM GMT-4)
- [x] Release 2010010034000 promoted to Experimental and Beta (1% traffic) channels (October 8, 2020, 10:09:10 AM GMT-4)
- [ ] Release 2010010034000 promoted to Stable channel (<CL submit time>)
- [x] Release 2010010034001 promoted to to Experimental and Beta (opt-in) channels (October 12, 2020, 4:17:52 PM GMT-7)
- [x] Release 2010010034001 promoted to to Experimental and Beta (1% traffic) channels (October 12, 2020, 4:31:57 PM GMT-7)
- [x] Release 2010010034001 promoted to Stable channel (October 13, 2020, 12:40:31 PM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
