### ISSUE TITLE
🚄 Release tracking issue for release 2010122315000

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#30741]
# Release tracking issue

This issue tracks release [2010122315000](https://github.com/ampproject/amphtml/releases/tag/2010122315000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2010010034001...2010122315000 ).

- [x] Release 2010122315000 promoted to Experimental and Beta (opt-in) channels (October 14, 2020, 5:26:46 AM GMT-7)
- [x] Release 2010122315000 promoted to Experimental and Beta (1% traffic) channels (October 14, 2020, 10:30:50 AM GMT-7)
- [x] Release [2010132225001](https://github.com/ampproject/amphtml/releases/tag/2010132225001) created with cherry pick #30730 
- [x] Release 2010122315001 promoted to Experimental and Beta (opt-in) channels (October 19, 2020, 9:14:28 PM GMT-4)
- [x] Release 2010122315001 promoted to Experimental and Beta (1% traffic) channels (October 19, 2020, 8:34:56 PM GMT-4)
- [x] Release 2010132225001 promoted to Stable channel (October 20, 2020, 4:30:22 PM GMT-4)
- [x] Release 2010132225001 rolled back from Stable channel, returning to 2010010034001 as Stable in the interim (October 21, 2020, 11:06:31 AM GMT-4)
- [x] Release [2010132225002](https://github.com/ampproject/amphtml/releases/tag/2010132225002) created with cherry pick #30805 
- [x] Release 2010122315002 promoted to Experimental and Beta (1% traffic) channels (October 21, 2020, 7:54:24 PM GMT-4)
- [x] Release 2010132225002 promoted to Stable channel (
October 21, 2020, 7:58:03 PM GMT-4)
- [x] Release [2010132225003](https://github.com/ampproject/amphtml/releases/tag/2010132225003) created with cherry pick #30909 
- [x] Release 2010132225003 promoted to Stable channel (2020-10-29 17:22 -04:00)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment]
_[Cleaning up old Release issues]_
