### ISSUE TITLE
🚄 Release tracking issue for release 2010162313001

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#30770]
# Release tracking issue

This issue tracks release [2010162313001](https://github.com/ampproject/amphtml/releases/tag/2010162313001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2010122315000...2010162313001).

- [x] Release 2010162313001 promoted to Experimental and Beta (opt-in) channels (October 20, 2020, 3:36:41 PM GMT-4)
- [x] Release [2010162313002](https://github.com/ampproject/amphtml/releases/tag/2010162313002) created with cherry pick #30805
- [x] Release 2010162313002 promoted to Experimental and Beta (opt-in) channels (October 21, 2020, 8:20:01 PM GMT-4)
- [x] Release 2010162313002 promoted to Experimental and Beta (1% traffic) channels (October 22, 2020, 11:39:10 AM GMT-4)
- [ ] ~Release 2010162313002 promoted to Stable channel (<CL submit time>)~ (Release freeze due to election)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment]
_[Cleaning up old Release issues]_
