### ISSUE TITLE
🚄 Release tracking issue for release 2010302236001

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#30974]
# Release tracking issue

This issue tracks release [2010302236000](https://github.com/ampproject/amphtml/releases/tag/2010302236000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2010132225003...2010302236000).

- [x] Release 2010302236000 promoted to Experimental and Beta (opt-in) channels (November 3, 2020, 8:38:49 AM GMT-8)
- [x] Release 2010302236000 promoted to Experimental and Beta (1% traffic) channels (November 4, 2020, 7:50:09 AM GMT-8)
- [x] Release [2010302236001](https://github.com/ampproject/amphtml/releases/tag/2010302236001) created with cherry pick #31004
- [x] Release 2010302236001 promoted to Experimental and Beta (opt-in) channels (November 5, 2020, 2:41:42 PM GMT-8)
- [x] Release 2010302236001 promoted to Experimental and Beta (1% traffic) channels (November 5, 2020, 2:32:49 PM GMT-8)
- [x] Release 2010302236001 promoted to Stable channel (November 11, 2020, 8:37:10 AM GMT-8)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
