### ISSUE TITLE
[amp-lightbox:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by realPrimoh** [ampproject/amphtml#31052]
## High-level requirements
| Consideration  | Ready when | Status |
| ------------- | ------------- | ------- |
| Component compatibility | [Conformance with 0.1 (see below)](https://amp.dev/documentation/components/amp-lightbox) | ✅  |
| Testing | Unit tests and e2e tests from 0.1 | ✅  |
| Internationalization | n/a | n/a |
| Analytics | n/a | n/a |
| Accessibility | Audit performed, [0.1 for reference](https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+label%3A%22UI%3A+Component%3A+amp-lightbox%22+label%3A%22Related+to%3A+Accessibility%22) |✅|
| Page experience | Audit performed |✅|
| Documentation | Written |✅ |
| Storybook | Samples written | ✅ |

## Component compatibility
Attributes to support: 
- [x] `animate-in` -> `animation` (optional)
- [x] ~`data-close-button-aria-label` (optional)~
- [x] ~`scrollable` (optional)~

### Migration Notes:

- This component does not currently support modifying browser history state.
- `data-close-button-aria-label` is not supported and will soon be replaced with support for `slot="close-button"`.
- `animate-in` has been renamed to `animation`

## Open tasks:

- [x] Unit tests
- [x] Address `scrollable` prop (is it still necessary? not added for now)
- [x] Send out events upon open/close or let users pass in a function
- [x] Modify history state (conformance to 0.1) - AMP only
- [x] Support `slot="close-button"` once `passthrough` and `children` modes are refactored
- [x] Add validations to include no-longer-supported attributes for backwards compatibility
- [x] Cancellable backdrop
