### ISSUE TITLE
🚄 Release tracking issue for release 2011070101000

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#31085]
# Release tracking issue

This issue tracks release [2011070101000](https://github.com/ampproject/amphtml/releases/tag/2011070101000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2010302236001...2011070101000).

- [x] Release 2011070101000 promoted to Experimental and Beta (opt-in) channels (November 11, 2020, 9:05:51 AM GMT-8)
- [x] Release [2011070101001](https://github.com/ampproject/amphtml/releases/tag/2011070101001) created with cherry picks #31130
- [x] Release 2011070101001 promoted to Experimental and Beta channels (November 13, 2020, 3:35:03 PM GMT-8)
- [x] Release 2011070101001 promoted to Experimental and Beta (1% traffic) channels (November 13, 2020, 3:33:15 PM GMT-8)
- [x] Release 2011070101001 promoted to Stable channel (November 17, 2020, 2:36:17 PM GMT-8)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
