### ISSUE TITLE
🚄 Release tracking issue for release 2011140244000

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#31228]
# Release tracking issue

This issue tracks release [2011140244000](https://github.com/ampproject/amphtml/releases/tag/2011140244000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2010302236002...2011140244000).

- [x] Release [2011140244000](https://github.com/ampproject/amphtml/releases/tag/2011140244000) promoted to Experimental and Beta (opt-in) channels (November 17, 2020, 4:28:28 PM GMT-5)
- [x] Release [2011140244001](https://github.com/ampproject/amphtml/releases/tag/2011140244001) created with cherry pick #31203 
- [x] Release 2011140244001 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [x] Release [2011140244002](https://github.com/ampproject/amphtml/releases/tag/2011140244002) created with cherry pick #31203 
- [x] Release 2011140244002 promoted to Experimental and Beta (opt-in) channels (November 18, 2020, 1:53:53 PM GMT-5)
- [x] Release 2011140244002 promoted to Experimental and Beta (1% traffic) channels (November 19, 2020, 12:16:56 PM GMT-5)
- [ ] ~Release 2011140244002 promoted to Stable channel (<CL submit time>)~ _AMP is on a release freeze, only Beta/Experimental releases will be performed on the week of November 23, 2020_

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
