### ISSUE TITLE
🚄 Release tracking issue for release 2011200012000

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#31314]
# Release tracking issue

This issue tracks release [2011200012000](https://github.com/ampproject/amphtml/releases/tag/2011200012000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2011070101001...2011200012000).

- [x] Release 2011200012000 promoted to Experimental and Beta (opt-in) channels (November 24, 2020, 12:29:35 PM GMT-5)
- [x] Release 2011200012000 promoted to Experimental and Beta (1% traffic) channels (November 25, 2020, 12:06:37 PM GMT-5)
- [x] Release 2011200012000 promoted to Stable channel (December 1, 2020, 1:38:27 PM GMT-5)

- [x] Release [2011200012001](https://github.com/ampproject/amphtml/releases/tag/2011200012001) created with cherry pick #31374
- [x] Release 2011200012001 promoted to Stable channel (December 1, 2020, 6:33:02 PM GMT-5)
- [x] Release 2011200012001 promoted to Experimental and Beta channels (December 1, 2020, 6:23:57 PM GMT-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
