### ISSUE TITLE
🚄 Release tracking issue for release 2011252111002

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#31369]
# Release tracking issue

This issue tracks release [2011252111000](https://github.com/ampproject/amphtml/releases/tag/2011252111000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2011200012000...2011252111000).

- [x] Release 2011252111000 promoted to Experimental and Beta (opt-in) channels (December 1, 2020, 2:53:17 PM GMT-5)
- [x] Release [2011252111001](https://github.com/ampproject/amphtml/releases/tag/2011252111001) created with cherry pick #31374
- [x] Release 2011252111001 promoted to Experimental and Beta (opt-in) channels (December 1, 2020, 6:39:54 PM GMT-5)
- [x] Release 2011252111001 promoted to Experimental and Beta (1% traffic) channels (December 2, 2020, 11:38:23 AM GMT-5)
- [x] Release 2011252111001 promoted to Stable channel (December 8, 2020, 2:41:22 PM GMT-5)
- [x] Release [2011252111002](https://github.com/ampproject/amphtml/releases/tag/2011252111002) created with cherry pick #31516
- [x] Release 2011252111002 promoted to Stable channel (December 9, 2020, 3:37:07 PM GMT-5)
- [x] Release 2011252111002 promoted to LTS channel (December 14, 2020, 1:21:20 PM GMT-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
