### ISSUE TITLE
🚄 Release tracking issue for release 2012050452002

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#31501]
# Release tracking issue

This issue tracks release [2012050452000](https://github.com/ampproject/amphtml/releases/tag/2012050452000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2011252111001...2012050452000).

- [x] Release 2012050452000 promoted to Experimental and Beta (opt-in) channels (December 8, 2020, 2:59:32 PM GMT-5)
- [x] Release [2012050452001](https://github.com/ampproject/amphtml/releases/tag/2012050452001) created with cherry pick #31509
- [x] Release 2012050452001 promoted to Experimental and Beta (opt-in) channels (December 8, 2020, 11:20:17 PM GMT-5)
- [x] Release [2012050452002](https://github.com/ampproject/amphtml/releases/tag/2012050452002) created with cherry pick #31516
- [x] Release 2012050452002 promoted to Experimental and Beta (opt-in) channels (December 9, 2020, 4:11:56 PM GMT-5)
- [x] Release 2012050452002 promoted to Experimental and Beta (1% traffic) channels (December 10, 2020, 3:39:01 PM GMT-5)
- [ ] Release 2012050452002 promoted to Stable channel (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
