### ISSUE TITLE
🚄 Release tracking issue for release 2012112254000

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#31617]
# Release tracking issue

This issue tracks release [2012112254000](https://github.com/ampproject/amphtml/releases/tag/2012112254000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2012050452002...2012112254000).

- [x] Release 2012112254000 promoted to Experimental and Beta (opt-in) channels (December 15, 2020, 7:38:38 PM GMT-5)
- [x] Release 2012112254000 promoted to Experimental and Beta (1% traffic) channels (December 17, 2020, 3:04:08 PM GMT-5)
- [ ] Release 2012112254000 promoted to Stable channel (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
