### ISSUE TITLE
🚄 Release tracking issue for release 2012232217000

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#31763]
# Release tracking issue

This issue tracks release [2012232217000](https://github.com/ampproject/amphtml/releases/tag/2012232217000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2011252111003...2012232217000).

- [x] Release 2012232217000 promoted to Experimental and Beta (opt-in) channels (December 29, 2020, 9:15:36 AM GMT-8)
- [x] Release 2012232217000 promoted to Experimental and Beta (1% traffic) channels (December 30, 2020, 11:43:45 AM GMT-8)
- [x] Release 2012232217000 promoted to Stable channel (<CL submit time>)
- [x] Release 2012232217000 promoted to LTS (January 13, 2021, 10:37:10 AM GMT-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
