### ISSUE TITLE
🚄 Release tracking issue for release 2012301722000

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#31929]
# Release tracking issue

This issue tracks release [2012301722000](https://github.com/ampproject/amphtml/releases/tag/2012301722000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2012292327000...2012301722000).

- [x] Release 2012301722000 promoted to Experimental and Beta (opt-in) channels (January 8, 2021, 2:19:08 PM GMT-5)
- [x] Release 2012301722000 promoted to Experimental and Beta (1% traffic) channels (January 7, 2021, 1:40:07 PM GMT-5)
- [x] Release 2012301722000 promoted to Stable channel (January 13, 2021, 9:54:57 AM GMT-5)
- [x] Release [2012301722001](https://github.com/ampproject/amphtml/releases/tag/2012301722001) created with cherry picks #31921
- [x] Release [2101152047000](https://github.com/ampproject/amphtml/releases/tag/2101152047000) created with cherry picks #31980 #31989 (January 20, 2021, 12:17:09 PM GMT-5)
- [x] Release [2101212155000](https://github.com/ampproject/amphtml/releases/tag/2101152047001) created with cherry picks (https://github.com/ampproject/amphtml/pull/32087) (7:28 PM, Jan 21, 2021 UTC-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by Enriqe** [comment]
Yep, that's right.
