### ISSUE TITLE
🚄 Release tracking issue for release 2101090132000

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#31930]
# Release tracking issue

This issue tracks release [2101090132000](https://github.com/ampproject/amphtml/releases/tag/2101090132000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2012301722000...2101090132000).

- [x] Release 2101090132000 promoted to Experimental and Beta (opt-in) channels (January 13, 2021, 10:47:11 AM GMT-5)
- [x] Release [2101090132001](https://github.com/ampproject/amphtml/releases/tag/2101090132001) created with cherry picks #31921
- [x] Release [2101090132003](https://github.com/ampproject/amphtml/releases/tag/2101090132003) (opt-in) created with cherry picks #31980 #31989
- [ ] Release 2101090132003 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [ ] Release 2101090132003 promoted to Stable channel (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by samouri** [comment]
Now that the relevant fixes have already landed in `master`, we are going to skip this release and instead cut a new Beta from today. Will make a new tracking issue for the new release tomorrow

**Comment by samouri** [comment]
Closing this thread/fully stopping release train in favor of: https://github.com/ampproject/amphtml/issues/32065
