### ISSUE TITLE
🚄 Release tracking issue for release 2101211748000

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#32065]
# Release tracking issue

This issue tracks release [2101211748000](https://github.com/ampproject/amphtml/releases/tag/2101211748000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2012301722001...2101211748000).

- [x] Release 2101200139000 promoted to Experimental and Beta (opt-in) channels.  -- **issues discovered**
- [x] Release 2101211748000 promoted to Experimental and Beta (opt-in) channels (4:21 PM, Jan 21, 2021 UTC-5)
- [x] Release 2101211748000 promoted to Experimental and Beta (1% traffic) channels (6:24 PM, Jan 21, 2021 UTC-5)
- [x] Release 2101211748001 created with cherry pick https://github.com/ampproject/amphtml/issues/32192
- [x] Release 2101211748001 promoted to Experimental and Beta (opt-in) channels (January 26, 2021, 3:21:20 PM GMT-5)
- [x] Release 2101211748001 promoted to Experimental and Beta (1% traffic) channels (January 26, 2021, 2:42:46 PM GMT-5)
- [x] Release 2101211748001 promoted to Stable channel (January 26, 2021, 4:19:13 PM GMT-5)
- [x] Release 2101211748002 created with cherry pick https://github.com/ampproject/amphtml/issues/32251
- [x] Release 2101211748002 promoted to Experimental and Beta (1% traffic) channels (January 27, 2021, 4:52:36 PM GMT-5)
- [x] Release 2101211748002 promoted to Stable channel (January 27, 2021, 4:50:11 PM GMT-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
