### ISSUE TITLE
🚄 Release tracking issue for release 2101230412000

### ISSUE THREAD

**Issue by krdwan** [ampproject/amphtml#32229]
# Release tracking issue

This issue tracks release [2101230412000](https://github.com/ampproject/amphtml/releases/tag/2101230412000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2101211748001...2101230412000).

- [x] Release 2101230412000 promoted to Experimental and Beta (opt-in) channels (January 26, 2021, 5:16:11 PM GMT-5)
- [x] Release 2101230412002 created with cherry picks https://github.com/ampproject/amphtml/issues/32235, https://github.com/ampproject/amphtml/issues/32251
- [x] Release 2101230412002 promoted to Experimental and Beta (opt-in) channels (January 27, 2021, 5:11:49 PM GMT-5)
- [x] Release 2101230412002 promoted to Experimental and Beta (1% traffic) channels (January 28, 2021, 11:07:56 AM GMT-5)
- [x] Release 2101230412003 created with cherry picks https://github.com/ampproject/amphtml/issues/32360
- [x] Release 2101230412003 promoted to Stable channel (February 3, 2021, 12:38:26 PM GMT-5)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
