### ISSUE TITLE
🚄 Release tracking issue for release 2101300534000

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#32408]
# Release tracking issue

This issue tracks release [2101300534005](https://github.com/ampproject/amphtml/releases/tag/2101300534005). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2101230412003...2101300534005).

- [x] Release 2101300534000 promoted to Experimental and Beta (opt-in) channels (February 3, 2021, 2:37:24 PM GMT-5)
- [x] Release 2101300534003 created with cherrypicks from https://github.com/ampproject/amphtml/issues/32463 (February 5, 2021, 5:54:46 PM GMT-5)
- [x] Release 2101300534003 promoted to Experimental and Beta (opt-in) channels (February 5, 2021, 7:04:44 PM GMT-5)
- [x] Release 2101300534003 promoted to Experimental and Beta (1% traffic) channels (February 5, 2021, 6:50:30 PM GMT-5)
- [x] Release [2101300534004](https://github.com/ampproject/amphtml/releases/2101300534004) created with cherry picks (https://github.com/ampproject/amphtml/issues/32521) 
- [x] Release 2101300534004 promoted to Experimental and Beta (1% traffic) channels (February 8, 2021, 5:05:47 PM GMT-8)
- [x] Release 2101300534004 promoted to Experimental and Beta (opt-in) channels (February 8, 2021, 5:48:04 PM GMT-8)
- [x] Release [2101300534005](https://github.com/ampproject/amphtml/releases/2101300534005) created with cherry picks (https://github.com/ampproject/amphtml/issues/32562) 
- [x] Release 2101300534005 promoted to Experimental and Beta (1% traffic) channels (February 9, 2021, 6:15:59 PM GMT-8)
- [x] Release 2101300534005 promoted to Experimental and Beta (opt-in) channels (February 9, 2021, 6:48:18 PM GMT-8)
- [x] Release 2101300534005 promoted to Stable channel (February 10, 2021, 10:09:08 AM GMT-8) 
 

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
