### ISSUE TITLE
🚄 Release tracking issue for release 2102060044001

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#32592]
# Release tracking issue

This issue tracks release [2102060044001](https://github.com/ampproject/amphtml/releases/tag/2102060044001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2101300534005...2102060044001).

- [x] Release 2102060044001 promoted to Experimental and Beta (opt-in) channels (February 10, 2021, 11:01:59 AM GMT-8)
- [x] Release 2102060044001 promoted to Experimental and Beta (1% traffic) channels (February 11, 2021, 12:13:18 PM GMT-8)
- [x] Release 2102060044001 promoted to Stable channel (February 17, 2021, 8:29:05 AM GMT-8)
- [x] Revert 2102060044001 back to 2101300534005 (February 17, 2021, 1:44:42 PM GMT-8)
- [x] Release [2102060044003](https://github.com/ampproject/amphtml/releases/tag/2102060044003) created with cherry picks #32710, #32724
- [x] Release 2102060044003 promoted to Experimental and Beta channels (February 18, 2021, 11:48:46 AM GMT-8)
- [x] Release 2102060044003 promoted to Stable channel (February 18, 2021, 12:13:29 PM GMT-8)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
