### ISSUE TITLE
🚄 Release tracking issue for release 2102130314000

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#32757]
# Release tracking issue

This issue tracks release [2102130314000](https://github.com/ampproject/amphtml/releases/tag/2102130314000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2102060044003...2102130314000).

- [x] Release [2102130314001](https://github.com/ampproject/amphtml/releases/tag/2102130314001) created with cherry picks #32724
- [x] Release 2102130314001 promoted to Experimental and Beta (opt-in) channels (2021-02-19 14:02 -05:00)
- [x] Release 2102130314001 promoted to Experimental and Beta (1% traffic) channels (2021-02-19 14:22 -05:00)
- [x] Release 2102130314001 promoted to Stable channel (2021-02-23 15:13:14 -0500)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by kristoferbaxter** [comment]
https://github.com/ampproject/amphtml/issues/32978

Looks like a regression was introduced in this version. Attempting to rollback.
