### ISSUE TITLE
[amp-lightbox-gallery:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#32759]
## High-level requirements
| Consideration  | Ready when | Status |
| ------------- | ------------- | ------- |
| Component compatibility | [Conformance with 0.1 (see below)](https://amp.dev/documentation/components/amp-lightbox-gallery/) | ✅ |
| Testing | Unit tests and e2e tests from 0.1 | ✅ |
| Internationalization | n/a | n/a |
| Analytics | [Events](https://amp.dev/documentation/components/amp-lightbox-gallery/#analytics) | ✅ |
| Accessibility | Audit performed, [0.1 for reference](https://github.com/ampproject/amphtml/issues?q=is%3Aopen+is%3Aissue+label%3A%22Related+to%3A+Accessibility%22+label%3A%22Component%3A+amp-lightbox-gallery%22) |✅ |
| Page experience | Audit performed |✅ |
| Documentation | Written |✅|
| Storybook | Samples written | ✅ |

## Component compatibility
Attributes to support: n/a
Features to support:

- `<img lightbox />` attribute
- `<amp-base-carousel lightbox />` attribute
- `<amp-stream-gallery lightbox />` attribute
- [captions](https://amp.dev/documentation/examples/components/amp-lightbox-gallery/#captions)

### Migration Notes:

- `.amp-lightbox-gallery-caption` is an exposed class for styling captions displayed in the Preact layer. In an HTML document (AMP or Bento mode) the exposed styling property is `::part(caption)`, due to the caption being provided across the shadow root.
- `lightbox-thumbnail-id` is unsupported at this time until 0.1's expected behavior is resolved as a reference point for backwards compatibility.

## Open tasks:

- [x] Initial implementation 
- [x] ~Investigate doubly rendering same JSX~ Update: This behavior is avoidable via the `render` props
- [x] UI (grid view / carousel view / close button)
- [x] ~Gesture support~
- [x] Modify history state (conformance to 0.1) - AMP only
- [x] Captions support #35171
- [x] Grouping support
- [x] Analytics events
- [x] ~Video support with `lightbox-thumbnail-id`~
- [x] Validation rules

**Comment by caroqliu** [comment]
`lightbox-thumbnail-id` is mentioned in the component documentation without clear code samples or e2e tests on 0.1. When [attempting to make a basic code sample](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoSBsYW5nPSJlbiI+CjxoZWFkPgo8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9Imh0dHBzOi8vYW1wLmRldi9kb2N1bWVudGF0aW9uL2V4YW1wbGVzL2NvbXBvbmVudHMvYW1wLWxpZ2h0Ym94LWdhbGxlcnkvaW5kZXguaHRtbCI+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+CiAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAteW91dHViZSIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAteW91dHViZS0wLjEuanMiPjwvc2NyaXB0PgogIDx0aXRsZT5hbXAtbGlnaHRib3gtZ2FsbGVyeTwvdGl0bGU+CiAgPCEtLSAjIyBTZXR1cCAtLT4KICA8IS0tIEltcG9ydCB0aGUgYW1wLWxpZ2h0Ym94LWdhbGxlcnkgY29tcG9uZW50IGluIHRoZSBoZWFkZXIuICAtLT4KICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtbGlnaHRib3gtZ2FsbGVyeSIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtbGlnaHRib3gtZ2FsbGVyeS0wLjEuanMiPjwvc2NyaXB0PgogIDwhLS0gT3B0aW9uYWxseSBpbXBvcnQgdGhlIGFtcC1jYXJvdXNlbCBjb21wb25lbnQgaW4gdGhlIGhlYWRlciBpZiB5b3UgYXJlIHVzaW5nIGxpZ2h0Ym94IHdpdGggY2Fyb3VzZWwuIC0tPgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1jYXJvdXNlbCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtY2Fyb3VzZWwtMC4xLmpzIj48L3NjcmlwdD4KICA8c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbW96LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tcy1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDthbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aH1ALXdlYmtpdC1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tb3ota2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbXMta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtby1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QGtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX08L3N0eWxlPjxub3NjcmlwdD48c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246bm9uZTstbW96LWFuaW1hdGlvbjpub25lOy1tcy1hbmltYXRpb246bm9uZTthbmltYXRpb246bm9uZX08L3N0eWxlPjwvbm9zY3JpcHQ+CjwvaGVhZD4KPGJvZHk+CjxidXR0b24gb249InRhcDphbXAtbGlnaHRib3gtZ2FsbGVyeSI+CiAgb3BlbiBsaWdodGJveAogIDwvYnV0dG9uPgogIAogICAgPGFtcC15b3V0dWJlCiAgICAgICAgd2lkdGg9IjM2MCIKICAgICAgICBoZWlnaHQ9IjI0MCIKICAgICAgICBkYXRhLXZpZGVvaWQ9IjhseVB5RmhwYVlVIgogICAgICAgIGxpZ2h0Ym94LXRodW1ibmFpbC1pZD0ieW91dHViZS1pbWciCiAgICAgID48L2FtcC15b3V0dWJlPgogICAgICAgIDxhbXAtaW1nCiAgICAgICAgICBsYXlvdXQ9Im5vZGlzcGxheSIKICAgICAgICAgIGlkPSJ5b3V0dWJlLWltZyIKICAgICAgICAgIHNyYz0iaHR0cHM6Ly9pbWFnZXMudW5zcGxhc2guY29tL3Bob3RvLTE1ODM1MTE2NTU4NTctZDE5YjQwYTdhNTRlP2l4bGliPXJiLTEuMi4xJml4aWQ9ZXlKaGNIQmZhV1FpT2pFeU1EZDkmYXV0bz1mb3JtYXQmZml0PWNyb3Amdz0xNDk4JnE9ODAiCiAgICAgICAgLz4KPC9ib2R5PjwvaHRtbD4=), errors surface with `Uncaught (in promise) TypeError: Cannot read property 'descriptionText' of undefined`, for instance. 

Given the above, 1.0 will not be supporting a `lightbox-thumbnail-id` in its first iteration, as it's not currently possible to discern what backward compatible behavior would be due to lack of functional examples.
