### ISSUE TITLE
🚄 Release tracking issue for release 2102130314001

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#32799]
# Release tracking issue

This issue tracks release [2102130314001](https://github.com/ampproject/amphtml/releases/tag/2102130314001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/012102060044003...2102130314001).

- [x] Release 2102130314001 promoted to Experimental and Beta (opt-in) channels (
February 19, 2021, 11:02:16 AM GMT-8)
- [x] Release 2102130314001 promoted to Experimental and Beta (1% traffic) channels (
February 19, 2021, 11:22:34 AM GMT-8)
- [x] Disabled Experiment B because if high error rates (February 19, 2021, 2:09:06 PM GMT-8)
- [ ] Release 2102130314001 promoted to Stable channel (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by erwinmombay** [comment]
closing, dupe of https://github.com/ampproject/amphtml/issues/32757
