### ISSUE TITLE
🚄 Release tracking issue for release 2102200206000

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#32874]
# Release tracking issue

This issue tracks release [2102200206000](https://github.com/ampproject/amphtml/releases/tag/2102200206000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2102130314001...2102200206000).

- [x] Release 2102200206000 promoted to Experimental and Beta (opt-in) channels (2021-02-23 17:42:30 -05:00)
- [x] Release 2102200206000 promoted to Experimental and Beta (1% traffic) channels (2021-02-24 14:29:18 -05:00)
- [x] Release 2102200206004 created with cherry picks (#32981) (March 1, 2021, 7:25:15 PM GMT-8)
- [x] Release 2102200206004 promoted to Stable channel (March 3, 2021, 12:39:51 PM GMT-8)
- [x] Release 2102200206005 created with cherry picks (#33052) (March 3, 2021, 5:48:39 PM GMT-8)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
