### ISSUE TITLE
🚄 Release tracking issue for release 2103020108001

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#33053]
# Release tracking issue

This issue tracks release [2103020108001](https://github.com/ampproject/amphtml/releases/tag/2103020108001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2102200206004...2103020108001).

- [x] Release 2103020108001 promoted to Experimental and Beta (opt-in) channels (March 3, 2021, 4:11:09 PM GMT-8)
- [x] Release 2103020156001 created with cherry-picks (#33052) (March 4, 2021, 7:28:59 AM GMT-8)
- [x] Release 2103020156001 promoted to Experimental and Beta (1% traffic) channels (March 4, 2021, 10:15:52 AM GMT-8)
- [x] Release 2103020156002 created with cherry-picks (#33081) (March 4, 2021, 3:53 PM GMT-8)
- [ ] ~~Release 2103020156002 promoted to Stable channel (<CL submit time>)~~
- [x] Release 2103020156003 create with cherry-picks (#33172) (March 10, 2021, 2:53:15 PM GMT-8)
- [x] Release 2103020156003 promoted to Stable channel (March 10, 2021, 4:03:08 PM GMT-8)
- [x] Release 2103020156004 create with cherry-picks (https://github.com/ampproject/amphtml/issues/33221) (
March 11, 2021, 3:48:29 PM GMT-8)
- [] ~~Release 2103020156004 promoted to Stable channel (March 11, 2021, 8:35:31 PM GMT-8)~~
- [x] Release 2103020156005 create with cherry-picks (https://github.com/ampproject/amphtml/issues/33228) (March 11, 2021, 9:52:24 PM GMT-8)
- [x] Release 2103020156005 promoted to Stable channel (March 12, 2021, 6:48:10 AM GMT-8)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment]
@erwinmombay @alanorozco Can this be closed out?
