### ISSUE TITLE
✨Tracking issue for new story ads placement algorithm

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#33147]
We are exploring options to improve the ad placement logic in `<amp-story-auto-ads>` especially to help monetize shorter stories or shorter sessions, while still maintaining user experience goals.

Pre-work
- [ ] Implement page manager for easier refactoring
- [ ] Encapsulate all algorithm specific logic

New work
- [ ] Implement new algorithm
- [ ] Implement experimental choosing of algo
- [ ] Monitor experiment results
- [ ] 🛳⛴🚢

cc/ @ampproject/wg-monetization

**Comment by kristoferbaxter** [comment]
This appears to be a great topic for design review. Could you bring the idea there?

**Comment by dcombe** [comment]
@calebcordry @kristoferbaxter 
Any update on this ? 

End I had a question, is the following function really currently used in LTS to determine if stories can display ads where they have more than 4 pages (in the merged to LTS in https://github.com/ampproject/amphtml/pull/33377). It seems the function is defined but not used in the getNumberOfAds. 
`isStoryEligible() {
    const storyLength = this.storyPageIds_.length;
    return storyLength > BEGINNING_OF_STORY_BUFFER + END_OF_STORY_BUFFER;
  }`

Moreover, as far as I understand, according to the code, it is not >=4 pages (as mentioned here: https://github.com/ampproject/amphtml/issues/33547) but >=5pages.

**Comment by calebcordry** [comment]
Hi @dcombe you are correct, this is not launched yet and we are still running it on a small portion of traffic. We are working on getting it launched but it may be another few weeks. I will update this thread when it is fully launched.

**Comment by dcombe** [comment]
Ok @calebcordry thanks.
And am I right it will be >= 5 and not >=4 as mentioned [here](https://github.com/ampproject/amphtml/issues/33547) ?
