### ISSUE TITLE
🚄 Release tracking issue for release 2103060631000

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#33224]
# Release tracking issue

This issue tracks release [2103060631000](https://github.com/ampproject/amphtml/releases/tag/2103060631000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2103020156004...2103060631000).

- [x] Release 2103060631000 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [ ] ~~Release 2103060631000 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)~~
- [ ] ~~Release 2103060631000 promoted to Stable channel (<CL submit time>)~~
- [x] Release 2103060631002 create with cherry-picks (#33207, #33227) (March 12, 2021, 5:36:43 AM GMT-8)
- [x] Release 2103060631002 promoted to Experimental and Beta (opt-in) channels (March 12, 2021, 7:50:56 AM GMT-8)
- [x] Release 2103060631002 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [x] Release 2103060631002 promoted to Stable channel (March 16, 2021, 11:17:10 AM GMT-4)
- [x] Identified P0 (https://github.com/ampproject/amphtml/issues/33317) in Stable; rolled back to 012103020156005 (March 17, 2021, 12:12:45 PM GMT-4)
- [x] Release 2103060631003 created with cherry-pick (#33317)
- [x] Release 2103060631004 created with cherry-pick (#33333)
- [x] Release 2103060631004 promoted to Experimental and Beta (1% traffic) channels (March 17, 2021, 8:09:40 PM GMT-4)
- [x] Release 2103060631004 promoted to Stable channel (March 18, 2021, 1:37:14 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
