### ISSUE TITLE
🚄 Release tracking issue for release 2103122145004

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#33276]
# Release tracking issue

This issue tracks release [2103122145000](https://github.com/ampproject/amphtml/releases/tag/2103122145000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2103020156005...2103122145000).

- [x] Release [2103122145002](https://github.com/ampproject/amphtml/releases/tag/2103122145002) created with cherry picks #33271 , #33277
- [x] Release 2103122145002 promoted to Experimental and Beta (opt-in) channels (March 17, 2021, 1:17:28 PM GMT-4)
- [x] Release 2103122145002 promoted to Experimental and Beta (1% traffic) channels (March 18, 2021, 2:22:33 PM GMT-4)
- [x] Release [2103122145004](https://github.com/ampproject/amphtml/releases/tag/2103122145004) created with cherry picks #33409, #33446
- [x] Release 2103122145004 promoted to Stable channel (March 24, 2021, 12:31:09 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
