### ISSUE TITLE
Intent to Implement: AMP Forms Support

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3343]
AMP will allow the usage of HTML5 `<form>` and `<input>`s. Publishers and Developers wanting to use Forms in their AMP Docs would be required to include the `amp-form` extension. There would be no `amp-form` element provided initially though it might be introduced in the future if we see need to it.

For now the AMP Form extension will polyfill support for validation where missing and allow forms to be submitted in an XHR-request.

While in experiments we'll start adding these features:
- [x] Allow basic usage of forms and inputs
- [x] Submit via `xhr`,  `_top` or `_blank`.
- [x] Validate and stop submission on Safari and other browsers that doesn't have validations-complete story
- [x] Allow rendering success and error states with data returned from the response
- [x] Build a tooltip component to be used when the builtin report UI is not available
- [x] Report Validation Errors on Webkit-based browsers that don't have builtin UI for error reporting.
- [x] Provide classes/attributes hooks to style different state of the form
- [x] Provide classes to style different states per input as the user jump between inputs
- [x] Allow users to always use custom validation messages instead of browser-provided UX
- [x] Expose `submit` event to allow `on=submit:lightbox.close` syntax.

Other issues to track:
- [x] Prevent double-submissions while the request is still being processed
- [x] Respect `novalidate` even on non-supported browsers #3469
- [x] Cleanup rendered submissions templates during submit #3587
- [x] Add Styles to display error/success containers to `amp-form.css`
- [x] Form submission fail when using GET and native Fetch API #3736
- [ ] Fieldsets marked valid when having invalid inputs on non-blink browsers #3898
- [x] Make custom validation and polyfills accessible - #3880 #3872 #3873

This will probably go out of experiment as soon as the list above with the required validations are deployed. 

Next we'll explore field-dependencies, data-loading and other features.

**Comment by HerbertL** [comment]
Is there a timeline on when AMP Forms Support will be added?

**Comment by dandv** [comment]
@HerbertL: [experimental forms support](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md) has been available since June.

**Comment by apch54** [comment]
is there a mean  working on a non htpps server ?

**Comment by mkhatib** [comment]
@apch54 no not currently. I am not even sure if non-secure endpoints would be allowed in the future.

cc/ @dvoytenko @cramforce for more details.

**Comment by dvoytenko** [comment]
All AMP protocols are allowed to be tested on `http://localhost` in dev modes. But not on any non-localhost http server.

**Comment by Bijunairzamp** [comment]
Team:
I have an Form that captures information like username, email ID and mobile number in TEXT area and gives the option of dropdown box to select Location. This information is then sent to my server when the user taps the SUBMIT button. Can you'll guide me how i can incorporate the same using AMP.
( I am new to AMP)

**Comment by rudygalfi** [comment]
The ability to support this is being developed under this issue. Much of the functionality is built, but is only available experimentally pending the entire feature being ready to launch. If you want to try it out, you can use pages like https://ampbyexample.com/components/amp-form/ to get started.

**Comment by Bijunairzamp** [comment]
Thanks Rudy for the prompt reply.. surely i will be trying out and sharing
my experience

**Comment by rohitverma007** [comment]
Great work on this! Just wondering when will this be out of experimental stage since some components such as `submit-success` fail the AMP validation. I see that there's only one issue left which is in regards to fieldsets validation.

**Comment by rudygalfi** [comment]
The `submit-success` validation is being tracked here: https://github.com/ampproject/amphtml/issues/5268#issuecomment-250048435

**Comment by rohitverma007** [comment]
@rudygalfi I see, thanks! I hope this is the right place to ask but I was wondering If the form component is no longer prohibited as it passes the validation (after including the amp-form extension) and whether it can be used in production-ready AMP documents. The docs state it is as experimental and also state that experimental components will fail validation.

**Comment by rudygalfi** [comment]
Experimental means that things might change and could still break your docs without notice. The component is close to stable and we don't anticipate that (in fact, the validation problem I noted in my previous comment is the main thing we're tracking to fix before calling this stable).

**Comment by Bijunairzamp** [comment]
HI.. Why is this closed?

**Comment by cramforce** [comment]
Because it shipped :)
