### ISSUE TITLE
🚄 Release tracking issue for release 2103240330001

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#33461]
# Release tracking issue

This issue tracks release [2103240330001](https://github.com/ampproject/amphtml/releases/tag/2103240330001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2103122145004...2103240330001).

- [x] Release [2103240330000](https://github.com/ampproject/amphtml/releases/tag/2103240330000) promoted to Experimental and Beta (opt-in) channels (March 24, 2021, 1:01:57 PM GMT-4)
- [x] Release 2103240330000 promoted to Experimental and Beta (1% traffic) channels (March 25, 2021, 10:54:54 AM GMT-4)
- [x] Release 2103240330000 promoted to Stable channel (March 30, 2021, 1:41:53 PM GMT-4)
- [x] Release [2103240330001](https://github.com/ampproject/amphtml/releases/tag/2103240330001) created with cherry pick #33562
- [x] Release 2103240330001 promoted to Stable channels (March 31, 2021, 4:02:00 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
