### ISSUE TITLE
🚄 Release tracking issue for release 2103261048002

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#33542]
# Release tracking issue

This issue tracks release [2103261048002](https://github.com/ampproject/amphtml/releases/tag/2103261048002). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2103122145004...2103261048002).

- [x] Release [2103261048000](https://github.com/ampproject/amphtml/releases/tag/2103261048000) promoted to Experimental and Beta (opt-in) channels (March 30, 2021, 1:07:25 PM GMT-4)
- [x] Release [2103261048001](https://github.com/ampproject/amphtml/releases/tag/2103261048001) created with cherry pick #33562
- [x] Release 2103261048001 promoted to Experimental and Beta (opt-in) channels (March 31, 2021, 4:26:18 PM GMT-4)
- [x] Release 2103261048001 promoted to Experimental and Beta (1% traffic) channels (April 1, 2021, 12:34:22 PM GMT-4)
- [x] Release [2103261048002](https://github.com/ampproject/amphtml/releases/tag/2103261048002) created with cherry pick #33592
- [x] Release 2103261048002 promoted to Experimental and Beta (opt-in) channels (April 1, 2021, 5:44:05 PM GMT-4)
- [x] Release 2103261048002 promoted to Experimental and Beta (1% traffic) channels (April 1, 2021, 5:51:26 PM GMT-4)
- [x] Release 2103261048002 promoted to Stable channel (April 6, 2021, 4:37:29 PM GMT-4)
- [x] Release 2103261048002 promoted to LTS (April 12, 2021, 11:06:15 AM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
