### ISSUE TITLE
Tracking Issue: restricted paths eslint allowlist

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#33631]
#33016 introduced eslint rules that disallows certain cross directory file imports. Given these are now blocking lint checks, there is also an allowlist for this rule:
https://github.com/ampproject/amphtml/blob/b286342aea581a77870178cb9c82d3ff63558477/src/.eslintrc.js#L49-L64

This is a tracking issue to centralize efforts to move files used in restricted and allowlisted ways so that they can be used correctly. Temporary additions to the allowlist should also refer to this issue so this work can stay up to date.

**Comment by rcebulko** [comment]
### General update
The log system is complicated, and asserts do a lot of extra work moving around arguments, picking out the first element, constructing the message array, transforming and filtering its values, etc. This is also related to some work on message extraction (one related PR: #25098), which includes some of the following goals/partial efforts:

- migrating existing calls to use template strings instead of sprintf format
  > Ex. `devAssert(truthy, 'The %s did a %s', divElement, barrelRoll)` 
  should be written as
  ``devAssert(truthy, `The ${divElement} did a ${barrelRoll}`))``<sup>1</sup>
- rewriting all error/log/assert calls to `fn('identifierString', [...messageArgs])`
  > Ex. ``devAssert(truthy, `The ${divElement} did a ${barrelRoll}`))``
  compiles to
  `devAssert(truthy, ["The %s did a %s", divElement, barrelRoll])`<sup>2</sup>
  and with the generated log-messages table becomes something like
  `devAssert(truthy, ["dF", divElement, barrelRoll])`
  
<sup>1</sup> above would reduce the number of arguments the assertion functions need to support, including the inline parameters and some wrapping of functions and reduce boilerplate for extracting variadic arguments. Downside: without the transform or the sprintf format, this wouldn't enable extracting the `messageArray` or element, or formatting elements into strings. We'd want to enable the template string transform for unminified builds so we can take advantage of this.

https://github.com/ampproject/amphtml/blob/af37e3ba33c29115f33496c335786f340b31f065/src/log.js#L868-L880

<sup>2</sup> above would result in the assertion functions being handed the message array directly, and so they wouldn't have to do any manipulation themselves; assertion/error/log code could become a decent bit simpler.

### Thoughts
**Goals:** Reduce core assert/error code complexity and bytes + partially validate message extraction approach

Some parts of this rewrite would be useful by itself for reducing the complexity of some common logging/assertion functions and shaving down the number of bytes spent shuffling data around in assertion code. Code that needs to do things with the message array, like filtering it or extracting elements from it (or anything else) can be handled by the function consuming that data and keep the core logic small.

Doing this step in isolation from the full log message extraction migration would also allow for iterative validation of the approach, lowering the risk of eventual log extraction.

### Planned Steps

- [ ] Move logic to find `error.firstElement` from core assertion code to its only consumer (`reportError`, which has the full `messageArray` to work with)
- [ ] Make the default assert signature `assert(shouldBeTruthy, [msg, ...msgArgs])` and shim sprintf-style calls to that messageArray format (or update them directly, quite doable automatically)
- [ ] Enable transforming template-string calls into messageArray format
- [ ] (Best-effort) migrate existing calls to template-string format

/cc @ampproject/wg-performance @alanorozco

**Comment by rcebulko** [comment]
Total bundle size reduction of 9.4KB across all binaries
> Note: These are changes in Brotli compressed size; there is minimal change to uncompressed bundle sizes.

Bundle-size highlights:
```
Δ -0.09KB : dist/v0/amp-subscriptions-google-0.1.js
Δ -0.08KB : dist/v0/amp-story-1.0.js
Δ -0.08KB : dist/v0/amp-story-0.1.js
Δ -0.08KB : dist/v0/amp-analytics-0.1.js
Δ -0.07KB : dist/v0/amp-script-0.1.js
Δ -0.07KB : dist/v0/amp-render-1.0.js
Δ -0.07KB : dist/v0/amp-date-picker-0.1.js
Δ -0.06KB : dist/v0/amp-standalone-0.1.js
Δ -0.06KB : dist/v0/amp-ad-network-nws-impl-0.1.js
Δ -0.06KB : dist/v0/amp-ad-network-fake-impl-0.1.js
Δ -0.06KB : dist/v0/amp-access-0.1.js
Δ -0.05KB : dist/v0/amp-playbuzz-0.1.js
Δ -0.05KB : dist/v0/amp-autocomplete-0.1.js
Δ -0.05KB : dist/v0/amp-audio-0.1.js
Δ -0.05KB : dist/amp-story-player-v0.js
Δ -0.05KB : dist.3p/current-min/vendor/viralize.js
Δ -0.05KB : dist.3p/current-min/vendor/adfox.js
Δ -0.04KB : dist/v0/amp-web-push-0.1.js
Δ -0.04KB : dist/v0/amp-onetap-google-0.1.js
Δ -0.04KB : dist/v0/amp-mustache-0.2.js
Δ -0.04KB : dist/v0/amp-date-display-1.0.mjs
Δ -0.04KB : dist/v0/amp-call-tracking-0.1.js
Δ -0.04KB : dist/v0/amp-brid-player-0.1.js
Δ -0.04KB : dist/v0.js
Δ -0.04KB : dist/amp-story-entry-point-v0.js
