### ISSUE TITLE
🚄 Release tracking issue for release 2104022034000

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#33662]
# Release tracking issue

This issue tracks release [2104022034000](https://github.com/ampproject/amphtml/releases/tag/2104022034000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2103261048002...2104022034000).

- [x] Release 2104022034000 promoted to Experimental and Beta (opt-in) channels (April 6, 2021, 5:14:23 PM GMT-4)
- [x] Release 2104022034000 promoted to Experimental and Beta (1% traffic) channels (April 7, 2021, 11:12:41 AM GMT-4)
- [x] Release 2104022034000 promoted to Stable channel (April 13, 2021, 3:16:41 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
