### ISSUE TITLE
🚄 Release tracking issue for release 2104081613001

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#33809]
# Release tracking issue

This issue tracks release [2104081613001](https://github.com/ampproject/amphtml/releases/tag/2104081613001). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2104022034000...2104081613001).

- [x] Release [2104081613000](https://github.com/ampproject/amphtml/releases/tag/2104081613000) promoted to Experimental and Beta (opt-in) channels (April 13, 2021, 3:32:08 PM GMT-4)
- [x] Release 2104081613000 promoted to Experimental and Beta (1% traffic) channels (April 14, 2021, 12:15:49 PM GMT-4)
- [x] Cherry-picked https://github.com/ampproject/amphtml/issues/33862
- [x] Release [2104081613001](https://github.com/ampproject/amphtml/releases/tag/2104081613001) promoted to Experimental and Beta (opt-in) channels (April 18, 2021, 7:34:50 PM GMT-4)
- [x] Release 2104081613001 promoted to Experimental and Beta (1% traffic) channels (April 18, 2021, 7:10:57 PM GMT-4)
- [x] Release 2104081613001 promoted to Stable channel (April 20, 2021, 1:25:01 PM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/main/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
