### ISSUE TITLE
🚄 Release tracking issue for release 2104170104001

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#33925]
# Release tracking issue

This issue tracks release [2104170104000](https://github.com/ampproject/amphtml/releases/tag/2104170104000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2104081613001...2104170104000).

- [x] Release 2104170104000 promoted to Experimental and Beta (opt-in) channels (April 20, 2021, 1:46:54 PM GMT-7)
- [x] Release 2104170104000 promoted to Experimental and Beta (1% traffic) channels (April 21, 2021, 10:11:48 AM GMT-7)
- [ ] ~~Release 2104170104000 promoted to Stable channel (<CL submit time>)~~
- [x] Release [2104170104001](https://github.com/ampproject/amphtml/releases/tag/2104170104001) created with cherry picks #33968
- [x] Release 2104170104001 promoted to Experimental and Beta (opt-in) channels (April 22, 2021, 5:33:44 PM GMT-7)
- [x] Release 2104170104001 promoted to Experimental and Beta (1% traffic) channels (April 23, 2021, 9:09:30 AM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/main/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
