### ISSUE TITLE
Bento NPM Publishing Tracker Issue

### ISSUE THREAD

**Issue by krdwan** [ampproject/amphtml#34137]
Tracker Issue for Bento NPM Publishing

[Lastest Status](https://docs.google.com/spreadsheets/d/1JnCfYzgEojX_vPVy6h0fOnOLIHOcfPl4FCOZUDpclfE/edit#gid=0)

- [x] Manually Publish First Batch of Components Including:
- amp-accordion
- amp-inline-gallery
- amp-date-countdown
- amp-date-display
- amp-fit-text
- amp-instagram
- amp-lightbox
- amp-selector
- amp-timeago
- amp-youtube
- [x] NPM Definition and package files
  - [x] Create NPM definition and package files for publishing components above: https://github.com/ampproject/amphtml/pull/34087
  - [x]  NPM Definition for amp-twitter https://github.com/ampproject/amphtml/pull/34333
- [x] Components conversion
  - [x] Conversion of amp-stream-gallery https://github.com/ampproject/amphtml/pull/34208
  - [x] Conversion of amp-base-carousel https://github.com/ampproject/amphtml/pull/34283
  - [x] Conversion of amp-social-share #34817
  - [x] Conversion of amp-video #34822
- [x] Create README examples for Dev Rel [Sample Readmes](https://docs.google.com/document/d/1OSkY69U440-FdGOV4kYzWpYezfwgy_KyNV3Q7S9wfuA/edit#)
- [x] Update `package.json` to support react apps https://github.com/ampproject/amphtml/pull/34528
- [x] Updated file naming to support react apps https://github.com/ampproject/amphtml/pull/34568
