### ISSUE TITLE
🚄 Release tracking issue for release 2104240357000

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#34244]
# Release tracking issue

This issue tracks release `[2104240357000](https://github.com/ampproject/amphtml/releases/tag/2104240357000)`.

- [X] Release 2104240357000 promoted to Experimental and Beta (opt-in) channels (<CL submit time>)
- [X] Release 2104240357000 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [X] Release 2104240357000 promoted to Stable channel (May 5, 2021, 8:56:59 AM GMT-7)

See the [release documentation](https://github.com/ampproject/amphtml/blob/main/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
