### ISSUE TITLE
🚄 Release tracking issue for release 2104302228000

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#34245]
# Release tracking issue

This issue tracks release `[2104302228000](https://github.com/ampproject/amphtml/releases/tag/2104302228000)`. See what's new compared to stable `[here](https://github.com/ampproject/amphtml/compare/<LATEST_STABLE_RELEASE_NUMBER>...<RELEASE_NUMBER>)`.

- [x] Release 2104302228000 promoted to Experimental and Beta (opt-in) channels (May 4, 2021, 3:09:59 PM GMT-7)
- [x] Release 2104302228000 promoted to Experimental and Beta (1% traffic) channels (May 5, 2021, 1:37:57 PM GMT-7)
- [x] Release 2104302228000 promoted to Stable channel (May 11, 2021, 3:29:25 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/main/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
