### ISSUE TITLE
🚄 Release tracking issue for release 2105072136000

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#34321]
# Release tracking issue

This issue tracks release [2105072136000](https://github.com/ampproject/amphtml/releases/tag/2105072136000).
 See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2104302228000...2105072136000).

- [x] Release 2105072136000 promoted to Experimental and Beta (opt-in) channels (2:38 PM, May 11, 2021 UTC-4)
- [x] Release 2105072136000 promoted to Experimental and Beta (1% traffic) channels (<CL submit time>)
- [x] Release 2105072136000 promoted to Stable channel (<CL submit time>)

See the [release documentation](https://github.com/ampproject/amphtml/blob/main/contributing/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
