### ISSUE TITLE
🚄  Release tracking issue for release 2105150310000

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#34437]
# Release tracking issue

This issue tracks release [2105150310000](https://github.com/ampproject/amphtml/releases/tag/2105150310000). See what's new compared to stable [here](https://github.com/ampproject/amphtml/compare/2105072136000...2105150310000).

- [x] Release 2105150310000 promoted to Experimental and Beta (opt-in) channels (May 18, 2021, 5:09:25 PM GMT-4)
- [x] Release 2105150310000 promoted to Experimental and Beta (1% traffic) channels (May 20, 2021, 4:38:49 PM GMT-4)
- [x] Release 2105150310000 promoted to Stable channel (May 25, 2021, 2:52:04 PM GMT-4)

See the [release documentation](https://github.com/ampproject/amphtml/blob/main/docs/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
