### ISSUE TITLE
🚄 Release tracking issue for release 2105210438000

### ISSUE THREAD

**Issue by krdwan** [ampproject/amphtml#34543]
# Release tracking issue

This issue tracks release [2105210438000](https://github.com/ampproject/amphtml/releases/tag/2105210438000). See [new commits](https://github.com/ampproject/amphtml/compare/2105150310000...2105210438000) since the previous Stable channel release.

- [x] Release 2105210438000 promoted to Experimental and Beta (opt-in) channels (May 25, 2021, 4:59:55 PM GMT-4)
- [x] Release 2105210438000 promoted to Experimental and Beta (1% traffic) channels (May 26, 2021, 11:50:08 AM GMT-4)
- [ ] Release 2105210438000 promoted to Stable channel (CL_SUBMIT_TIME)

See the [release documentation](https://github.com/ampproject/amphtml/blob/main/docs/release-schedule.md) for more information on the release process, including how to test changes in the Experimental channel.

If you find a bug in this build, please file an [issue](https://github.com/ampproject/amphtml/issues/new). If you believe the bug should be fixed in this build, follow the instructions in the [cherry picks documentation](https://go.amp.dev/cherry-picks).

/cc @ampproject/release-on-duty
