### ISSUE TITLE
🚄 Tracking issue for release 2105210438000

### ISSUE THREAD

**Issue by krdwan** [ampproject/amphtml#34565]
### Release Version

2105210438000

### Previous Release Version

2105150310000

### Release Progress

This issue tracks release [2105210438000](https://github.com/ampproject/amphtml/releases/tag/2105210438000). See [new commits](https://github.com/ampproject/amphtml/compare/2105150310000...2105210438000) since the previous Stable channel release.

- [x] Release 2105210438000 promoted to Experimental and Beta (opt-in) channels (May 25, 2021, 4:59:55 PM GMT-4)
- [x] Release 2105210438000 promoted to Experimental and Beta (1% traffic) channels (May 26, 2021, 11:50:08 AM GMT-4)
- [x] Release 2105210438003 promoted to Stable channel (June 3, 2021, 2:57:10 PM GMT-4)

### LTS Release

_To be updated if an LTS promotion is necessary._

- [ ] Release VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Cherry-Picks

_To be updated if a cherry-pick release is necessary._

A cherry-pick release [2105210438002](https://github.com/ampproject/amphtml/releases/tag/2105210438002) was created with cherry-pick(s) https://github.com/ampproject/amphtml/issues/34599, https://github.com/ampproject/amphtml/issues/34596

- [x] Release 2105210438002 promoted to Experimental and Beta (opt-in) channels (May 28, 2021, 7:37:40 PM GMT-4)
- [x] Release 2105210438002 promoted to Experimental and Beta (1% traffic) channels (June 1, 2021, 10:55:01 AM GMT-4)
- [x] Release 2105210438003 promoted to Experimental and Beta (opt-in) channels (June 2, 2021, 4:07:13 PM GMT-4)
- [x] Release 2105210438003 promoted to Experimental and Beta (1% traffic) channels (June 2, 2021, 3:40:32 PM GMT-4)
- [x] Release 2105210438003 promoted to Stable channel (June 3, 2021, 2:57:10 PM GMT-4)
- [x] Release 2105210438003 promoted to LTS channel (2021-06-03 11:57)

### Notifications

/cc @ampproject/release-on-duty
