### ISSUE TITLE
🚄 Tracking issue for release 2106030132000

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#34705]
### Release Version

2106030132000

### Previous Release Version

2105210438003

### Release Progress

This issue tracks release [2106030132000](https://github.com/ampproject/amphtml/releases/tag/2106030132000). See [new commits](https://github.com/ampproject/amphtml/compare/2105210438003...2106030132000) since the previous Stable channel release.

- [x] Release 2106030132000 promoted to Experimental and Beta (opt-in) channels (June 3, 2021, 3:45:28 PM GMT-4)
- [x] Release 2106030132000 promoted to Experimental and Beta (1% traffic) channels (June 4, 2021, 10:55:19 AM GMT-4)
- [x] Release 2106030132000 promoted to Stable channel (CL_SUBMIT_TIME)

### LTS Release

_To be updated if an LTS promotion is necessary._

- [ ] Release 2106030132000 promoted to LTS channel (CL_SUBMIT_TIME)

### Cherry-Pick Release Progress

_To be updated if a cherry-pick release is necessary._

A cherry-pick release [CP_VERSION](https://github.com/ampproject/amphtml/releases/tag/CP_VERSION) was created with cherry-pick(s) #CP_ISSUE.

- [ ] Release CP_VERSION promoted to Experimental and Beta (opt-in) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Experimental and Beta (1% traffic) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Stable channel (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Notifications

/cc @ampproject/release-on-duty
