### ISSUE TITLE
[amp-lightbox-gallery:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#34737]
## High-level requirements
| Consideration  | Ready when | Status |
| ------------- | ------------- | ------- |
| Component compatibility | [Conformance with 0.1 (see below)](https://amp.dev/documentation/components/amp-lightbox-gallery/) | ✖️ |
| Testing | Unit tests and e2e tests from 0.1 | ✅ |
| Internationalization | n/a | n/a |
| Analytics | n/a | ✖️ |
| Accessibility | Audit performed, [0.1 for reference](https://github.com/ampproject/amphtml/issues?q=is%3Aopen+is%3Aissue+label%3A%22Related+to%3A+Accessibility%22+label%3A%22Component%3A+amp-lightbox-gallery%22) |✖️ |
| Page experience | Audit performed |✖️ |
| Documentation | Written |✖️ |
| Storybook | Samples written | ✅ |

## Component compatibility
Attributes to support: 
- [x]  `img[lightbox]`
- [ ] `amp-carousel[lightbox]`
- [ ] `amp-base-carousel[lightbox]`

### Migration Notes:

n/a

## Open tasks:

- [x] Preact layer
- [x] Unit tests
- [ ] UI features (Carousel View and Grid View)
- [ ] AMP layer
- [ ] Gestures library integration

**Comment by caroqliu** [comment]
Whoops, dedupe with #32759
