### ISSUE TITLE
🚄 Tracking issue for release 2106072053000

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#34788]
### Release Version

2106072053000

### Previous Release Version

2106030132000

### Release Progress

This issue tracks release [VERSION](https://github.com/ampproject/amphtml/releases/tag/VERSION). See [new commits](https://github.com/ampproject/amphtml/compare/PREVIOUS_VERSION...VERSION) since the previous Stable channel release.

- [x] Release VERSION promoted to Experimental and Beta (opt-in) channels (2021-06-08 15:34)
- [x] Release VERSION promoted to Experimental and Beta (1% traffic) channels (June 9, 2021, 11:23:22 AM GMT-4)
- [x] Release VERSION promoted to Stable channel (June 15, 2021, 8:38:39 PM GMT-4)

### LTS Release

_To be updated if an LTS promotion is necessary._

- [ ] Release VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Cherry-Pick Release Progress

_To be updated if a cherry-pick release is necessary._

A cherry-pick release [CP_VERSION](https://github.com/ampproject/amphtml/releases/tag/CP_VERSION) was created with cherry-pick(s) #CP_ISSUE.

- [ ] Release CP_VERSION promoted to Experimental and Beta (opt-in) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Experimental and Beta (1% traffic) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Stable channel (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Notifications

/cc @ampproject/release-on-duty
