### ISSUE TITLE
🚄 Tracking issue for release 2106120107000

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#34882]
### Release Version

2106120107000

### Previous Release Version

2106072053000

### Release Progress

This issue tracks release [VERSION](https://github.com/ampproject/amphtml/releases/tag/VERSION). See [new commits](https://github.com/ampproject/amphtml/compare/PREVIOUS_VERSION...VERSION) since the previous Stable channel release.

- [x] Release 2106120107000 promoted to Experimental and Beta (opt-in) channels (June 15, 2021, 8:53:04 PM GMT-4)
- [x] Release 2106120107000 promoted to Experimental and Beta (1% traffic) channels (June 16, 2021, 4:22:42 PM GMT-4)
- [x] Release 2106120107000 promoted to Stable channel (Tue, Jun 22, 2021, 6:15 PM GMT-4)

### Cherry-Pick Release Progress

_To be updated if a cherry-pick release is necessary._

A cherry-pick release [CP_VERSION](https://github.com/ampproject/amphtml/releases/tag/CP_VERSION) was created with cherry-pick(s) #CP_ISSUE.

- [ ] Release CP_VERSION promoted to Experimental and Beta (opt-in) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Experimental and Beta (1% traffic) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Stable channel (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Notifications

/cc @ampproject/release-on-duty
