### ISSUE TITLE
🚄 Tracking issue for release 2106182132000

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#34972]
### Release Version

2106182132000

### Previous Release Version

2106120107000

### Release Progress

This issue tracks release [2106182132000](https://github.com/ampproject/amphtml/releases/tag/2106182132000). See [new commits](https://github.com/ampproject/amphtml/compare/2106120107000...2106182132000) since the previous Stable channel release.

- [x] Release `2106182132000` promoted to Experimental and Beta (opt-in) channels (
Tue, Jun 22, 2021, 3:40 PM GMT-4)
- [x] Release 2106182132000 promoted to Experimental and Beta (1% traffic) channels (CL_SUBMIT_TIME)
- [x] Release 2106182132000 promoted to Stable channel (Tue, Jun 29, 2021, 3:40 PM GMT-4)

### LTS Release
_To be updated if an LTS promotion is necessary._

- [x] Release 2106182132000 promoted to LTS channel (Mon, Jul 12, 2021, 3:23 PM GMT-4)

### Cherry-Pick Release Progress

_To be updated if a cherry-pick release is necessary._

A cherry-pick release [CP_VERSION](https://github.com/ampproject/amphtml/releases/tag/CP_VERSION) was created with cherry-pick(s) #CP_ISSUE.

- [ ] Release CP_VERSION promoted to Experimental and Beta (opt-in) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Experimental and Beta (1% traffic) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Stable channel (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Notifications

/cc @ampproject/release-on-duty
