### ISSUE TITLE
🚄 Tracking issue for release 2106260436000

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#35074]
### Release Version

2106260436000

### Previous Release Version

2106182132000

### Release Progress

This issue tracks release [2106260436000](https://github.com/ampproject/amphtml/releases/tag/2106260436000). See [new commits](https://github.com/ampproject/amphtml/compare/2106182132000...2106260436000) since the previous Stable channel release.

- [x] Release 2106260436000 promoted to Experimental and Beta (opt-in) channels (Tue, Jun 29, 2021, 4:01 PM GMT-4)
- [x] Release 2106260436000 promoted to Experimental and Beta (1% traffic) channels (Wed, Jun 30, 2021, 3:18 PM GMT-4)
- [ ] Release VERSION promoted to Stable channel (CL_SUBMIT_TIME)

### LTS Release

_To be updated if an LTS promotion is necessary._

- [ ] Release VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Cherry-Pick Release Progress

_To be updated if a cherry-pick release is necessary._

A cherry-pick release [CP_VERSION](https://github.com/ampproject/amphtml/releases/tag/CP_VERSION) was created with cherry-pick(s) #CP_ISSUE.

- [ ] Release CP_VERSION promoted to Experimental and Beta (opt-in) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Experimental and Beta (1% traffic) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Stable channel (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Notifications

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment]
Closing out this tracker because 2106260436000 didn't need to be promoted to stable due to the release freeze.

/cc @processprocess
