### ISSUE TITLE
🚄 Release tracking issue for release 2107030008001

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#35162]
### Release Version

2107030008001

### Previous Release Version

2106260436000

### Release Progress

This issue tracks release [2107030008001](https://github.com/ampproject/amphtml/releases/tag/2107030008001). See [new commits](https://github.com/ampproject/amphtml/compare/2106260436000...2107030008001) since the previous Stable channel release.

- [x] Release 2107030008001 promoted to Experimental and Beta (opt-in) channels (Fri, Jul 9, 2021, 8:40 AM GMT-4)
- [x] Release 2107030008001 promoted to Experimental and Beta (1% traffic) channels (Fri, Jul 9, 2021, 3:25 PM GMT-4)
- [x] Release 2107030008001 promoted to Stable channel (Tue, Jul 13, 2021, 1:29 PM GMT-4)

### LTS Release

_To be updated if an LTS promotion is necessary._

- [ ] Release VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Cherry-Pick Release Progress

_To be updated if a cherry-pick release is necessary._

A cherry-pick release [CP_VERSION](https://github.com/ampproject/amphtml/releases/tag/CP_VERSION) was created with cherry-pick(s) #CP_ISSUE.

- [ ] Release CP_VERSION promoted to Experimental and Beta (opt-in) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Experimental and Beta (1% traffic) channels (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to Stable channel (CL_SUBMIT_TIME)
- [ ] Release CP_VERSION promoted to LTS channel (CL_SUBMIT_TIME)

### Notifications

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment]
Closing now that https://github.com/ampproject/amphtml/releases/tag/2107030008001 has been promoted to stable.
