### ISSUE TITLE
🚄 Tracking issue for release 2107092322000

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#35202]
### Release Version

2107092322000

### Previous Release Version

2107030008001

### Release Progress

This issue tracks release [2107092322000](https://github.com/ampproject/amphtml/releases/tag/2107092322000). See [new commits](https://github.com/ampproject/amphtml/compare/2107030008001...2107092322000) since the previous Stable channel release.

- [x] Release 2107092322000 promoted to Experimental and Beta (opt-in) channels (Tue, Jul 13, 2021, 2:18 PM GMT-4)
- [x] Release 2107092322000 promoted to Experimental and Beta (1% traffic) channels (Wed, Jul 14, 2021, 1:32 PM GMT-4)
- [x] Release 2107092322000 promoted to Stable channel (Tue, Jul 20, 2021, 12:39 PM GMT-4)

### Notifications

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment]
End of a quiet week. Co-assigning to Esther who is next week's on-duty for stable promotion + close out. 👍
