### ISSUE TITLE
🚄 Tracking issue for release 2107170150000

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#35308]
### Release Version

2107170150000

### Previous Release Version

2107092322000

### Release Progress

This issue tracks release [2107170150000](https://github.com/ampproject/amphtml/releases/tag/2107170150000). See [new commits](https://github.com/ampproject/amphtml/compare/2107092322000...2107170150000) since the previous Stable channel release.

- [x] Release 2107170150000 promoted to Experimental and Beta (opt-in) channels (Tue, Jul 20, 2021, 1:07 PM GMT-4)
- [x] Release 2107170150000 promoted to Experimental and Beta (1% traffic) channels (Wed, Jul 21, 2021, 12:26 PM GMT-4)
- [x] Release 2107170150000 promoted to Stable channel (Tue, Jul 27, 2021, 1:09 PM GMT-4)

/cc @ampproject/release-on-duty
