### ISSUE TITLE
🚄 Tracking issue for release 2107240354000

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#35415]
### Release Version

2107240354000

### Previous Release Version

2107170150000

### Release Progress

This issue tracks release [2107240354000](https://github.com/ampproject/amphtml/releases/tag/2107240354000). See [new commits](https://github.com/ampproject/amphtml/compare/2107170150000...2107240354000) since the previous Stable channel release.

- [x] Release 2107240354000 promoted to Experimental and Beta (opt-in) channels (Tue, Jul 27, 2021, 10:35 AM GMT-4)
- [x] Release 2107240354000 promoted to Experimental and Beta (1% traffic) channels (Wed, Jul 28, 2021, 1:19 PM GMT-4)
- [x] Release 2107240354000 promoted to Stable channel (Tue, Aug 3, 2021, 3:06 PM GMT-4)
- [x] Release 2107240354000 promoted to LTS channel (Tue, Aug 10, 2021, 9:16 AM GMT-7)

### Notifications

/cc @ampproject/release-on-duty
