### ISSUE TITLE
🚄 Tracking issue for release 2107302322000

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#35504]
### Release Version

2107302322000

### Previous Release Version

2107240354000

### Release Progress

This issue tracks release [2107302322000](https://github.com/ampproject/amphtml/releases/tag/2107302322000). See [new commits](https://github.com/ampproject/amphtml/compare/2107240354000...2107302322000) since the previous Stable channel release.

- [ ] Release 2107302322000 promoted to Experimental and Beta (opt-in) channels (CL_SUBMIT_TIME)
- [ ] Release 2107302322000 promoted to Experimental and Beta (1% traffic) channels (CL_SUBMIT_TIME)
- [ ] Release 2107302322000 promoted to Stable channel (CL_SUBMIT_TIME)

### Notifications

/cc @ampproject/release-on-duty
