### ISSUE TITLE
🚄 Release tracking issue for release `2108052321000`

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#35622]
### Release Version

`2108052321000`

### Previous Release Version

`2107302322000`

### Release Progress

This issue tracks release [`2108052321000`](https://github.com/ampproject/amphtml/releases/tag/2108052321000). See [new commits](https://github.com/ampproject/amphtml/compare/2107302322000...2108052321000) since the previous Stable channel release.

- [x] Release `2108052321000` promoted to Experimental and Beta (opt-in) channels (Wed, Aug 11, 2021, 12:32 PM GMT-7)
- [ ] Release `2108052321000` promoted to Experimental and Beta (1% traffic) channels ()
- [ ] Release `2108052321000` promoted to Stable channel ()

### Notifications

/cc @ampproject/release-on-duty
