### ISSUE TITLE
Bento Tracking Issue: React/Preact compatibility

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#35678]
### Description

There are some nuances in React and Preact compatibility we need to address to ensure our Bento components written in Preact are well built in React for their releases. At the very least, there should be no warnings when running our components in React development mode. This is a tracking issue for the effort in doing so.

- [x] `react.Fragment` and `preact.Fragment` are not the same type - #35412
- [ ] Do not pass unneeded DOM attributes/props - #35553
- [x] Use of `className` (React build) and `class`(Preact builds) #35722
- [x] Use of `tabIndex` preferred to `tabindex` #35722
- [x] Use of `props.children` should use the [Children API](https://preactjs.com/guide/v10/differences-to-react/#children-api) in `preact/compat` where relevant #36154
- [x] camelCase [SVG props inside of JSX ](https://preactjs.com/guide/v10/differences-to-react/#svg-inside-jsx) for React builds and kebab-case for Preact builds #35722
- [x] Use of [`onInput` and `onChange`](https://preactjs.com/guide/v10/differences-to-react/#use-oninput-instead-of-onchange)
- [x] Use of [`onDblClick` and `onDoubleClick`](https://preactjs.com/guide/v10/differences-to-react/#main-differences)
- [x] Registered events are supported via [GlobalEventHandlers](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers) and [SyntheticEvents](https://reactjs.org/docs/events.html)
- [x] Pass correctly typed values to DOM, i.e. `rtl="false"` preferred to `rtl={false}` - #35696

### Alternatives Considered

n/a

**Comment by caroqliu** [comment]
Wondering if @ampproject/wg-infra can help out with the last bit here -- we need the React build from the Preact sourcecode to make a few prop replacements based on preferred syntax specific to the library. In the following list of props, the left hand side should be enforced or linted to the given casing in our sourcecode (preact) and the right hand side should be the result of transforming for the React build:
- `allowfullscreen` -> `allowFullScreen`
- `class` -> `className`
- `datetime` -> `dateTime`
- `frameborder` -> `frameBorder`
- `srcset` -> `srcSet`
- kebab-cased svg attributes -> camelCased svg attributes

The build is more urgent than the lint, but both are important for compatibility with their respective libraries.

**Comment by estherkim** [comment]
re: runtime performance - good question! I don't know. Open to moving it to the build stage if we see it being too expensive.

**Comment by alanorozco** [comment]
> No performance issues in using the plugin because it is already being imported.

Not to split hairs, but there's a ~2.6KB uncompressed impact from bundling the rest of `preact/compat`. When using what we already import, this code is DCE'd.

Runtime performance can be audited from [this snippet](https://github.com/preactjs/preact/blob/master/compat/src/render.js#L116-L191). From a quick look, we're evaluating the props names, and creating a second props object every time we render a `VNode` that corresponds to an element.

If we ensure that our source has props in React-style, how are we accomplishing that? Do we know of an existing transform that we can run on our codebase?

I feel like we'd be doing a similar amount of work either way, but feel free to correct me.

**Comment by caroqliu** [comment]
Thanks for performing the analysis here, Alan. 

> If we ensure that our source has props in React-style, how are we accomplishing that? Do we know of an existing transform that we can run on our codebase?

I assume it would be a change on the [`preact-preferred-props`](https://github.com/ampproject/amphtml/blob/main/build-system/eslint-rules/preact-preferred-props.js) lint rule, which currently enforces an non-exhaustive set into Preact style, and could be modified to prefer React-style.
