### ISSUE TITLE
Bento Tracking Issue: 3p Iframe Support

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#35676]
### Description

[Building a Bento Iframe Component](https://github.com/ampproject/amphtml/blob/main/docs/building-a-bento-iframe-component.md) outlines how to build components in the Bento paradigm which use either an iframe directly or a proxy iframe for 3p embeds. There are a few AMP contributor and devX pain points with the current model. This is a tracking issue to organize the efforts so that contributing and using one of these components in any mode (AMP, Bento, Preact) is straightforward from start to finish!

- [x] Make build constants available in Storybooks #35560
- [x] Extricate `deserializeMessage` from logging system (which causes errors in Preact mode) #35563
- [x] Default and overridable `bootstrap` and `src` props for the `ProxyIframeEmbed` should not depend on AMP runtime #35669
- [ ] Components using code in `3p/` should trigger build when run in Storybooks
- [ ] `ProxyIframeEmbed` `src` and `options` props should be simplified to provide a clear API surface. For example, `<Twitter options={{limit, momentId}}>` should also be supported as `<Twitter limit={limit} momentId={momentId}>`. This is particularly noticeable if there is only one such prop needed, i.e. `<Twitter options={{tweetId}}>` -> `<Twitter tweetId={tweetId}>`. This is even more confusing for `Reddit` whose `src` prop passes to the `ProxyIframeEmbed` `src` and is not used, as one might expect, for the Reddit iframe url `src`. 
- [ ] Update documentation when the above work is complete

### Alternatives Considered

n/a
