### ISSUE TITLE
tracker: migrate release tagger to GitHub

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#35729]
Features:
- [ ] Create release for beta, cherry-picks
- [ ] Publish release for stable, lts, cherry-picks
- [ ] Mark release as rolled back for rollbacks 
- [ ] Add labels to PRs for beta, stable, lts, cherry-picks
- [ ] Remove labels from PRs for rollbacks
- [ ] Create release channel tracker comment on PR merge
- [ ] Update release channel tracker comment for beta, stable, lts, rollback

PRs:
- https://github.com/ampproject/amphtml/pull/35387
- https://github.com/ampproject/amphtml/pull/35459
- https://github.com/ampproject/amphtml/pull/35507
- https://github.com/ampproject/amphtml/pull/35692
- https://github.com/ampproject/amphtml/pull/35705
- https://github.com/ampproject/amphtml/pull/35719
- https://github.com/ampproject/amphtml/pull/35727

Non PRs:
- [ ] Add environment + secret for github action
- [ ] (internal) Trigger github action with pubsub subscriber
- [ ] (internal) Delete deprecated release tagger
