### ISSUE TITLE
🚄 Release tracking issue for release 2108280007001

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#35886]
### AMP Version

[2108280007000](https://github.com/ampproject/amphtml/releases/tag/2108280007000)

### Promotions

- [x] 2108280007000 promoted to Experimental and Beta (opt-in) channels (Tue, Aug 31, 2021, 3:04 PM GMT-4)
- [x] Release 2108280007001 created with cherry pick #35892 (Wed, Set 1, 2021)
- [x] 2108280007001 promoted to Experimental and Beta (1% traffic) channels (Fri, Sep 3, 2021, 12:17 PM GMT-4)
- [x] 2108280007001 promoted to Stable channel (Tue, Sep 7, 2021, 4:19 PM GMT-7)
- [x] 2108280007001 promoted to LTS channel (Mon, Sep 13, 2021, 7:45 AM GMT-4)

/cc @ampproject/release-on-duty
