### ISSUE TITLE
Migrate Storybook Knobs to Controls

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#35923]
Storybook [Knobs are deprecated](https://www.npmjs.com/package/@storybook/addon-knobs) and we should replace them with [Controls.](https://storybook.js.org/docs/react/essentials/controls)

## General work

- [x] Forbid using in new Stories (#35991)
- [x] Install `addon-controls` (#35915)
- [x] Uninstall `addon-knobs` (#37681)
- [x] Update extension template (#35915)

## Migrating Stories

For general guidance, see Storybook docs: [**How do I migrate from addon-knobs?**](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs) 

Please also make sure to follow our [**Style Recommendations**](https://github.com/ampproject/amphtml/blob/main/build-system/tasks/storybook/README.md#style-recommendations).

You'll also have to remove the migrated files from this allowlist to pass CI. Files in this list are also disabled on Storybook, so you have to remove them from `allowlist` for them to show up at all.

https://github.com/ampproject/amphtml/blob/375cfb59dd02cc74bf776eac7da3a325d41ebf20/build-system/test-configs/forbidden-terms.js#L720-L724

### Tasks

- [x] Update Stories 0...15
  @alanorozco (#35915)
- [x] Update Stories 15...30
  @alanorozco (#35930)
- [x] Update Stories 30..34 (@dmanek)
  @dmanek (#37697)
  ```
  extensions/amp-date-display/1.0/storybook/Basic.amp.js
  extensions/amp-date-display/1.0/storybook/Basic.js
  extensions/amp-iframe/0.1/storybook/Basic.amp.js
  extensions/amp-iframe/1.0/storybook/Basic.amp.js
  extensions/amp-image-slider/0.1/storybook/Basic.amp.js
  ```
- [x] Update Stories 35..39
  @kvchari (#37727)
  ```
  extensions/amp-inline-gallery/1.0/storybook/Basic.js
  extensions/amp-stream-gallery/1.0/storybook/Basic.amp.js
  extensions/amp-stream-gallery/1.0/storybook/Basic.js
  extensions/amp-lightbox-gallery/1.0/storybook/Basic.amp.js
  extensions/amp-lightbox-gallery/1.0/storybook/Basic.js
  extensions/amp-lightbox/1.0/storybook/Basic.amp.js
  ```
- [x] Update Stories 40..44
  @rbeckthomas  (#37729)
  ```
  extensions/amp-selector/1.0/storybook/Basic.amp.js
  extensions/amp-selector/1.0/storybook/Basic.js
  extensions/amp-sidebar/0.1/storybook/Basic.amp.js
  extensions/amp-sidebar/1.0/storybook/Basic.amp.js
  extensions/amp-sidebar/1.0/storybook/Basic.js
  ```
- [x] Update Stories 45..49
  @rbeckthomas  (#37850)
  ```
  extensions/amp-soundcloud/1.0/storybook/Basic.amp.js
  extensions/amp-soundcloud/1.0/storybook/Basic.js
  extensions/amp-lightbox/1.0/storybook/Basic.js
  extensions/amp-timeago/1.0/storybook/Basic.js
  ```
- [x] Update Stories 50..53
  @alanorozco (#37685)
- [x] Update Stories 54..61 (video)
  @rbeckthomas (#37860)
  ```
  extensions/amp-video/1.0/storybook/Basic.amp.js
  extensions/amp-video/1.0/storybook/Basic.js
  extensions/amp-video-iframe/1.0/storybook/Basic.amp.js
  extensions/amp-vimeo/1.0/storybook/Basic.amp.js
  extensions/amp-vimeo/1.0/storybook/Basic.js
  extensions/amp-youtube/0.1/storybook/Basic.amp.js
  extensions/amp-youtube/1.0/storybook/Basic.amp.js
  extensions/amp-youtube/1.0/storybook/Basic.js
  ```
- [x] Update Stories 62..65
  @rbeckthomas  (#37730)
  ```
  src/builtins/storybook/amp-layout.amp.js
  src/preact/storybook/Context.js
  src/preact/storybook/Wrappers.js
  ```
