### ISSUE TITLE
Tracking Issue for CTA Migration Page Outlink

### ISSUE THREAD

**Issue by jshamble** [ampproject/amphtml#36035]
### Description

[Page Outlink CTA Migration Design Doc](https://docs.google.com/document/d/1lPwJ01CHXXlNexeJUz7QI7v3pFlbF6Qj_9kT0fjDSME/)

Code
- [x] Replace <amp-story-cta-layer> with <amp-story-page-outlink>
- [x] Create client side experiment CL
- [x] Set up branch level experiment in AMP (amp-story-ads-page-outlink)

Analysis
- [ ] Monitor/Ramp experiment
- [ ] 🛳⛴🚢

**Comment by ychsieh** [comment]
Closing this because it's been stale for a long time. Feel free to reopen it is actually not finished yet and we still have the intent to do it. 

cc: @calebcordry @jshamble @powerivq
