### ISSUE TITLE
🍱 [amp-gpt:1.0] Bento tracking issue

### ISSUE THREAD

**Issue by AnuragVasanwala** [ampproject/amphtml#36684]
### High-Level Requirements

_To be updated as information becomes available._

| Consideration           | Ready When                                 | Status  |
| ----------------------- | ------------------------------------------ | ------- |
| Component Compatibility | Feature checklist is covered               | 🚧 |
| Testing                 | Unit tests and pre-existing e2e tests pass | 🚧 |
| Internationalization    | <fill this out>                            | ✖️ |
| Analytics               | <fill this out>                            | ✖️ |
| Accessibility           | Audit performed                            | ✖️ |
| Page Experience         | Audit performed                            | ✖️ |
| Documentation           | Written                                    | 🚧 |
| Storybook               | Samples written in Preact and AMP          | 🚧 |

### Feature Checklist

_To be updated as information becomes available._

### Features
- [x] Intersection Observer
- [x] Fallback DIV

### Existing attributes
- [x] `ad-unit-path`
- [x] `disable-initial-load`
- [ ] `slot-targeting`
- [ ] `page-targeting`
- [x] `size`
- [x] `opt-div`

### Actions
- [ ] `setTarget`
- [ ] `setPageTarget`
- [ ] `getTarget`
- [ ] `getPageTarget`
- [ ] `clearTarget`
- [ ] `clearPageTarget`
- [ ] `display`
- [ ] `refresh`

### Events
_To be updated as information becomes available._

### Analytics Events
_To be updated as information becomes available._

### Migration Notes

Migration does not apply to this component.

### Open Tasks

_To be updated as information becomes available._

- [ ] Action Implementation
- [ ] Complete Storybook
- [ ] Cleanup, `lint`, `prettify`
- [ ] Code commenting

### Notifications

/cc @ampproject/wg-bento
