### ISSUE TITLE
[Punch List] - Video in AMP

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4154]
This is a _tracker_ issue for related work planned for video enhancements in AMP.
- [x] Define the AMP JavaScript interface for the shared video interface as defined in #3945
- [x] Implement the above interface for `amp-video` 
- [x] Implement the above interface for `amp-youtube` 
- [x] Implement an AMP video manager that can discover what elements are videos, knows which one is currently playing, and provides utilities to manage all videos as a group (e.g. playing one, would pause others, etc...)  
- [ ] Support muted autoplay
  - [x] `<amp-video>`
  - [x] `<amp-youtue>`
  - [x] `<amp-dailymotion>` https://github.com/ampproject/amphtml/issues/6285
  - [ ] `<amp-video-iframe>` https://github.com/ampproject/amphtml/issues/8524
- [ ] Support dock-and-minimize UX for playing videos #9702 #9961 #9962 #9993 
  - [x] Scroll-bound docking
  - [x] Drag, drop & snap to corner
  - [x] Minimized video controls
  - [ ] Customization attributes
- [x] Support Media API https://github.com/ampproject/amphtml/issues/7272
- [x] Support "Go To Fullscreen" on orientation change #5380 
- [x] Support Video Analytics #9902 
- [x] Documentation and DevRel related work
  - [x] `autoplay` on `amp-by-examples`
  - [x] `click-to-play` overlay
- [ ] Custom controls
- [ ] Play closed captions for autoplay
- [ ] Support "overlays" for `start`, `end`
- [ ] Support `during` overlay and allow `amp-animation`'s timeline to be synced with video timeline
- [ ] Support custom controls
- [ ] Support Hero Video https://github.com/ampproject/amphtml/issues/7510
- [x] Support Mode: Video in lightbox 2.0  (part of work is in lightbox 2.0 efforts #4152)
- [ ] Support Mode: Video in fixed position (maybe both `fixed` and `fixed hero`)
- [ ] Support ability for referrers to specify a `videoId` in the URL to auto-play upon page load. (`videoId` optional, defaults to primary video). Maybe also allow the mode to be specified by the referrer.

**Comment by aghassemi** [comment]
@cramforce @rudygalfi @ericlindley-g Here is a rough punch list for video related work we need to do. Feel free to edit. I will spin off more Github issues as time comes for each task.

**Comment by rudygalfi** [comment]
Note: This covers #3799.

**Comment by tomasvts** [comment]
There is no autoplay attribute propagation in chrome v53 android.
muted autoplay is only working on IOS in the last version 1475106123549 thanks to `fixIOSCanplayEventForAutoplay_` method.

**Comment by aghassemi** [comment]
@tomasvts We don't actually propagate the `autoplay` attribute and call `play()` manually (even in `fixIOSCanplayEventForAutoplay_`, `autoplay` attribute is removed afterwards). 

Are you seeing `autoplay` not working in Android or iOS? (There is a bug with Chrome autoplay in 4G/LTE which is fixed by https://github.com/ampproject/amphtml/pull/5228 - will be in the next release)

**Comment by rudygalfi** [comment]
@aghassemi Wondering if this list needs to be updated at all, particularly the amp-youtube parts?

**Comment by randallbpotter15** [comment]
Any more information on amp-video-iframe?

**Comment by aghassemi** [comment]
@randallbpotter15 Not yet, that being said, `amp-video-iframe` is fairly simple to add but until the underlying video player implements it, it won't do anything. Is there a particular video-player that you like to embed using `amp-video-iframe`? Are you in control of the underlying player and able to implement the expected behaviour (e.g. receiving a postMessage and pausing/playing the video and sending messages back to parent frame on video events such as pause/play?).

**Comment by randallbpotter15** [comment]
@aghassemi We are currently using an iframe to serve our video player as we have "pre-roll" ad needs and event management for analytics.  We are always interested to hear about potential upgrades to the amp video experience.  We are in control of the underlying player, both from one we made to work on AMP to our in-house version here at CNN.

Would love to learn more etc.

**Comment by aghassemi** [comment]
@randallbpotter15 That's great! CNN's video player is a perfect candidate for `amp-video-iframe` as a generic `amp-cnn-player` does not make sense in AMP.

Having a compelling use-case and a partner to work with for the initial version of `amp-video-iframe` is precisely what we need to kick of the work on `amp-video-iframe`. I will start work on this soon under an experimental flag and I assume you have the interest and hopefully some cycles to implement and collaborate on the approach.

The video-interface API will evolve overtime, currently the API is focused on providing hooks for managing autoplay and other playback related UX features we like to implement it AMP (rather than, say, analytics). `<amp-video>` and `<amp-youtube>` currently implement the interface, some examples of AMP's autoplay UX can be found [here](www.popsugar.com/food/Avocado-Toast-Recipes-Video-36701287/amp) and [here](https://amphtml-ae5fc.firebaseapp.com/caption/test/manual/empty.amp.html). This is the sort of UX CNN can expect with `<amp-video-iframe autoplay src="cnn.com/url"></amp>` when implemented.

**Comment by randallbpotter15** [comment]
@aghassemi I'd be happy to check this out with you all.  @jmadler and some others on the team have my contact information for here at CNN.

**Comment by matAtWork** [comment]
Is the nascent `<amp-video-iframe>` documented anywhere? We (dailymail) are also struggling with analytics, etc. (see https://github.com/ampproject/amphtml/issues/6234#issuecomment-296156703)

**Comment by aghassemi** [comment]
@matAtWork `<amp-video-iframe>` doesn't exist yet :) but planned. Please subscribe to #8524for updates.
For your analytics needs, a solution similar to your and my comments on  #6234 (independent of  `<amp-video-iframe>`) should work. Let's continue the discussion on #8524.

**Comment by shimonenator** [comment]
@aghassemi wanted to add that CBS would also be interested in adapting `<amp-video-iframe>` and the video interface.

**Comment by wassgha** [comment]
@aghassemi  #6285 checks off `amp-dailymotion` on the list

**Comment by wassgha** [comment]
Can we add Media Session API and fullscreen on landscape to the punch list?

**Comment by aghassemi** [comment]
@wassgha done and added a few more items around start/end overlays and allowing `amp-animation`'s timeline to be tied to video timeline (see comments on #8971 for background).

**Comment by ampprojectbot** [comment]
This issue hasn't been  updated in awhile. @aghassemi Do you have any updates?

**Comment by aghassemi** [comment]
it's a tracker

**Comment by ampprojectbot** [comment]
This issue hasn't been  updated in awhile. @aghassemi Do you have any updates?
