### ISSUE TITLE
Tracking Bug: amp-analytics in friendly iframes

### ISSUE THREAD

**Issue by avimehta** [ampproject/amphtml#5657]
This bug tracks all the work for enabling amp-analytics in friendly iframe components (currently A4A).

Things to be done:
- [ ] Provide additional variables for amp-ads
- [x] Restrict and override URL replacements implementation for embed
- [x] Allow iframe host as an element whose visibility can be measured.
- [x] Restrict selectors to only select elements within embeds. (#5749)
- [x] Disallow scroll and custom triggers in embeds (#5658)
- [x] Update example for amp-ad.

**Comment by rudygalfi** [comment]
Any updates here?
