### ISSUE TITLE
Extension Analytics V1

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#8202]
This is a tracker issue for #6417 

- [x] insert `<amp-analytics>` for extension
- [x] Limit support for certain eventType (#8389)
- [x] Apply replacement on selector/selectorMethod of the config (#8389)
- [x] Allow extension to load analytics extension
- [ ] Refactor customEventTracker. Change it from mapping an eventType to observer, to mapping an [eventType and extension] to observer (#8304)
- [x] Add restriction on url replacement (#8360)
- [ ] Read default config
- [x] Remove `injectActiveViewAmpAnalyticsElement` function [#8628]

**Comment by rudygalfi** [comment]
@zhouyx Can you close? Let's document the remaining items that aren't done, but which will be considered upon request.

**Comment by zhouyx** [comment]
Closing this for now. Will create separate issue to address the customEventTracker issue
