### ISSUE TITLE
Position Observer Improvement

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9208]
Tracker issue to improve positionObserver and support PositionObserver for AMP Inabox in non AMP host.
- [x] Enable communication between AMP Inabox and AMP host (#10867)
- [x] AMP host send position data to inabox (#10987)
- [x] Inabox pull position data from AMP host (#11017)
- [x] Introduced Viewport method to get latest clientRect position async (#11148)
- [x] Make PosOb work transparently across w/o aware of runtime version. (#10813)
- [x] Add Example for PositionObserver in AMP Inabox in non AMP host. (#11247)

**Comment by ampprojectbot** [comment]
This issue hasn't been  updated in awhile. @zhouyx Do you have any updates?
