### ISSUE TITLE
form verifier launch tracker

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9308]
- [ ] 1 partner waiting for feature tries it in experimental and provides feedback ( @ericlindley-g )
- [ ] thumbs up from @dvoytenko on the final design
- [ ] ampbyexample.com sample
- [ ] integration test in `integration/test-integration-form.js`

then
- [ ] flag flip for experiment to 100%
- [ ] blog/tweet? ( @ericlindley-g )

then (after few weeks of experiment 100% live in prod)
- [ ] #9174 

@cvializ checklist to help manage the form verifier launch.

**Comment by ericlindley-g** [comment]
Thanks for filing!

Is there already documentation in an .md?

May be good to combine multiple form-related things into a single blog post (like de-bounced input trigger / autocomplete) — definitely good to get it all on the radar, regardless.

**Comment by aghassemi** [comment]
Closing tracked under # #9696 #9700
